### ISSUE TITLE
Twisted==11.1.0 requirement

### ISSUE THREAD

**Issue by anatolijd** [graphite-project/carbon#105]
requirements.txt suggests this specific Twisted version to be installed (for both master and megacarbon branches):

Twisted==11.1.0
git+git://github.com/graphite-project/whisper.git#egg=whisper
mocker==1.1

Is carbon really specific version-bound ? 
Perhaps, this can be changed to 'Twisted>=11.1.0' as 12.2.0 is already available.

**Comment by piotr1212** [comment]
This isn't the case anymore, closing. `Twisted>=13.2.0`
