### ISSUE TITLE
handling of unicode input breaks web GUI

### ISSUE THREAD

**Issue by linkslice** [graphite-project/carbon#131]
If you connect to the carbon cache and insert unicode characters, the directories and files names are created on the filesystem, but the graphite browser can no longer display any directories.

**Comment by Low-power** [comment]
I think this issue still exist in current version.

**Comment by deniszh** [comment]
That's really depends on your python version (for 2.7 it will never work, for 3 maybe it will), locale and filesystem, so, in current setup this issue is very broad and I doubt that it will be ever fixed.
