### ISSUE TITLE
setup.py should not attempt to do root operations

### ISSUE THREAD

**Issue by dmick** [graphite-project/carbon#173]
Installation is tricky enough without requiring root; rather than copying /etc/init.d scripts, setup.py should simply point to them and recommend that the user install them (since it's only coded for 'redhat' anyway).

**Comment by dmick** [comment]
graphite's really not very active anymore, is it?

**Comment by deniszh** [comment]
It depends what you mean saying “very active”.  Developing is ongoing, new
release is every 6 months or so... Everything else is in the community’s
hands.

**Comment by piotr1212** [comment]
setup.py does not do this any more, see https://github.com/graphite-project/carbon/blob/master/setup.py#L68-L69 and https://github.com/graphite-project/carbon/commit/976dd083c12403c050788ba28b250b10a3fda40e
