### ISSUE TITLE
Run carbon-cache.py as a windows service

### ISSUE THREAD

**Issue by Kapaski** [graphite-project/carbon#192]
Hi,

This sounds propably a rare asked question:
I managed to install Graphite carbon, whisper and webapp on windows - the whole things works well. So down to detailed issues, this one seems pretty annoying. Is there a thought that how to start carbon-cache.py as a windows service that can direct me to right way ? Thanks.

Regards

James

**Comment by Kapaski** [comment]
wow stale bot, after 7 years, well done!

**Comment by adiroiban** [comment]
Did you managed to get this done?

One way to start things are a service is to use tools like [NSSW](https://nssm.cc/) or https://github.com/mtkennerly/shawl
