### ISSUE TITLE
Received data that exceeds Integer.max value

### ISSUE THREAD

**Issue by Kapaski** [graphite-project/carbon#193]
Hello,

I recently found this issue in Graphite 0.9.12 (after updated from 0.9.10). There is a value 'Available Memory Bytes' now keeps showing as "-2147483648.0" which seems like the actual values are exceeding Integer.Max. and the data type shouldn't be Integer in fact.

Could anyone help me about where and how should I check the relative data type setup in Graphite? At least I want to make sure whether this wrong data type was set in Graphite. Thanks

PS. the data source for this is windows performance counter, where I can see in its code it is using float as type to report to Graphite:

```
public float? ReportValue()
    {
        if (this.disposed)
            throw new ObjectDisposedException(typeof(PerformanceCounter).Name);

        try
        {
            // Report current value.
            return this.counter.NextValue();
        }
```

Regards

James

**Comment by Kapaski** [comment]
Hi any reason? will be fixed? not an issue? not true? but anything other than just close it?

**Comment by deniszh** [comment]
Sorry, @Kapaski, I was not sure if that's still relevant.
Graphite supporting very big number as value, definitely. So, it can be bug or misconfiguration in Codahale / dropwizard, maybe together with 0.9.12, but I doubt so.
So, it's better to ask dropwizard guys.

**Comment by Kapaski** [comment]
@deniszh that's all right. wasn't complaining but curious

I'm happy to close and park this one now though as we are not using that old version any more, agree that it might be a legacy issue by now.

**Comment by deniszh** [comment]
👍 
Thanks!
