### ISSUE TITLE
console.log of writer process(es) is being spammed with unix timestamp

### ISSUE THREAD

**Issue by zstyblik** [graphite-project/carbon#195]
Hello,

for an unknown reason, 'console.log' of writer process(es) is being spammed by the following lines:

```
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024110
14/12/2013 13:32:37 :: 1387024080
```

It's a unix timestamp, alright. But why? What is it doing there and why isn't there more info? Any thoughts? Does somebody else having the same issue?

Branch megacarbon + ceres.

Thank you.

**Comment by Zagrebelsky** [comment]
The same problem. CentOS
