### ISSUE TITLE
IPv6 support needed

### ISSUE THREAD

**Issue by aww-yiss** [graphite-project/carbon#209]
For hosts with IPv6 interfaces, there doesn't seem to be any way to bind to anything but the IPv4 0.0.0.0 interface, need to add support for IPv6

**Comment by obfuscurity** [comment]
Ugh, opening this back up since we actually list `Twisted==11.1.0` in requirements.txt. Can anyone suggest a stable Twisted version for ipv6 support?

**Comment by obfuscurity** [comment]
Even though it's a little old, I'm leaning towards `>=13.2.0`. I believe that a number of people have been running this version successfully with Carbon.

**Comment by obfuscurity** [comment]
Because lazy Sundays.
