### ISSUE TITLE
Best place to set carbon-aggregator  in a graphite cluster ( rules vs consistent hashing)?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#251]
Hi guys.

I'm planning a big graphite cluster and I've tested with relay (now configured with rules) in front of carbon caches, but I need now to add a carbon-aggregator  daemon and I have doubts on the best place to put it.

we are considering a load  balancer in front of carbon daemons doing a RR balancing for all carbon clients.

So If CA=carbon-aggregator/CR=carbon-relay/CC=carbon-cache/LB=load balancer
## Config 1

```

      +->(node1)  [CR1]->[CA1]->[CC1]
     |
[LB]-+
     |
      + ->(node2) [CR2]->[CA2]->[CC2]
```

This can be good if 
RELAY_METHOD = rules ( ^env1 =>node 1 ^env2 => node2)
REPLICATION_FACTOR = 1

so I can assure that all metric beginning with the same metric name ( same environment)  can be aggregated independent of what is the receiver node of the metric.
## Doubts

what happens if I configure   RELAY_METHOD = consistent-hashing ? There is any way to do this layout scheme with a generic load balancer in front of carbon daemons ?

Which is the best approach for this layout ?

**Comment by wrossmann** [comment]
> What C-H basically means is that the sender maps out each metric to a specific target in an effort to distribute all metrics evenly throughout the "hash ring". This works well with one large caveat; any time the hash ring changes (e.g. adding a new node), **that map gets blown away and all of the metric destinations change**. You're responsible for moving the existing data around to their new homes.

I'm not certain if this was the case as of the time of the original writing, and if so it was not a proper implementation of a consistent hashring, but as of today the bolded statement is incorrect.

If the number of nodes in a cluster changes only a subset of metrics move from an existing node to the newly added node. *No metrics will shuffle between the pre-existing nodes.*

Eg: Assuming an ideally-distributed hashring in a cluster of 2 nodes [A and B], adding a third node [C] would cause 1/3 of all metrics destinations on nodes A and B to move to node C, however _no_ metric destinations would move between nodes A and B.

Posted for the sake of clarity.
