### ISSUE TITLE
documentation of MAX_CREATES_PER_MINUTE needs clarification

### ISSUE THREAD

**Issue by wk66** [graphite-project/carbon#262]
In the file _carbon.conf.example_ you'll find documentation about **MAX_CREATES_PER_MINUTE**. It says, that with low values of that setting

> it will take much longer for those metrics' database files to all get created and
> thus longer until the data becomes usable.

which I interpret as _"the metrics you sent are queued up and written later"_. But the truth is, that some of the metrics sent in that minute are **discarded**. The documentation should state that clearly! A user who sends new metrics which shall not be lost, has to set **MAX_CREATES_PER_MINUTE** to the highest needed number. A clarification on this behaviour would save many new users hours of research where carbon put the (of course new) metrics they just sent.

In the original use cases of Graphite this may not be an issue, but think of use cases where precious data is collected once a day (maybe at high cost) and stored into carbon/graphite.

**Comment by gaborurbanics** [comment]
:+1: That was a bit confusing in the doc for me, as well. Btw, do you know if there is any plan to change this behaviour (e.g. caching those metrics instead of dropping them) or make this configurable? Thx!

**Comment by asafm-logzio** [comment]
Just got "discarded" by this as well. It's 2 sec to fix in the documentation

**Comment by deniszh** [comment]
Indeed. Wondering why everybody, like, :+1: and :100: and nobody did make 2 sec PR for fixing it...

**Comment by asafm-logzio** [comment]
I'll do it now

**Comment by deniszh** [comment]
Thanks, @asafm-logzio, appreciated ! :+1:

**Comment by gwaldo** [comment]
I actually just pushed https://github.com/graphite-project/carbon/commit/785e80ff96947ff09223116843a98e15423d90ae

I was wondering why the 2 minute complaints rather than a 2 minute fix, myself...

**Comment by gwaldo** [comment]
@deniszh I didn't notice that I wasn't working off a fork until I went to do the PR.  I'm fixing my setup now...

**Comment by obfuscurity** [comment]
Someone please also port the change to 0.9.x.

**Comment by gwaldo** [comment]
good point.  https://github.com/graphite-project/carbon/pull/463 @graphite-project/committers
