### ISSUE TITLE
STORAGE_DIR in carbon.conf has no affect

### ISSUE THREAD

**Issue by jjshoe** [graphite-project/carbon#269]
https://github.com/tmm1/graphite/blob/master/carbon/conf/carbon.conf.example#L14

Uncommenting L17 and changing the path has no affect. The only way I could find to change this path was by setting it as an environment variable. Not sure what's more wrong here, the example config, or if there is a bug in graphite/conf.py

**Comment by reynir** [comment]
The cause for this is that all the other options that depend on STORAGE_DIR gets setdefault'ed before the config is read, that is they use the default value of STORAGE_DIR. I made a crude fix in the above PR.
