### ISSUE TITLE
Add possibility to turn off console, query, creates logging

### ISSUE THREAD

**Issue by gdubicki** [graphite-project/carbon#307]
I use carbon v. 0.9.11 or 0.9.12 (it's not too easy to check that, is it?).

I turned off logging to listerner.log by setting in my `carbon.conf` this to false:
`LOG_LISTENER_CONNECTIONS = False`

I also set all other logging-related settings to false. 

(Actually only one setting:
`LOG_CACHE_QUEUE_SORTS = False`
..because settings:

```
LOG_UPDATES = False
LOG_CACHE_HITS = False
```

...were set to false by default.)

But I was not able to find settings to turn off logging to files `console.log`, `query.log`, `creates.log`.

I don't need those logs and they are filling up my disk.

Finally I followed advise from https://answers.launchpad.net/graphite/+question/107948 to replace those files with symlinks to `/dev/null` but thats a workaround.

Is there a way to turn off that logging via configuration?

**Comment by benburry** [comment]
It's possible (for both 0.9.11 and 0.9.12) to use the `LOG_CACHE_HITS` setting to control whether the `cache query for` entries are written to query.log. Set it to `False` and they won't be written.

I don't believe it's possible to control either of the other two, nor entirely stop writing to those files using only config settings
