### ISSUE TITLE
Moving forward with 0.9.13 and 0.10.x

### ISSUE THREAD

**Issue by jssjr** [graphite-project/carbon#312]
Calling all @graphite-project/committers.

I'm happy to continue to help maintain this project, but there are some questions I have that are likely to have opinionated answers.

**Where do we go from 0.9.x**

The [0.9.13 milestone](https://github.com/graphite-project/carbon/milestones/0.9.13) is nearly complete. There are a couple of extraneous release tasks like updating readme's and bumping some metadata, but beyond that it's pretty much ready to :ship:.

This leaves the project with two potential paths forward. The `master` branch (which is already *way* behind 0.9.x and will require significant cleanup) or the `megacarbon` branch. Megacarbon to me seems like a step backwards to me. I prefer the UNIX mentality of do one thing and do it well, and megacarbon seems to squash several tasks into one. (relay/routing, aggregation, and writing.)

I propose we create an 0.10.x branch from 0.9.x, backport anything from master and megacarbon that we want to keep, then rename `0.10.x` to master and drop `0.10.x` until we're ready to cut an `0.10.0` release.

Thoughts?

**Comment by obfuscurity** [comment]
Closing this out as there's been a lot of time has passed since the original discussion. There is a separate issue for [pluggable storage](https://github.com/graphite-project/carbon/pull/216) that I intend to address post-1.0.
