### ISSUE TITLE
Installing graphite-carbon unattended

### ISSUE THREAD

**Issue by davideicardi** [graphite-project/carbon#328]
I'm trying to create an automation script that install Graphite on Ubuntu 14.04 without user interaction (unattended).
I try with the following command:

```
sudo apt-get -q -y --force-yes install graphite-carbon=0.9.12-3
```

During the installation, I will be asked whether I want Carbon to remove the database files.

Do you know if there is a way to run an installation without these kind of UI? I have only this problem with Graphite-carbon.

I have also tried using

```
export DEBIAN_FRONTEND=noninteractive
```

without success.

What is the best way to install graphite-carbon without user interaction?

**Comment by jamtur01** [comment]
And there's always:

```
echo "graphite-carbon graphite-carbon/postrm_remove_databases boolean false" | sudo debconf-set-selections
```
