### ISSUE TITLE
Carbon-relay UDP

### ISSUE THREAD

**Issue by ikkaro** [graphite-project/carbon#329]
Can carbon-relay listen in UDP protocol?

**Comment by MarkDordoy-JustEat** [comment]
Are you able to elaborate on how i can enable my carbon relay to accept udp traffic? 

Thanks

**Comment by obfuscurity** [comment]
@MarkDordoy-JustEat https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example#L84-L86

**Comment by MarkDordoy-JustEat** [comment]
Im assuming i can use those config settings, but under the carbon-cache section of the conf file?

**Comment by MarkDordoy-JustEat** [comment]
Also, thanks for replying :+1:

**Comment by obfuscurity** [comment]
Those settings are universal to the Carbon receivers. IOW, they'll work for any Carbon service types.

https://github.com/graphite-project/carbon/blob/77e1eb09b9708c91ffbca6e94ffd46e1143b04ee/lib/carbon/service.py#L139-L156
