### ISSUE TITLE
Very high amount of `MetricLineReceiver connection with ..` logs

### ISSUE THREAD

**Issue by vvo** [graphite-project/carbon#34]
Hi, we got a very large amout (1GB per day) amout of theses logs:

``` bash
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56607 closed cleanly
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56608 established
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56608 closed cleanly
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56609 established
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56609 closed cleanly
03/09/2012 08:59:35 :: MetricLineReceiver connection with 127.0.0.1:56610 established..
```
1. Why so many of them?
   We use statsd to send meters to graphite and we send a lot of them but why logs are showing so much connect/disconnect?
   Perhaps we are misusing listeners.
2. Should carbon have a log level configuration option?

It seems you already created two configuration options for disabling some logging:

``` bash
LOG_UPDATES = False
LOG_CACHE_HITS = False
```

Why not just have a `LOGLEVEL` which will directly map the twisted log level? http://docs.python.org/library/logging.html#logging.Logger.setLevel

**Comment by jdmarshall** [comment]
8 years later this is still on, and the suggestion for turning it off does not work.  Isn't this trace data? Why is it on by default?
