### ISSUE TITLE
blank line in blacklist.conf blacklists everything

### ISSUE THREAD

**Issue by lexelby** [graphite-project/carbon#340]
A blank line in blacklist.conf is treated as a regular expression, and blank regular expressions in python match everything (when used with re.search).  This results in the very surprising behavior that all metrics are dropped on the floor if you have a blank line in blacklist.conf.

**Comment by lexelby** [comment]
No idea if this bug still exists, but I'm quite certain it did when I created this issue.  I verified it by looking at the code.

**Comment by piotr1212** [comment]
Just tested and cannot reproduce.
