### ISSUE TITLE
Drop ".example" extension on sample (mandatory) conf files

### ISSUE THREAD

**Issue by ryan-williams** [graphite-project/carbon#362]
One confusing thing when trying to quick-start a graphite instance was having to strip the `.example` suffixes from `carbon.conf`, `storage-aggregation.conf`, and `storage-schemas.conf`.

If their contents provide workable defaults out of the box, then this is an unnecessary hurdle to put in the way of new users.

Leaving them in `conf/` next to other `.example` files will sufficiently get the message across to users that they can/should be modified.

As it is, it is pretty overwhelming to see [9 `.conf.example` files in the repo](https://github.com/graphite-project/carbon/tree/master/conf) (15 in my `/opt/graphite/conf` after installing all graphite modules) and not know which ones are necessary vs. optional for certain installations.

**Comment by obfuscurity** [comment]
You're not supposed to "drop" the suffixes, you're supposed to copy them and make your changes. There is no single "best default" configuration for everyone.

I could see putting them into a separate "example" subdirectory, but I don't think it makes any sense to turn them into running defaults.

**Comment by ryan-williams** [comment]
Yes, people will want to turn some of the 1000 available knobs once they have a simple installation set up, but I'm telling you, you're exposing a whole lot of unnecessary complexity to new users in the current setup.

**Comment by SEJeff** [comment]
Yeah I agree with @obfuscurity here. For a stack like graphite, there is no one size fits all config. Users are expected to read the docs and configure things as they see fit. Having a default for anything more than an example docker container or something doesn't really make a lot of sense.

**Comment by obfuscurity** [comment]
@ryan-williams I empathize but there's probably a better solution than what you proposed. Synthesize, for example, is highly opinionated and designed to "just work" on start. I look at that as "training wheels" for Graphite.

Not to mention, your change would break all production setups on upgrade.
