### ISSUE TITLE
Remove "match-all" and "list" schema options

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/carbon#370]
These options were added a [long](https://github.com/graphite-project/carbon/commit/401f0436f2eabd2e3122fa297bc3234bfe399f68) [time](https://github.com/graphite-project/carbon/commit/59b410cf22ee0fccb3d73aff40c001d9be113c58) ago but they were never documented. As far as I can tell, nobody even knows they exist but I want to check here to see if anyone uses them before we deprecate them.

It appears that `match-all` is intended to override the [default schema](https://github.com/graphite-project/carbon/blob/master/lib/carbon/storage.py#L193) (1m for 1w), although I believe most people just use `pattern = .*` for this instead. I suspect that this option was more relevant back when `priority` existed.

The `list` option continues to remain a mystery to me since there's no examples of how it should actually be used.

/cc @nleskiw @drawks @mleinart @jssjr @cdavis

**Comment by mleinart** [comment]
:thumbsup:

**Comment by drawks** [comment]
:+1:
