### ISSUE TITLE
IPv6 and UDP error

### ISSUE THREAD

**Issue by mkwiczalayandex** [graphite-project/carbon#374]
Hi,

Is it possible to setup graphite/carbon to listen on IPv6 UDP?
I have below error when I setup IPv6 UDP and restart service:

```
"An error has occurred: 'Couldn't listen on :::2003: [Errno -9] Address family for hostname not supported.' 
Please look at log file for more information. 
log file:"
```
And in log file I have:
```
....
27/01/2015 21:33:33 ::   File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 191, in _bindSocket
27/01/2015 21:33:33 ::     raise error.CannotListenError(self.interface, self.port, le)
27/01/2015 21:33:33 :: twisted.internet.error.CannotListenError: Couldn't listen on :::2003: [Errno -9] Address family for hostname not supported.
```
My /etc/carbon/carbon.conf for UDP:
```
ENABLE_UDP_LISTENER = True
UDP_RECEIVER_INTERFACE = ::
UDP_RECEIVER_PORT = 2003
```
I have no problem with below configurations:
IPv6 TCP
IPv4 TCP
IPv4 UDP

System information: 
Ubuntu 14.04
carbon installed as: sudo apt-get -y install graphite-web graphite-carbon
pip freeze | grep -i twisted
Twisted-Core==13.2.0

Regards,
Mariusz

**Comment by obfuscurity** [comment]
Carbon supports IPv6 only where it's supported by Twisted. According to https://twistedmatrix.com/trac/wiki/IPv6, it looks like UDP IPv6 support is only partially complete, and what *is* supported was only introduced in [14.0.0](http://twistedmatrix.com/trac/browser/tags/releases/twisted-14.0.0/NEWS?format=raw).
