### ISSUE TITLE
Whisper / storage-schemas.conf changing retention times

### ISSUE THREAD

**Issue by rlueckl** [graphite-project/carbon#379]
Hi,

sorry if this is a noob question, but I did not find the answer in the official documents. I recently had to take over our teams monitoring systems and I'm not very experienced in Carbon/Whisper.

I understand, that if I want to change the retention times I have to "recreate" the *.wsp files, since they have a fixed size. But what happens if I "forget" to create new Whisper files?

Let's say I have this in my storage-schemas.conf:
```
[historical_data]
pattern = ^foo\.bar\.archive
retentions = 1d:2y
```

The Whisper files are created with a maxRetention of 2 years. Now, I change the config from 1d:2y to 1d:10y - what happens after 2 years? Do I have to change the files by hand? If yes, which tool would I need to use - whisper-resize or whisper-fill?

Thanks,
Roland

**Comment by rlueckl** [comment]
Okay, so I figured it out: there was no "automatic" resizing (which is understandable), but I also didn't see any errors or at least warnings in the logs, that the Whisper file retentions do NOT correspond to the retentions in the storage-schemas.conf. So basically I had data overwritten by Carbon.

After using whisper-resize.py everything is fine.

(IMHO there should be an error written to the log if the retention times in the config differ from the Whisper file.)

**Comment by gargnisha1605** [comment]
Hi I used the following command to change the retention policies of my existing metrics:
find ./ -type f -name '*.wsp' -exec whisper-resize {} 10s:6h ;

Before changing the retention policies:
find ./ -type f -name 'count.wsp' -exec whisper-info {} ;
maxRetention: 86400
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 17308

Archive 0
retention: 86400
secondsPerPoint: 60
points: 1440
size: 17280
offset: 28

After changing the retention policy from 60s:1d to 10s:6h, my file size has increased.
find ./ -type f -name 'count.wsp' -exec whisper-info {} ;
maxRetention: 21600
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 25948

Archive 0
retention: 21600
secondsPerPoint: 10
points: 2160
size: 25920
offset: 28

I have changed the retention policy to clear some space from graphite server, but wsp file size has increased after whisper-resize. Can any body guide my how to clean whisper data.

**Comment by deniszh** [comment]
Hi @gargnisha1605,
not sure why you naming that operation "cleaning". You're _increasing_ number of stored datapoints (60s:1d is 1440 points, 10s:6h - 2160).  Please see https://github.com/graphite-project/carbon/issues/622#issuecomment-276194113
