### ISSUE TITLE
Query on local_settings.py carbon-cache/carbon-relay log directory

### ISSUE THREAD

**Issue by wingZero21** [graphite-project/carbon#380]
Hi,

There is currently the log_dir parameter that can be added within the local_settings.py for allow for a custom log location for graphite web. 

Is there anyway to have a parameter that allows you to add a custom log directory for carbon cache/relay logs as well?

**Comment by steve-dave** [comment]
See https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example#L28

You can have a different log dir for each instance of carbon.

**Comment by wingZero21** [comment]
Hey, Yeah we just found this its adding the log_dir into the carbon.conf.

Cheers for the info!
