### ISSUE TITLE
Option to disable listening for any service

### ISSUE THREAD

**Issue by PaulMcMillan** [graphite-project/carbon#381]
It's great that we have `ENABLE_UDP_LISTENER` so that we can disable that listener if it isn't in use. However, I'm running a tightly locked down system, and want the ability to disable ANY listener (e.g. I'm not using the pickle listener, so I'd prefer it wasn't listening at all, even using the safe unpickler).

Can we get a similar config for the other listeners?

**Comment by mleinart** [comment]
It's not documented, but you should be able to disable any listener by
setting the port to 0

**Comment by jssjr** [comment]
https://github.com/graphite-project/carbon/blob/master/lib/carbon/service.py#L133

Sneaky.

**Comment by PaulMcMillan** [comment]
Thanks!
