### ISSUE TITLE
Databases are not created like storage schema dictates

### ISSUE THREAD

**Issue by widhalmt** [graphite-project/carbon#382]
Hi!

I installed Graphite at a customers of mine and the installation has a problem.

When start or end of the interval to show in a graph is outside the first interval of the storage schema, the graph is empty. This happens with Graphite-Web and Graphana (which uses Graphite-Web to fetch data from carbon)

In the log I see the possible reason for this problem.
This storage schema is:

```
 [carbon]
pattern = ^carbon\.
retentions = 60:90d

[icinga_internals]
pattern = ^icinga\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)
retentions = 5m:7d

[icinga_default]
pattern = ^icinga\.
retentions = 1m:2d,5m:10d,30m:90d,360m:4y
```

And the `creates.log` reads:

```
09/02/2015 12:37:39 :: new metric [metricname] matched schema icinga_default
09/02/2015 12:37:39 :: new metric [metricname] matched aggregation schema default
09/02/2015 12:37:39 :: creating database file [databasename] (archive=[(60, 2880), (300, 2880), (1800, 4320), (21600, 5840)] xff=None agg=None)
```

The 5m interval is not set to 10 days like the schema says, but 2 days exact like the 1m interval.

**Comment by steve-dave** [comment]
@widhalmt Actually the 5m archive is correct: 2880 points at 300s resolution = 10 days. Something else must be causing your problem. Have you tried using whisper-dump on a whisper file to see if it actually contains the archives and data you expect?

**Comment by eyesonlyone** [comment]
A whisper-dump shows, that no archive except the first one contains any data.

**Comment by steve-dave** [comment]
@eyesonlyone @widhalmt are you having the same issue or working together on the same installation?  Can you confirm which version you are running (master, 0.9.12, 0.9.x)?  I haven't seen this happen, but it does look like a bug.

**Comment by eyesonlyone** [comment]
Yes we are working together on the same Installation. The used versions are 
> python-carbon-0.9.12-3.el6.noarch
> graphite-web-0.9.12-5.el6.noarch
