### ISSUE TITLE
carbon-relay stuck in AlreadyCalledError

### ISSUE THREAD

**Issue by lambdafu** [graphite-project/carbon#383]
Hi,

I just updated my stack from an Oct 2013 version to current versions, and am getting a ton of AlreadyCalledError failures in carbon-relay.  Once it gets in these, it seems to be stuck (retrying every couple of seconds with the same problem), until it is restarted or dies because of other bugs (I was using the pypi 0.9.13 "release" and thus saw #364 also).

Somewhat at a loss how to get more information, as I don't know twisted or carbon internals, and it seems related to asynchronous operation.  Help! :)

My overall setup is a single carbon-cache (with pickle interface) and one carbon-relay for each protected namespace (customer, with line interface).  The relay's only job is whitelisting.

I am using the ubuntu latest (14.04) docker image with its twisted and other packages, and graphite from pypi (some of the dependencies are for mozilla's circus).

From the relay error log:
```
08/02/2015 19:20:47 :: [console] Starting factory CarbonClientFactory(127.0.0.1:2004:None)
08/02/2015 19:20:47 :: [clients] CarbonClientFactory(127.0.0.1:2004:None)::startedConnecting (127.0.0.1:2004)
08/02/2015 19:20:47 :: [clients] CarbonClientProtocol(127.0.0.1:2004:None)::connectionMade
08/02/2015 19:20:47 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 593, in doConnect
    self._connectDone()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 612, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 481, in makeConnection
    self.connectionMade()
  File "/usr/lib/python2.7/dist-packages/carbon/client.py", line 32, in connectionMade
    self.sendQueued()
  File "/usr/lib/python2.7/dist-packages/carbon/client.py", line 79, in sendQueued
    self.factory.queueHasSpace.callback(queueSize)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 483, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError: 

08/02/2015 19:20:47 :: [clients] CarbonClientProtocol(127.0.0.1:2004:None)::connectionLost 
08/02/2015 19:20:47 :: [console] <twisted.internet.tcp.Connector instance at 0x7f5154db1b48> will retry in 4 seconds
08/02/2015 19:20:47 :: [clients] CarbonClientFactory(127.0.0.1:2004:None)::clientConnectionLost (127.0.0.1:2004) 
08/02/2015 19:20:47 :: [console] Stopping factory CarbonClientFactory(127.0.0.1:2004:None)
```

From the Dockerfile:
```
FROM ubuntu
RUN apt-get update && apt-get install -y --no-install-recommends \
  openssh-client \
  python-pip \
  python-dev \
  python-psutil \
  python-tornado \
  python-zmq \
  python-iowait \
  python-gevent \
  python-yaml \
  python-crypto \
  python-setproctitle \
  python-argh \
  python-mako \
  python-markupsafe \
  python-anyjson \
  python-tornadio2 \
  python-waitress \
  python-cairo \
  python-django \
  python-simplejson \
  python-django-tagging \
  python-tz \
  python-pyparsing \
  python-twisted \
  python-txamqp \
  python-zope.interface
RUN pip install --install-option "--prefix=/usr" --install-option "--install-lib=/usr/lib/python2.7/dist-packages" whisper carbon graphite-web
```

Package versions:
```
python-pip	 1.5.4-1
python-dev	 2.7.5-5ubuntu3
python-psutil	 1.2.1-1ubuntu2
python-tornado	 3.1.1-1ubuntu2
python-zmq	 14.0.1-1build2
python-iowait	 0.1-1.1build1
python-gevent	 1.0-1ubuntu1
python-yaml	 3.10-4ubuntu0.1
python-crypto	 2.6.1-4build1
python-setproctitle	 1.0.1-1ubuntu1
python-argh	 0.24.1-1
python-mako	 0.9.1-1
python-markupsafe	 0.18-1build2
python-anyjson	 0.3.3-1build1
python-tornadio2	 0.0.4-1
python-waitress	 0.8.8-1ubuntu3
python-cairo	 1.8.8-1ubuntu5
python-django	 1.6.1-2ubuntu0.6
python-simplejson	 3.3.1-1ubuntu6
python-django-tagging	 1:0.3.1-3
python-tz	 2012c-1build1
python-pyparsing	 2.0.1+dfsg1-1build1
python-twisted	 13.2.0-1ubuntu1
python-txamqp	 0.6.1-0ubuntu2
python-zope.interface	 4.0.5-1ubuntu4
```

**Comment by clohtd** [comment]
Did you ever resolve this  I am also now experiencing this, without any recent updates.

**Comment by WonderBeat** [comment]
Any news? 
Carbon 0.9.13. Deployed with Chef 'graphite' cookbook. Same error

**Comment by nisc-acooper** [comment]
I can confirm I am seeing this after upgrading to 0.9.13-pre.  Running python 2.6 on centos 6.5.  The only fix is to restart the relay process.

**Comment by WonderBeat** [comment]
TY. Restart helped

**Comment by mleinart** [comment]
This is a bit jank of a fix, but I think this might do it:

diff --git a/lib/carbon/client.py b/lib/carbon/client.py
index f128378..0c325b6 100644
--- a/lib/carbon/client.py
+++ b/lib/carbon/client.py
@@ -76,7 +76,8 @@ class CarbonClientProtocol(Int32StringReceiver):
       queueSize = self.factory.queueSize
       if (self.factory.queueFull.called and
           queueSize < SEND_QUEUE_LOW_WATERMARK):
-        self.factory.queueHasSpace.callback(queueSize)
+        if not self.factory.queueHasSpace.called:
+          self.factory.queueHasSpace.callback(queueSize)

   def __str__(self):
     return 'CarbonClientProtocol(%s:%d:%s)' % (self.factory.destination)


I'm guessing this is a race that happens when the queue is full and several
destinations reconnect at the same time, all send points along, and all try
and signal that the queue's no longer full

**Comment by nisc-acooper** [comment]
@mleinart's fix appears to work well!  After applying, we did see consistent queue drops, so I suspect we were running into the queue filling and multiple destinations (in our case, a cluster of 2) all trying to signal.

**Comment by deniszh** [comment]
Cool! do we need to create proper PR to fix it then?

**Comment by nisc-acooper** [comment]
+1 for PR

**Comment by obfuscurity** [comment]
This has been applied to 0.9.x and master in #400 and #431, respectively.
