### ISSUE TITLE
whisper aggregation not working for older data points

### ISSUE THREAD

**Issue by dhirajforyou** [graphite-project/carbon#389]
Storage - scheme:

```
[default]
pattern = .*
retentions = 5m:15d,15m:1y,1h:10y,1d:100y
```

storage-aggregation : 

```
[all_sum]
pattern = .*
xFilesFactor = 0.1
aggregationMethod = sum
```

Now, I am feeding entries as :

```
echo "rec.test 25 $(date --date="-6 minute" +%s)" | nc localhost 2003
echo "rec.test 50 $(date --date="-3 minute" +%s)" | nc localhost 2003 
echo "rec.test 100 $(date +%s)" | nc localhost 2003
echo "rec.test 1 $(date --date="-1 year" +%s)" | nc localhost 2003 
echo "rec.test 4 $(date --date="-1 year minute" +%s)" | nc localhost 2003
echo "rec.test 6 $(date --date="-1 year -1 minute" +%s)" | nc localhost 2003
echo "rec.test 8 $(date --date="-1 year -2 minute" +%s)" | nc localhost 2003
```

On grafana graph, I am able to see the aggregation(sum value) for recent feeded values. But 1 year before values are not aggregated. In fact only one value(latest entry from window of 1 hour) 8 is shown instead of 4+6+8=18.

What can be missing in the configurations ?

**Comment by syepes** [comment]
Have you tried setting xFilesFactor = 0.0

**Comment by dhirajforyou** [comment]
@syepes , thanks for the input. But still the problem persists.

**Comment by dhirajforyou** [comment]
I have below versions of graphite & grafana : 
graphite  0.10.0 
grafana  1.9.1

**Comment by syepes** [comment]
@dhirajforyou Have you looked at the raw data using whisper-dump.py to see if its good?

**Comment by dhirajforyou** [comment]
@syepes ,  yes I do check the raw data .
 whisper-dump test.wsp | grep -vP "0,[\s]+0" 
Able to see Archive 0,1,2...  both info and data.

Hey, have you tried to insert data into whisper - with older timestamp values? 
I think this must be supported by carbon or whisper some other way, which I am not able to reach.

**Comment by dhirajforyou** [comment]
So, here are the entire things I am doing.

case.sh > 
#!/bin/bash
#can we insert old data??
#retentions = 5m:15d,30m:1y,1d:10y
sudo rm -rf /var/lib/graphite/whisper/local/testin.wsp 
echo "local.testin 10 `date  +%s`" >~/graphite_test/insert_old.txt
echo "local.testin 6 `date -d '360days ago 30min  ago' +%s`" >>~/graphite_test/insert_old.txt
echo "local.testin 7 `date -d '360days ago 26min ago' +%s`" >>~/graphite_test/insert_old.txt
echo "local.testin 9 `date -d '360days ago 25min ago' +%s`" >>~/graphite_test/insert_old.txt
echo "local.testin 11 `date -d '360days ago 19min ago' +%s`">>~/graphite_test/insert_old.txt
echo "local.testin 5 `date -d '360days ago 9min ago' +%s`" >>~/graphite_test/insert_old.txt
echo "local.testin 50 `date -d '360days ago 1min ago' +%s`">>~/graphite_test/insert_old.txt

cat ~/graphite_test/insert_old.txt | nc localhost 2003
sleep 2
whisper-dump /var/lib/graphite/whisper/local/testin.wsp | grep -vP "0,[\s]+0" > ~/graphite_test/can_we_insertold.dump

can_we_insertold.dump >
Meta data:
  aggregation method: sum
  max retention: 315360000
  xFilesFactor: 0

Archive 0 info:
  offset: 52
  seconds per point: 300
  points: 4320
  retention: 1296000
  size: 51840

Archive 1 info:
  offset: 51892
  seconds per point: 1800
  points: 17520
  retention: 31536000
  size: 210240

Archive 2 info:
  offset: 262132
  seconds per point: 86400
  points: 3650
  retention: 315360000
  size: 43800

Archive 0 data:
0: 1426150800,         10

Archive 1 data:
0: 1426150800,         10
239: 1395045000,          5
240: 1395046800,         50

Archive 2 data:
0: 1426118400,         10
3290: 1395014400,         55


Archive data 2 is correct considering Archive data 1 is correct. In Archive 1, I understand first entry 10. After that why 5? I think it is remembering the last entry only ? Please correct me if I am wrong. 
I am expecting the sum(as in aggregation conf).

**Comment by plambrechtsen** [comment]
I have the same issue as you, I am trying to load historical data via the aggregator. It's hourly statistical information from some network elements and I have 6 months of raw data. Loading in real-time data is fine, but anything older than 1 hour fails to import. Feeding the data via pickle directly to carbon works fine and gives me the values I am expecting. But if I wanted it aggregated then it looks like I need to re-process it beforehand.
The error I get in the console log is: exceptions.AttributeError: 'module' object has no attribute 'metricGenerated'

**Comment by dhirajforyou** [comment]
@plambrechtsen, 
console log error -exceptions.AttributeError: 'module' object has no attribute 'metricGenerated'
make sure you have a file named metricGenerated in some where in whisper files.

Make sure you have correct storage scheme (for 6 months data, one of the bucket should be > 6 months) and aggregation as sum.

**Comment by plambrechtsen** [comment]
@dhirajforyou I found the metricGenerated issue since I was using 9.x and as soon as I upgraded to master the problem went away. 

But I too have the same issue in regards to aggregation of legacy data outside the current time period specified in the aggregation-rules. My storage schema is "elements.name.app.val" and I wanted to aggregate to elements.ALL.app.val on an hourly basis. So my aggregation rule is:
elements.ALL.<app>.<val> (3600) = sum bng.*.<app>.<val>
It works fine for data returned during the period, but loading anything older is just ignored and passed to carbon cache.
It would be nice to be able to reprocess everything based on the aggregation rules starting at the oldest event and going through the whole database.

**Comment by gilessbrown** [comment]
I'm getting an exception in the aggregator console.log that seems similar to this issue.

Looking at the code here:
    https://github.com/graphite-project/carbon/blob/master/lib/carbon/aggregator/buffers.py#L67

It looks to me like there import at the bottom of the file should:
```
from carbon import state, events
```

And that line 67 should be:
```
events.metricGenerated(self.metric_path, datapoint)
```

I have hacked this live change onto a VM install and it seems to be aggregating happily now.

I also had a look at the tests and I suspect that the mocking is masking this problem from showing up.

**Comment by helmo** [comment]
Quoting from #751:
> The aggregator always uses the current time, delayed data is not supported.

I was also looking to import historic data into a new graphite instance, but it seems that for this it's better to bypass the aggregator.

My workaround:
- Use whisper-resize on the wsp file to have the most detailed precision level for the whole period you want to import
- import
- resize again to the desired precision levels, letting the aggregator do it's job.

**Comment by floringavrila** [comment]
Had the same problem but no access on the graphite/whisper because of prod environment ...
I choosed to aggregate the data externally and then sending it to the graphite data port.
Then I wrote this library https://github.com/floringavrila/graphite-feeder
