### ISSUE TITLE
Profiling carbon does not pass filename to twistd

### ISSUE THREAD

**Issue by ebpitts** [graphite-project/carbon#393]
According to the carbon daemons help output, you can enable profiling like so

> --profile=PROFILE     Record performance profile data to the given file

However, when I do this, I get a traceback like the following

```
Traceback (most recent call last):
  File "/usr/local/www/graphite/releases/current/graphite_python/bin/carbon-relay.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/usr/local/www/graphite/releases/current/graphite_python/lib/carbon/util.py", line 88, in run_twistd_plugin
    config.parseOptions(twistd_options)
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 614, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.7/dist-packages/twisted/python/usage.py", line 236, in parseOptions
    raise UsageError(str(e))
twisted.python.usage.UsageError: option --instance not recognized
```

that is from an instance of carbon-relay started like

`/usr/local/www/graphite/releases/current/graphite_python/bin/python /usr/local/www/graphite/releases/current/graphite_python/bin/carbon-relay.py --nodaemon --profile=/data/graphite/carbon.relay.stats start`

I can solve this problem by changing 

`twistd_options.append("--profile")`

to

`twistd_options.extend(["--profile", options.profile])`

in lib/carbon/util.py

**Comment by ebpitts** [comment]
Fixing the code to enable profiling hasn't proved very useful, since I get a [stack error](https://bugs.python.org/issue900092) when loading the profiler's output.

I tried switching twisted to use cprofile instead of hotshot with with

`twistd_options.extend(["--profile", options.profile, "--profiler", "cprofile", "--savestats"])`

but then the stats file wasn't written anymore, this may be a [twisted issue](http://twistedmatrix.com/pipermail/twisted-python/2010-August/022683.html).

Still, I thought I would open the issue so anyone else who ha this problem will find it when searching.

**Comment by tail** [comment]
I just ran into this issue myself.  I also added an explicit `--profiler` option.

@ebpitts - It looks like twistd saves the profile results on exit of the process.  I was able to get both hotshot and cProfile to output to `--profile` when I terminated the process.
