### ISSUE TITLE
can SIGHUP  reload config?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#412]
Hi guys . I have a on production running some carbon-writters running and I've changed de storage-aggregation.conf. I would like to reload config without stopping the proceses but nothing found in the main documentatio in

http://graphite.readthedocs.org/en/latest/carbon-daemons.html

I've found a merged PR related to support SIGHUP (https://github.com/graphite-project/carbon/pull/309) but the PR says:

```
"... catch and ignore HUP regardless of how carbon is launched...".
```
But after in the carbon.conf this info is done.

```
# Enable daily log rotation. If disabled, a kill -HUP can be used after a manual rotate
ENABLE_LOGROTATION = False
```

is SIGHUP ignored or not? could be used to reload the configuration files?

**Comment by gretel** [comment]
i'd be glad to have an answer. regards!

**Comment by bmhatfield** [comment]
AFAIK, Sighup is indeed ignored / not used.

That said, I would love to see a PR that enables SIGHUP to catch and reload configs - that seems like a great idea. I feel like something about Twisted might get in the way, so it might require some fiddling to make sure it actually works :-)

**Comment by mleinart** [comment]
storage-schemas and storage-aggregation configs are reloaded automatically
(minutely IIRC). No signal is necessary
