### ISSUE TITLE
posible memory leak in carbon caches?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#413]
I have 2 relays and 2 writters on 2 servers doing replication in this way. ( with master dec9dfed89ea19e756fd5a45ff6462874b03b904 release)

![image](https://cloud.githubusercontent.com/assets/5883405/7648118/2809b832-fadf-11e4-8a08-3bcd1594da79.png)

And after restart all I got this memory evolution. ( this graph represent carbon._._.memUsage metric)

![image](https://cloud.githubusercontent.com/assets/5883405/7648138/64ead06a-fadf-11e4-910c-1e6991367a68.png)

on the last 3 days nothing special happned on the servers ( no incidents ) and all seems to be fine, the 2 servers have the same numer of metrics received over time.

![image](https://cloud.githubusercontent.com/assets/5883405/7648247/eb641fba-fae0-11e4-9e59-9cc652efaf74.png)

And the only correlation whatched is correlation with increments on average update time in writters (carbon.agents.*.avgUpdateTime)

![image](https://cloud.githubusercontent.com/assets/5883405/7648216/7dd42454-fae0-11e4-9e33-a0c0eaeddba5.png)

There is any know but related to memory leaks?

**Comment by GoozeyX** [comment]
were you ever able to resolve the issue for this? I am seeing similar behaviour with my setup
