### ISSUE TITLE
Feature Request: filter metrics by  IP origin

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#415]
Hi .

It could be great if we can discard and log metrics received from unwanted origins something like.

```
ORIGIN_ALLOW=1.0.1.0/32,1.0.1.3/32,1.0.1.5/32, 1.1.1.0/24
ORIGIN_FILTER_LOG=/var/log/graphite/metrics_filtered.log
```

is There  any alternative to do that?

**Comment by drawks** [comment]
I don't think this should be implemented in carbon. Filtering on network origin is a solved problem with various other more appropriate tools i.e. ipf, iptables, etc

**Comment by SEJeff** [comment]
Yup, I'm going to have to agree with @drawks. We are a small team as it stands, and it would be better to focus on our core mission. This should be very achievable by blocking the incoming carbon ports via iptables rules. You can even have iptables log the offending source host.
