### ISSUE TITLE
Weirdness in carbon-aggregator's aggregateDatapointsSent graph

### ISSUE THREAD

**Issue by bigunyak** [graphite-project/carbon#416]
Hi,

I tried to ask this question graphite community at answers.launchpad.net/graphite but unfortunately didn't get any help. Maybe the actual developers would help me. :)

I'm trying to understand/explain the weirdness I see in carbon-aggregator's aggregateDatapointsSent graph. It looks like this:
![carbon-aggregator](http://i.imgur.com/36rst6W.jpg)
Even though the number of received points by carbon-aggregator stays approximately the same there are sudden ups and downs on the aggregateDatapointsSent graph.

My graphite configuration is the following: there are 4 backend servers reporting per host metrics to locally installed statsd servers which flush the aggregates every 10 sec to carbon-aggregator. The carbon-aggregator then aggregates the metrics from the backends and along with the original data (`FORWARD_ALL = True`) passes stats to carbon-relay which has two destinations: local carbon-cache and another remote graphite server.
My aggregated application metrics look good in the local graphite (0.9.13) but completely broken on the remote one (0.9.12), where they look like cheese.
![app metrics](http://i.imgur.com/vtmNgtN.jpg)

I was thinking about two things:
1. There are probably changes between the versions in the code of carbon-aggregator or/and carbon-cache which could explain normal graphs in the later version and broken ones in the earlier.
2. The `frequency` parameter in aggregation rules in the `aggregation-rules.conf` is 10 sec, this is equal to statsd flush intervals on the backends. Maybe this causes the problem described in #54 and the parameter should be set to a longer period of time?

I'd appreciate any help or ideas on where to look for answers.
Thanks,
Dmitry

**Comment by piotr1212** [comment]
I'm sorry that you didn't get a response. Since this issue is almost 4 years old I assume that you moved on so there is no need to investigate this. The code also changed a lot since then. I am going to close this, if you are still experiencing this problem, please reopen.
