### ISSUE TITLE
AMQP connection drops; does not reconnect

### ISSUE THREAD

**Issue by TJC** [graphite-project/carbon#42]
I've observed a problem with Carbon's AMQP support.
If there's a network break for a while, the connection to the message broker from Carbon will drop out. However Carbon does not seem to automatically reconnect. I had to stop and restart carbon to do so.

I recommend that you implement client/server heartbeating in the AMQP connection, as well as a reconnection handler.
The heartbeating will allow you to drop the connection if it has died but not dropped. If you fail heartbeats, you just disconnect.
The reconnection handler spots a lack of AMQP connection, and initiates reconnection.

**Comment by jcarizza** [comment]
Same problem here.

**Comment by mgrzybek** [comment]
You can use Logstash as a workaround between RabbitMQ and Carbon. It will reconnect on network failure.
