### ISSUE TITLE
Negative values on Cache Size statistics

### ISSUE THREAD

**Issue by sbengo** [graphite-project/carbon#420]
Hi, I am on carbon master branch version commit b80ce915a5e420b46e6972512801491e536db1b6 

The last day, I had seen that some of the writers have negative values on the metric cache size:
`carbon/agents/backend-wr*/cache/size.wsp`

![image](https://cloud.githubusercontent.com/assets/13196237/8741901/d46fe806-2c5f-11e5-9eef-5555866797a0.png)
Seems that the backend is working fine, but I am worried about those negative values.
Do you know why I am obtaining those negative values?

**Comment by deniszh** [comment]
I think it's connected with https://github.com/graphite-project/carbon/issues/371, I tried patch from  https://github.com/graphite-project/carbon/issues/371#issuecomment-118056194, maybe it helps with negative values too.

**Comment by LeonidVasilyev** [comment]
I'm experiencing same issue using 0.9.15 version, cache size is negative:
![image](https://cloud.githubusercontent.com/assets/1970951/13882826/217c7d82-ed38-11e5-9bff-6cfc56d0693c.png)

**Comment by Kenterfie** [comment]
I notice the same problem since month. After short time the cache size goes in negative range. I also use 0.9.15

![image](https://cloud.githubusercontent.com/assets/527694/16560111/8f3739a8-41f1-11e6-9d56-ba33b8099045.png)

**Comment by vinhlh** [comment]
+1

**Comment by obfuscurity** [comment]
Should be fixed by https://github.com/graphite-project/carbon/pull/551.
