### ISSUE TITLE
How can I disable carbon-aggregator console.log generation ?

### ISSUE THREAD

**Issue by zyy17** [graphite-project/carbon#423]
When I use carbon-aggregator, it will generate huge amount of console.log, such as:

``` shell
...
14/08/2015 10:42:22 :: abj-nogic-7.elogic_appkey_stat.puback_packet_count.5417dd2cee00dba45fb0d1dc.one
14/08/2015 10:42:22 :: abj-nogic-7.elogic_appkey_stat.unsuback_packet_count.5417dd2cee00dba45fb0d1dc.one
14/08/2015 10:42:22 :: abj-nogic-7.elogic_appkey_stat.subscribe_packet_count.5417dd2cee00dba45fb0d1dc.one
...
```

and this log will consume most of my disk space.

I cannot find the config in carbon.conf such as `ENABLE_LOGROTATION` in aggreator section.

**Comment by genuss** [comment]
I didn't find the solution for similar issue. Ended up with removing the line, which invokes log in source code.

**Comment by xneo64** [comment]
Same problem, I tried including LOG_UPDATES = False in the [aggregator] section but didn't work.
Ended up symlinking console.log to /dev/null.

**Comment by ChanningBJ** [comment]
Seems setting LOG_AGGREGATOR_MISSES = False should work in version 1.0.1
