### ISSUE TITLE
Multiple carbon-cache and CPUs

### ISSUE THREAD

**Issue by KaiPierre** [graphite-project/carbon#461]
I see in different posts that to enhance a graphite instance/cluster performance, we can launch multiples carbon-cache instances on a same host (and generally one per CPU). So I do that but it seem that only one CPU work. Global load of my host stay high and I can see that only one CPU have a large wait time (like when I have just one launched). 
How does the balance between carbon processes and CPUs are done ? Just simply launching X processes means they execute each on a different CPU all managed by the system (Docker container hosted on a Linux Ubuntu in my case) ? 
Does the docker layer can cause any conflict (inside container I can see all my processors) ?
Or does it need to specify the CPU used when launching each carbon-cache process ?

**Comment by obfuscurity** [comment]
You can run multiple `carbon-cache` instances and they should each bind to a different core. Without more details, e.g. your `carbon.conf` (minus any extraneous comments, please), we're not going to be able to provide much help. Are you sure that you're running multiple `carbon-cache`s?

**Comment by KaiPierre** [comment]
Ok, this is my config : 
```
[cache]
STORAGE_DIR    = /var/lib/graphite/
CONF_DIR       = /etc/carbon/
LOG_DIR        = /var/log/carbon/
PID_DIR        = /var/run/carbon
LOCAL_DATA_DIR = /var/lib/graphite/whisper/
ENABLE_LOGROTATION = True
USER = graphiteUser
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 500
MAX_UPDATES_PER_SECOND_ON_SHUTDOWN = 1000
MAX_CREATES_PER_MINUTE = 50
LINE_RECEIVER_INTERFACE = 127.0.0.1
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
CACHE_QUERY_INTERFACE = 127.0.0.1
ENABLE_UDP_LISTENER = False
LOG_LISTENER_CONNECTIONS = True
USE_INSECURE_UNPICKLER = False
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = True
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False
WHISPER_FALLOCATE_CREATE = True

[cache:0]
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7012
[cache:1]
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_PORT = 2024
CACHE_QUERY_PORT = 7022

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
LOG_LISTENER_CONNECTIONS = True
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2014,127.0.0.1:2024
MAX_DATAPOINTS_PER_MESSAGE = 500
MAX_QUEUE_SIZE = 10000
USE_FLOW_CONTROL = True
```
All are started by supervisord using 
```
/usr/bin/carbon-cache --debug --instance=XX start
````
and I can see 2 carbon-cache processes and a carbon-relay running.

I just see that with or without multiple carbon-cache just CPU1 (using graphite and collectd on my host) keep a wait amount between 80 and 100. I know that wait is linked to I/O disk operation (and writes on my volume are high) but I was thinking that balancing between two caches balance this wait on two CPUs.
I was trying this use case before eventually duplicate node to get a complete cluster.
I see also that relay don't balance half metrics on each cache but around 5k more on one cache than other (Using carbon-relay sent metrics).

**Comment by obfuscurity** [comment]
@KaiPierre I'm circling back around on some older issues and came across this one again. I'm not sure I understand if there's an actual question in your report. I can verify that you can absolutely run numerous carbon-cache and carbon-relay process in parallel on the same host.

I'm closing this issue for now but if you still need assistance, please elaborate and we'll do our best to assist you.
