### ISSUE TITLE
log to syslog not working after change to 0.9.14

### ISSUE THREAD

**Issue by dopey** [graphite-project/carbon#471]
In v0.9.13 I could give the --syslog option to carbon-cache.py and carbon-relay.py to send logs to syslog. Has this option been changed or reverted in 0.9.14?

I get:

 `carbon-relay.py: error: no such option: --syslog` -- and same for carbon-cache.py

**Comment by deniszh** [comment]
IIRC syslog was implemented in master and never backported to 0.9.x

**Comment by obfuscurity** [comment]
I'm looking into this today. Yes, syslog support via Twisted was added to master, but I suspect there was some native support that broke somewhere along the way.

**Comment by obfuscurity** [comment]
There was indeed syslog support added [way back when](https://github.com/graphite-project/carbon/commit/6a41bbdf2b20a9cabf56f5712693711cabc674a8) but there was no `--syslog` option. Still trying to figure out how this is/was typically enabled.

**Comment by obfuscurity** [comment]
@dopey I'm not able to reproduce your claim that pre-0.9.14 supported a `--syslog` option to Carbon. I've tested with 0.9.13-pre1 and 0.9.12 and they both return startup errors.

```
$ sudo /opt/graphite/bin/carbon-cache.py --syslog start
Usage: carbon-cache.py [options] <start|stop|status>

carbon-cache.py: error: no such option: --syslog
```

I have no qualms about backporting #323 to the 0.9.x branch; we may or may not issue a follow-up release for the handful of items fixed post-0.9.14. But I'd like to also understand how you might have been triggering @sidnei's aforementioned native support.

**Comment by deniszh** [comment]
I suspect that @dopey means running carbon as twisted plugin - e.g. like https://bitbucket.org/jerub/twisted-plugin-example - then you'll have ```--syslog``` option - but it's a twisted option, not carbon one. Unfortunately I have no idea how to run carbon as twisted plugin.

**Comment by dopey** [comment]
My upstart files for carbon-relay and carbon-cache respectively:

carbon-relay
```
#!/bin/sh

set -e

export GRAPHITE_CONF_DIR="/var/lib/graphite/conf"

exec su -c"/opt/graphite/bin/carbon-relay.py --syslog \"$1\"" -s"/bin/sh" "graphite"
```

carbon-cache
```
#!/bin/sh

set -e

export GRAPHITE_CONF_DIR="/var/lib/graphite/conf"
export GRAPHITE_STORAGE_DIR="/var/lib/graphite/storage"

exec su -c"/opt/graphite/bin/carbon-cache.py --syslog --pidfile \"/var/run/graphite/carbon-cache-a.pid\" --instance \"a\" \"$1\"" -s"/bin/sh" "graphite"
```

ubuntu 12.04 precise
graphite-web sha: aa37f1bd3f3d2478b3d84ff20bd309db3ec30a02
carbon sha: 142f5493972db05c5c63ef7691ff71a8aeb128a4
whisper (dont have the sha but around the 0.9.13 release)

With the above, the `--syslog` option worked. Logs for twisted, carbon-cache, and the carbon-relay all appeared in syslog.

Switching to the 0.9.14 tag, and upgrading django to 1.4.5 (from 1.3.x), causes the `unrecognized option` error from above.

Let me know if there is any more information I could provide that might be useful.

**Comment by obfuscurity** [comment]
How did you install?

**Comment by dopey** [comment]
heh, in a non-standard way. I built my own debs using fpm.

graphite-web: https://github.com/dopey/graphite-web-build/blob/master/bootstrap.sh
carbon: https://github.com/dopey/carbon-build/blob/master/bootstrap.sh
whisper: https://github.com/dopey/whisper-build/blob/master/bootstrap.sh

**Comment by obfuscurity** [comment]
Unfortunately, I simply can't reproduce. I've tried with both 0.9.12 and 0.9.13-pre1 and I get the same `no such option: --syslog` error with both. I'm a little suspicious of your actual versions since there was no official `0.9.13` tag.

**Comment by obfuscurity** [comment]
I strongly suspect that you were running master and not "0.9.13", since that tag never existed. Regardless, I've backported `--syslog` support from master to 0.9.x. You're welcome to run from HEAD of this branch or you can wait in the off-chance that we cut a 0.9.15 release.

**Comment by dopey** [comment]
Oh, sorry. Didn't fully grasp what you meant before, but that's definitely what I was doing. The SHAS that I pasted above were the just the most recent commits on master at the time that I made the package (since 0.9.13 didnt' have a tag). Thanks for backporting, I will have a look at it later today :)
