### ISSUE TITLE
LOG_CACHE_QUEUE_SORTS documentation

### ISSUE THREAD

**Issue by skstronghold** [graphite-project/carbon#478]
There is no documentation for `LOG_CACHE_QUEUE_SORTS` in example config file.

Adding a commented line to `carbon.conf.example` will increase discovery of this feature.

**Comment by obfuscurity** [comment]
There's no point adding it to the example config for 0.9.x since we're in maintenance mode there. I've added the setting to master in #480 and included it in the sample config.
