### ISSUE TITLE
AMQP multiple receivers (not exclusive Queue)

### ISSUE THREAD

**Issue by biancalana** [graphite-project/carbon#481]
The actual carbon configuration only allow the user to specify the exchange used to bind a private queue created by carbon on startup and this queue is deleted when you stop the carbon process. So the metrics on those queue are lost.

Attempting to improve our metrics availability, handle better maintenance window and metric traffic spikes without loosing metrics, we have setup all our collectors to send metrics to graphite through AMQP, and did a small patch that allow user to define a queue_name on carbon.conf. That way we don't loose metrics on startup and also could have multiple receivers on the same queue.

I have did that because I didn't found any better way to achieve my goals, would this patch be valuable to the project ?

**Comment by deniszh** [comment]
I found that almost nobody using carbon with AMQP - maybe because that
issue even (or lack of documentation).
So, IMO, if you find some time to make an PR - it will be great!

**Comment by biancalana** [comment]
Which branch should I use as base 0.9.x ?

**Comment by deniszh** [comment]
Nah, 0.9.x is in maintenance mode, we have no plans to add new features
there. Please use master.

**Comment by mgrzybek** [comment]
I do use AMQP in front of my graphite aggregators. It is very convenient to have a buffer in case of maintenance or problem on the back-office servers.

Using several queues would allow users to have separated data sources: one per DMZ for example.
