### ISSUE TITLE
Twisted 15.5 no longer supports Python 2.6

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/carbon#482]
Although the Twisted [15.5 changelog](https://twistedmatrix.com/trac/changeset/46361) claims to support Python 2.6, builds are [now failing](https://travis-ci.org/graphite-project/carbon/jobs/93936324) because of it. Verified that Twisted 15.5 does in fact [break Python 2.6 compatibility](https://twistedmatrix.com/trac/browser/tags/releases/twisted-15.5.0/twisted/__init__.py#L16) (and further confirmed [here](https://twitter.com/hawkieowl/status/671365064864108544)).

Should we deprecate Python 2.6 support for the next (1.0?) master release, or lock in at Twisted 15.4 for the time being?

Refs #480 which is blocked on the broken 2.6 build.

**Comment by deniszh** [comment]
Depends on current state of support of Python 2.6 in distros. Do we have
Python 2.6 as default still in 2016?

**Comment by mleinart** [comment]
FWIW I'm in favor of dropping 2.6 support. AFAICT the only reason to continue to support it would be for RHEL/Centos 5 (EPEL only supports up to 2.6). However, 2.6 is a language runtime that was EOL'd two years ago on a nearly 9 year old distro.

Both Twisted and Django now support Python 3 and dropping 2.6 support is prerequisite to beginning the move to support 3 (keeping 2.6 support along with 3.x looks to be pretty messy).

**Comment by SEJeff** [comment]
You can get get Python 2.7 or even 3 in rhel / centos 6 easily via software collections. RHEL7 / Debian Jessie have much newer Python with 2.7.x as a baseline.

I'd also be in favor of dropping all versions of Django that aren't supported anymore.

**Comment by obfuscurity** [comment]
Removed python2.6 from all test configurations. There are some additional steps we can take to check versions, but this was just a quick run-through to unblock any future PR builds.
