### ISSUE TITLE
carbon-relay and high CPU Usage

### ISSUE THREAD

**Issue by willhughes** [graphite-project/carbon#495]
I have a carbon-relay relaying to 8 local carbon-caches using the aggregated-consistent-hashing method. ([This is the config I'm using](https://github.com/willhughes/docker-graphite-statsd/blob/deployed/conf/graphite/carbon.conf)). 

I'm not using any aggregations (yet) - but perhaps in the future. 

I'm sending about 5-8K metrics/second, and this is causing carbon-relay to sit at/near 100% CPU according to the carbon.relays.*.cpuUsage metric. 

First of all, is it sitting at (or near to) 100% going to cause problems if I try to send more metrics? 

If so, what are my options to improve performance? 

Can I reduce CPU usage by changing some options?

Alternatively, can I run multiple carbon-relay instances, and use tcp load balancing between them?

**Comment by deniszh** [comment]
>Alternatively, can I run multiple carbon-relay instances, and use TCP load balancing between them?

That's a good way. The carbon-relay is notoriously CPU-bound daemon.
Another good way - use [carbon-c-relay](https://github.com/grobian/carbon-c-relay) (if you happy with its aggregation capabilities, which is not worse than original btw).

**Comment by willhughes** [comment]
OK, great, thanks.
