### ISSUE TITLE
carbon-cache  strange behaviour: Mb reads from disk  greater than Mb writes (without graphite-web render hits)

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#497]
Hi @mleinart , @SEJeff 

I'he been working in a big performance issue when working with graphite.

* graphite-web ( https://github.com/graphite-project/graphite-web/tree/8710ff76f0b4571481d295d997a83e4c895dd092 )
* carbon ( b80ce915a5e420b46e6972512801491e536db1b6 )
* whisper (https://github.com/graphite-project/whisper/tree/1e96c0cd1dc0b361177c585033cfbbb5711a191f)

As you can see there is much more load from reads than  load from writes over the metric dedicated disks (even with only 10 hits in the graphite , in the meanwhile carbon-caches are storing 170K metrics/minute )

![image](https://cloud.githubusercontent.com/assets/5883405/11741616/68c093a8-9ffa-11e5-8418-f097aa4eb3fa.png)

![image](https://cloud.githubusercontent.com/assets/5883405/11741765/53b9f52a-9ffb-11e5-86b3-fb8aea8a123c.png)

You can see each Read/Write with iotop ( now at 12:00 aprox)
````
Total DISK READ: 90.27 M/s | Total DISK WRITE: 0.00 B/s
  PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 2322 be/4 carbon     13.61 M/s    3.42 M/s  0.00 % 40.25 % python bin/carbon-cache.py --instance=wr07c start
 2302 be/4 carbon     14.46 M/s    4.03 M/s  0.00 % 38.97 % python bin/carbon-cache.py --instance=wr07a start
 2312 be/4 carbon     14.79 M/s    4.03 M/s  0.00 % 38.65 % python bin/carbon-cache.py --instance=wr07b start
 2352 be/4 carbon     15.95 M/s    3.62 M/s  0.00 % 37.89 % python bin/carbon-cache.py --instance=wr07d start
61286 be/4 carbon     15.05 M/s    4.17 M/s  0.00 % 37.53 % python bin/carbon-cache.py --instance=wr07f start
61276 be/4 carbon     16.62 M/s    3.66 M/s  0.00 % 37.49 % python bin/carbon-cache.py --instance=wr07e start
```

These estrange reads  over disk are impacting on the CPU  ( you could see less io wait when Reads decrease)

![image](https://cloud.githubusercontent.com/assets/5883405/11741938/70ac4baa-9ffc-11e5-84ca-8e7436459561.png)

There is any reason in the carbon/whisper logic that could explain this behavior on the I/O load ?

Thank you very much !

**Comment by bmhatfield** [comment]
Every write to a whisper file requires multiple reads. I have solved this problem (and a few other graphite performance problems) by making sure I have plenty of memory available to linux disk caching, 20-30GB or so for a box handling 1TB of metrics.

I also turn off entirely Graphite's django/web-side caching, as that eats memory for multiple copies of the same (soon to be expired) object, instead preferring to let linux disk caching handle that too.

The result is that I see extremely low reads, and as a result of the reduced contention I gain improved write throughput, which seems to reduce the points in carbon-cache, which gives even more memory back for improved throughput.

Here's an example graph of the improved ratio simply by having plenty of repeat-reads in cache:

<img width="782" alt="screen shot 2015-12-11 at 9 32 26 am" src="https://cloud.githubusercontent.com/assets/1119967/11746089/30713ff8-9fea-11e5-8c35-5ac086d1843c.png">

**Comment by mleinart** [comment]
Note also that writes to whisper files with many retentions are much more
read intensive due to the way aggregation works (the aggregated points are
written to *every* write, requiring a read of all points in the highest
precision that cover the aggregated period). bhatfield's suggestion applies
well in any case

**Comment by toni-moreno** [comment]
Hi @bmhatfield @mleinart , Thank you for the reply, I'm working in a virtualized environtment, so there is no way to get SSD's disk.

I will try today to disable memcached and force more cached memory with vm.dirty_ratio , If not enough, I will ask for more memory  and restart the server.

**Comment by toni-moreno** [comment]
Hi  @mleinart and @bmhatfield , after 2 Gb RAM the io have decreased and io-wait in now very low.

![image](https://cloud.githubusercontent.com/assets/5883405/11817681/507ef320-a356-11e5-9f54-537ad35a1566.png)

Thanks a lot for your help!!

**Comment by gideon-maina** [comment]
@bmhatfield You have said that you "I also turn off entirely Graphite's django/web-side caching, as that eats memory for multiple copies of the same (soon to be expired) object, instead preferring to let linux disk caching handle that too." I would like to know how you have done that for your set up. 

Is it something to do with DEFAULT_CACHE_DURATION and DEFAULT_CACHE_POLICY with graphite web's local_settings.py ?
