### ISSUE TITLE
Centralized graphite-web

### ISSUE THREAD

**Issue by vasiliyb** [graphite-project/carbon#498]
Folks,
  I have 2 clusters, each in its own geographic location (aws regions east and west).  Each has a working carbon_relay/carbon_cache stack, and a _graphite_web_ instance that connects to back-end carbon_caches and is able to graph in-region metrics. Lets call them _graphite_region_aggregators_ in the example.

  The piece that is not working, is a central _graphite_web_ instance that connects to both region's _graphite_region_aggregators_.  No metrics are being shown on the front-end.
  I can see (via tcpdump) successful connection attempts to the in-region graphite servers on port 80 when I search for metrics

  Is specifying `CLUSTER_SERVERS = ["us_west_graphiteweb:80", "us_east_graphiteweb:80"]` enough, or is there some other magical configuration I've missed?

**Comment by vasiliyb** [comment]
Folks, to my understanding, you can not cluster graphite_web in such fashion.  At the moment, you can not have the following:


```
'graphite_web_head' connects to:
                     ['graphite_web_us_east1', 'graphite_web_us_west2']
                                  which in turn connect to in-region graphite_web/carbon_relay/carbon_cache stacks
```

So it is not possible to have more complex stacks of graphite_web proxies?

**Comment by deniszh** [comment]
Hello @vasiliyb,

Our graphite cluster configured exactly like that - we have a bunch of "frontend" servers ( "render farm" ) which is connected to "backend" servers (one per DC). Frontends have no data, all data is stored on backends.
And for configuring such setup you need to only add servers to CLUSTER_SERVERS, as you did. So, we need to dig more. Ang Github issues is not a better place for that. 
Could you please open question on project Launchpad https://answers.launchpad.net/graphite instead and add more info? 
Let's continue there.
