### ISSUE TITLE
gracefully shutdown of carbon daemon

### ISSUE THREAD

**Issue by andyxning** [graphite-project/carbon#501]
I think carbon-relay and carbon-cache both have some cache in the memory. So, i think we should have a graceful shutdown just like what Nginx do.

**Comment by obfuscurity** [comment]
Carbon **does** attempt to flush metrics to disk before shutting down, as long as you don't try to `kill -9` it.

**Comment by andyxning** [comment]
what about cabron-relay? I remember in version 0.9.12 there is no work to do when we just shutdown the carbon-relay. However, we have a cache in the middle of data flow in carbon-relay. If i am wrong, please tell me. :)

**Comment by obfuscurity** [comment]
I'm not against some type of solution like this, but I don't expect to see anyone working on this actively. If you'd like to submit a PR or propose some sort of paid bounty, perhaps you'll find someone interested. But this is not a simple feature, nor is it one that users have clamored for.

**Comment by andyxning** [comment]
Ok, i got it.




===
Ning Xie
Email: andy.xning@gmail.com


原始邮件
发件人:Jason Dixonnotifications@github.com
收件人:graphite-project/carboncarbon@noreply.github.com
抄送:Ning Xieandy.xning@gmail.com
发送时间:2015年12月16日(周三) 10:55
主题:Re: [carbon] gracefully shutdown of carbon daemon (#501)


I'm not against some type of solution like this, but I don't expect to see anyone working on this actively. If you'd like to submit a PR or propose some sort of paid bounty, perhaps you'll find someone interested. But this is not a simple feature, nor is it one that users have clamored for.

**Comment by mleinart** [comment]
FYI I took a look at this as I thought carbon-relay flushed queues at shutdown. Turns out that was all coded up but a little mistake caused shutdown to happen without waiting for a queue flush to complete.

Fixed in #503

**Comment by andyxning** [comment]
Ok，i will have a look at it later. :)




===
Ning Xie
Email: andy.xning@gmail.com


原始邮件
发件人:Michael Leinartasnotifications@github.com
收件人:graphite-project/carboncarbon@noreply.github.com
抄送:Ning Xieandy.xning@gmail.com
发送时间:2015年12月17日(周四) 13:47
主题:Re: [carbon] gracefully shutdown of carbon daemon (#501)


FYI I took a look at this as I thought carbon-relay flushed queues at shutdown. Turns out that was all coded up but a little mistake caused shutdown to happen without waiting for a queue flush to complete.
Fixed in #503
