### ISSUE TITLE
Enable on/off configuration for appending dates to log files

### ISSUE THREAD

**Issue by rowanu** [graphite-project/carbon#51]
As mentioned by @mleinart in https://answers.launchpad.net/graphite/+question/198157.

Carbon currently uses twisted.python.logfile.DailyLogFile to write logs to file, so log files end up looking something like:

```
console.log
console.log.2012_12_18
console.log.2012_12_19
```

This date extension means that it doesn't play nicely with things like `logrotate`, which is annoying.

I would propose a configuration option (in `daemon.conf`?) to enable turning this off. The default can be to continue using DailyLogFile, and the alternative to log to the same filename, so that services like `logrotate` can do their thing.

Let me know if that sounds reasonable, and I will send a pull request.

**Comment by piotr1212** [comment]
This was implemented in https://github.com/graphite-project/carbon/pull/68
