### ISSUE TITLE
Erroneous aggregation with nulls.

### ISSUE THREAD

**Issue by magmax** [graphite-project/carbon#511]
Hello.

I have an aggegation over a measure with a lot of nulls. Let's say I have a point each 5 minutes while whisper stores each minute.

When I configure the aggregation method "max" or "latest", it always returns null, so I'm losing all the stores.

I'm not sure if I'm doing something wrong, but IMHO, "max" should just consider the not-null values, so I should not lose any value.

Thank you in advance.

Configuration:
```
[example]
pattern = metrics.example
xFilesFactor = 0.5
aggregationMethod = max
```

**Comment by eyesonlyone** [comment]
I think i have a similiar problem. Carbon Cache is configured with saving points every minute for 7 days. But most most of our metrics come in a 5min interval. And that works fine for the period of 7 daysl. I can see the graph in graphite-web without the "null" points.

But as soon as it gets to the second timeperiod the graph is empty.

This is my storage scheme:

[icinga_default]
pattern = ^icinga2\.
retentions = 1m:5d,5m:14d,10m:90d,30m:180d,60m:1y,360m:4y

bizarrely we also have metrics that come only once an hour but they are correctly aggregated without the nulls in higher timeperiods.

graphite-carbon version is 0.9.12-3
python-whisper version is 0.9.12-1

**Comment by obfuscurity** [comment]
I suspect you're not familiar with how the `xFilesFactor` attribute works. See the following documentation.

http://obfuscurity.com/2012/04/Unhelpful-Graphite-Tip-9
http://graphite.readthedocs.org/en/latest/config-carbon.html?highlight=xfilesfactor#storage-aggregation-conf

If this addresses your question, please go ahead and close this issue. If you still think you're seeing a bug please let me know and we'll look into it further.

**Comment by magmax** [comment]
So by setting xFilesFactor to 0.0 should fit the bill. I will try, and if it works, I will close this issue.

Thank you very much.

**Comment by magmax** [comment]
Checked and working.

Thank you very much!
