### ISSUE TITLE
Carbon cache: no module named carbon.util

### ISSUE THREAD

**Issue by amdei** [graphite-project/carbon#514]
Exactly the same issue as #276 .
Debian 8 x64, installed 
carbon-0.9.15 
graphite-web-0.9.15 
to default locations using pip.

When I trying to run:
python /usr/local/bin/carbon-cache.py start

I got:
Traceback (most recent call last):
  File "/usr/local/bin/carbon-cache.py", line 28, in <module>
    from carbon.util import run_twistd_plugin
ImportError: No module named carbon.util

**Comment by skolsuper** [comment]
+1

I have installed into a virtualenv at `/opt/graphite/venv`, after activating with `source /opt/graphite/venv/bin/activate` in the python shell I can `import whisper` no problem, but `import carbon` throws an ImportError

**Comment by skolsuper** [comment]
`import twisted` and `import zope` also work.

**Comment by skolsuper** [comment]
I changed the virtualenv to the installation folder as [recommended in the docs](http://graphite.readthedocs.org/en/latest/install-virtualenv.html#installing-in-the-default-location).  This is the output I get below when trying to import carbon, hopefully it will help diagnose the problem.  Box is a fresh install of ubuntu14.04 with python 2.7

```
vagrant@carbon:~$ cd /opt/graphite/
vagrant@carbon:/opt/graphite$ source bin/activate
(graphite)vagrant@carbon:/opt/graphite$ pip freeze
carbon==0.9.15
graphite-web==0.9.15
Twisted==15.5.0
txAMQP==0.6.2
wheel==0.24.0
whisper==0.9.15
zope.interface==4.1.3
(graphite)vagrant@carbon:/opt/graphite$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import carbon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named carbon
```

**Comment by asurak** [comment]
Exactly the same issue here. I rollbacked to 0.9.12 from Ubuntu 14.04 repo and had to manually remove `twisted` from `pip`, otherwise even 0.9.12 did not work.

**Comment by asurak** [comment]
My colleague tried to make a container for 0.9.15 and locked the version of `twisted` to 11.1.0 and then it worked well. Here is the [container](https://github.com/ElPicador/docker-graphite-statsd/blob/master/Dockerfile).

**Comment by damm** [comment]
This is a mess; I found the util stuck in `/opt/graphite/lib/python/site-packages/opt/graphite/lib/`

There's also some twisted plugins in there as well.

**Comment by cahlbin** [comment]
+1

Using virtualenv seems to be the problem. I'm seeing the carbon.util module ending up in `/opt/graphite/lib/python2.7/site-packages/opt/graphite/lib.`

Not using virtual env works fine as then the util module ends up in `/opt/graphite/lib/carbon/util.py` (as expected by `carbon-cache.py`, in terms of relative path to itself at least)

(CentOS 7)

**Comment by mleinart** [comment]
Looks like this is graphite's default prefix (/opt/graphite) screwing things up again. Unsure what changed to break this - perhaps it never worked in the first place.
You should be able to pass in --install-lib to point to the virtualenv's site-packages dir as in the 'custom install' section of the docs:
http://graphite.readthedocs.org/en/latest/install-pip.html?highlight=pip#installing-carbon-in-a-custom-location

Unfortunately there doesn't appear to be a reliable way to get this directory programmatically on the commandline (see http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory) though if you're installing with a virtual env at /opt/graphite/ this should work:
    source /opt/graphite/bin/activate
    pip install carbon --install-option="install-lib=/opt/graphite/lib"

**Comment by damm** [comment]
@cahlbin I'm not sure that `/opt/graphite/lib/carbon/util.py` is the right location without virtualenv

carbon should be installed into the python site-packages? that's what seems right to me.  I suspect it would fail either way

This was introduced in https://github.com/graphite-project/carbon/issues/219

**Comment by deniszh** [comment]
@cahlbin is right, by default it's installing in /opt/graphite and not in python site-packages

**Comment by damm** [comment]
right and it should be installed into the site-packages; regardless of virtualenv or not.

As virtualenv is just an isolated python install? (i guess that's a good phrase) it has roughly the same directory layout as the distro's install.

**Comment by qiangyao** [comment]
> damm commented on 27 Feb
This is a mess; I found the util stuck in /opt/graphite/lib/python/site-packages/opt/graphite/lib/
There's also some twisted plugins in there as well.

mv  /opt/graphite/lib/python/site-packages/opt/graphite/lib/carbon   /opt/graphite/lib/python/site-packages/
mv  /opt/graphite/lib/python/site-packages/opt/graphite/lib/twisted/plugins/carbon_*  /opt/graphite/lib/python/site-packages/twisted/plugins/carbon_*

**Comment by damm** [comment]
exactly @qiangyao

**Comment by marcusdb** [comment]
`cp -rv /usr/local/lib/python2.7/dist-packages/opt/graphite/lib/carbon /usr/local/bin/ && cp -rv /usr/local/lib/python2.7/dist-packages/opt/graphite/lib/twisted /usr/local/bin/`

This fixed the issue for me
ubuntu 16 // python 2.7 // Twisted (11.1.0) // carbon (0.9.15)

**Comment by 7heo** [comment]
qiangyao commented on Sep 19, 2016
>
> damm commented on 27 Feb
>> This is a mess; I found the util stuck in /opt/graphite/lib/python/site-packages/opt/graphite/lib/
>> There's also some twisted plugins in there as well.
>
> mv /opt/graphite/lib/python/site-packages/opt/graphite/lib/carbon /opt/graphite/lib/python/site-packages/
> mv /opt/graphite/lib/python/site-packages/opt/graphite/lib/twisted/plugins/carbon_* /opt/graphite/lib/python/site-packages/twisted/plugins/carbon_*

That will work for installations located in `/opt/graphite`. For **virtualenv** installations, `cd` to your virtualenv and run:

    $ mv lib/python2.7/site-packages/opt/graphite/lib/carbon lib/python2.7/site-packages/
    $ mv lib/python2.7/site-packages/opt/graphite/lib/twisted/plugins/* lib/python2.7/site-packages/twisted/plugins/
    $ rmdir -p lib/python2.7/site-packages/opt/graphite/lib/twisted/plugins/

And carbon will work.
