### ISSUE TITLE
Carbon metrics  shows errors but no error in carbon logs.  What is the meaning of this metric?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#519]
Hi guys.

I 'm seeing errors in the carbon metric, but not error appears in the logs

![image](https://cloud.githubusercontent.com/assets/5883405/12510969/11de30e2-c10e-11e5-9cc6-75d327a8b26f.png)

What exactly means "error" in the carbon context ? Where can I query which error is reporting carbon ?
Thank you very much.

**Comment by reynir** [comment]
Check /opt/graphite/storage/log/carbon-cache/..., there should be log files there, hopefully with useful information about the errors.

**Comment by toni-moreno** [comment]
Hi @reynir there is not any error log message in these log files.

**Comment by toni-moreno** [comment]
Hi @reynir , I realize today that we had a truncate file in a rotation log for console.log and probably we hide the error message on these carbon agents.
I will close this issue until we can reproduce the error.
