### ISSUE TITLE
Archiving old data

### ISSUE THREAD

**Issue by joeg1484** [graphite-project/carbon#522]
Hi,

I have a ton of old sar data that I want to put into Graphite so we can graph it to get historical information on systems.

When I say old, I mean from back in 2013 and up. I have created a script that will convert the date and time stamps to the system time (I call it epoch time) and then format the data to put it into the database.

At first, I was only getting back 2 data points for one days worth of data. Then, I realized that I had to change the retention values to specify older than 5 years for 10 min (Sar default). 

This works GREAT, other than each month of sar data consumed ~300 megs of data. So, if I have a whole year, thats ~300*12 = 3.6 gigs. I have over 100 systems that I need to import.

Is there a better way of doing this? Can I somehow use a smaller value like 10:30d in retention and manipulate some other settings to have that work.

When I try this, I only end up with an empty data file. If I do something like: 
retentions = 10m:60d,30m:90d,60m:120d,120m:5y

Then I only get like 2 or 3 data points for the day, so it looks like a big inverse V.

If the only way is to use 10:5y, then so be it, but I just wanted to see if there was some other way to minimize the size of the data files.

Thanks!
Joe

**Comment by jds86930** [comment]
I haven't tried this, but with a use-case like yours, I'd probably look into using Btrfs for a filesystem with zlib compression. Graphite's whisper files compress really well.

**Comment by obfuscurity** [comment]
Aside from filesystem-level compression, the only alternative would be to use `WHISPER_SPARSE_CREATE` in your carbon.conf.

**Comment by mleinart** [comment]
Graphite will read gripped whisper files (.wsp.gz) seamlessly. If the files
aren't being updated you should be able to just gzip them in place
