### ISSUE TITLE
Carbon-Cache not recognizing storage-schemas.conf

### ISSUE THREAD

**Issue by ghost** [graphite-project/carbon#524]
Hi,

I´m using Graphite together with icinga2. When i try to select a time interval of 1 month or 1 year in icingaweb2 i keep getting the 1 week view. The X-axis stays the same. All the other intervals like 10minutes and 1 hour work perfectly.

Also i tried to restart carbon-cache a few times but the value.wsp of a hostalive check still looks like this. I also deleted the whole /var/lib/graphite/icinga2 folder before restarting carbon-cache

```
maxRetention: 604800
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 120988

Archive 0
retention: 604800
secondsPerPoint: 60
points: 10080
size: 120960
offset: 28
```
Maybe those are two different problems.
My storage-schemas.conf looks like this:

```
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[icinga_default]
pattern = ^icinga\.
retentions = 5m:10d,30m:90d,360m:4y
xFilesFactor = 0

[icinga_internals]
pattern = ^icinga\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)  
retentions = 5m:7d,30m:90d,360m:4y
xFilesFactor = 0
```

**Comment by deniszh** [comment]
Sorry, have no Icinga2+Graphite experience. What's located in /var/lib/graphite/icinga2 ?
wsp files?

**Comment by obfuscurity** [comment]
Closing this out due to non-response.

**Comment by bob454522** [comment]
Im seeing the same issue here,  no matter what i put for retentions in storage-schemas.conf  whisper-info still shows the first point (my first entry in ss.conf is 10:3h  which should be 10seconds per point for 3hours retention)  i do know ss.conf is being read, as if i put something in it to cause a syntax error, i will get an error on service carbon restart  :

Archive 1
retention: 43200
secondsPerPoint: 60
points: 720
size: 8640
offset: 13108

**Comment by deniszh** [comment]
@bob454522 : changes will be applied only for new files. If you need to change existing files you need to migrate them with [whisper-resize.py](https://github.com/graphite-project/whisper/blob/master/bin/whisper-resize.py) or [whisper-auto-resize.py](https://github.com/graphite-project/whisper/blob/master/contrib/whisper-auto-resize.py)
