### ISSUE TITLE
Carbon-relay queue flushes blocks the event loop

### ISSUE THREAD

**Issue by mleinart** [graphite-project/carbon#53]
Carbon-relay's queue flush is done in a blocking manner and blocks the event loop. On a busy system with multiple destinations, a temporary disconnection of a destination blocks things long enough to cause a backup in requests that carbon-relay never recovers from

**Comment by obfuscurity** [comment]
Closing due to non-response.

**Comment by pcn** [comment]
Yeah, I'm not there anymore and I can't test it anymore, and I think its obviated now.
