### ISSUE TITLE
No directory /opt/graphite/storage 

### ISSUE THREAD

**Issue by kskaran94** [graphite-project/carbon#530]
i want to delete data from graphite , all the online solutions suggest go this directory and delete from here. But i can't find this directory

**Comment by JeanFred** [comment]
How did you install Graphite ? Debian package, pip,…?

**Comment by kskaran94** [comment]
[Check this ](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server)

**Comment by JeanFred** [comment]
Check `/var/lib/graphite/whisper` ?

**Comment by kskaran94** [comment]
Can i delete time based data from here ?

**Comment by JeanFred** [comment]
Er, yeah, sure. If you browse around in your `whisper` directory (which for me is in `/opt/graphite/storage/whisper`) you should find the Whisper files which hold your time series. Deleting the file = deleting the data.

**Comment by kskaran94** [comment]
As in if i delete the file , whole data is gone. What can i do if want to keep last week's data and delete rest?

**Comment by deniszh** [comment]
It have not much sense, whisper files have fixed size.
