### ISSUE TITLE
which is the exact meaning for  "cache.queue/cache.size" metrics?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbon#532]
Hi guys.

After working some months with graphite I notice I don't know which is the exact meaning of the carbon.agents.*.cache.queues metric.

For me seems to be the number of metrics which have pending points to write to disk / minute , in this case the it will be always less than the total  number of input metrics /minute.  ( as you can see in the 2 following images)

![image](https://cloud.githubusercontent.com/assets/5883405/13739568/2b53c5d2-e9cc-11e5-8cf1-9f039ba74561.png)

![image](https://cloud.githubusercontent.com/assets/5883405/13739588/4d8e3dc6-e9cc-11e5-81a2-cdf32dfbdc15.png)

But it is important for us also how big is each one of this queues, ( how many minutes of data are pending to write to disk when each metric has pending points).

When looking for carbon metrics the only similar seems to be "cache.size" 

![image](https://cloud.githubusercontent.com/assets/5883405/13741626/916ff146-e9d7-11e5-98db-fbd87f9c903b.png)

but in this case I expect cache.size be always more than cache.queue if each queue has at least one point waiting to be written to disk . 

When printed as nonNegativeDerivative() ( as in the following picture) 

![image](https://cloud.githubusercontent.com/assets/5883405/13741746/1a6a0d2e-e9d8-11e5-8067-78b49138f4e4.png)

Values are below of cache.queue 

- Which is the exact meaning for   "cache.queue/cache.size" metrics?
- How can I compute the number of pending points to write to disk?

NOTE: we are working with master version commit (b80ce915a5e420b46e6972512801491e536db1b6)

Thank you very much.

**Comment by obfuscurity** [comment]
From the Graphite book appendix on internal statistics:

```asciidoc
carbon.agents.<instance>.cache.bulk_queries::
  Number of bulk queries to the carbon-cache instance.
carbon.agents.<instance>.cache.overflow::
  Number of datapoints received while the cache was full.
carbon.agents.<instance>.cache.queries::
  Number of all cache queries received by the cache from the webapp.
carbon.agents.<instance>.cache.queues::
  Number of metric keys (metric name) in the cache at the time of recording.
carbon.agents.<instance>.cache.size::
  Number of metric datapoints in the cache at the time of recording.
```
