### ISSUE TITLE
Carbonate

### ISSUE THREAD

**Issue by jssjr** [graphite-project/carbon#533]
My role at work has changed enough that I'm finding it increasingly difficult to give https://github.com/jssjr/carbonate the attention it deserves. I'm certain some of you are frustrated with me for leaving issues and PR's open and unanswered. I'm sorry! :cry: 

Would the Graphite Project be interested in taking over the Carbonate tool kit? I'd be happy to transfer the entire repo if so. Long term, I think it makes sense to incorporate the carbonate tools directly into carbon and whisper.

/cc @mleinart @obfuscurity @SEJeff

**Comment by deniszh** [comment]
I think carbonate is still a vital part of Graphite stack. I still have plans to finish DIVERSE_REPLICA and implement different hashing functions to make it compatible with https://github.com/grobian/carbon-c-relay
And... we have not that many other tools to make work with Graphite clusters. IIRC only https://github.com/jjneely/buckytools - but it supports RF=1 only.
So, I'm voting :+1: and maybe can get some time for checking PRs and broken tests there...

**Comment by obfuscurity** [comment]
I'd be happy with bringing Carbonate into the org as its own project (e.g. `graphite-project/carbonate`).

**Comment by jssjr** [comment]
Much :heart: to you both for dedicating your time and effort to improving graphite and the larger monitoring community. I'll initiate the transfer.

**Comment by jssjr** [comment]
@obfuscurity - I have collaborator rights and not admin rights. I'll need to transfer the carbonate repo to you and let you transfer it into the graphite-project org.

**Comment by obfuscurity** [comment]
Okey doke.

**Comment by obfuscurity** [comment]
The transfer to https://github.com/graphite-project/carbonate is complete.

**Comment by deniszh** [comment]
Looks like project rights were not transferred? Could someone fix it? 
I want to close/reopen PRs in carbonate repo to retrigger Travis tests but can do that only with mine PR...

**Comment by obfuscurity** [comment]
Sorry about that, should be fixed now.
