### ISSUE TITLE
Branch to use in prod environment

### ISSUE THREAD

**Issue by gtonello** [graphite-project/carbon#536]
Hi guys,
This issue is just to solve a doubt.
 
I'm running graphite from package on pypi. But we're facing an issue that was fixed and merged on 0.9.x branch.
On pypi, package is 0.9.15 as master branch, right? And 0.9.x is ahead of master.
Is OK to use 0.9.x branch? Is an stable branch?

Thanks.

**Comment by deniszh** [comment]
No, all 0.9.x releases are derived from 0.9.x branch, including 0.9.12
Master has version 0.10.0 and it has no stable releases yet.

**Comment by gtonello** [comment]
Ah ok, got it.
Thanks @deniszh
