### ISSUE TITLE
Feature: rewrite rules for relay and cache

### ISSUE THREAD

**Issue by zerthimon** [graphite-project/carbon#541]
It'd be most awesome if rewrite rules could be implemented in relay and cache, in the same way they are implemented in aggregator. This would allow for greater flexibility when designing metrics namespaces.

**Comment by DanCech** [comment]
You can use `carbon-aggregator-cache` to run aggregation and cache in the same process.

**Comment by ganiserb** [comment]
@DanCech I find [this section](https://graphite.readthedocs.io/en/1.1.3/carbon-daemons.html#carbon-aggregator-cache-py) confusing.

Why does the carbon-aggregator-cache.py daemon need the relay-rules.conf file given that carbon-cache.py and carbon-aggregator.py do not? Does it also do relaying like carbon-relay.py does?

Also, which settings does the [aggregator-cache] section support in the carbon.conf file? It has no example section in the carbon.conf.example file. Maybe a union of both [cache] and [aggregator]?

**Comment by DanCech** [comment]
That appears to be a typo, the relay-rules.conf would be used by `carbon-aggregator`, not `carbon-aggregator-cache`.

I haven't used it myself, but it appears that it will look for an `[aggregator-cache]` section that can contain all the settings applicable to the aggregator and the cache.
