### ISSUE TITLE
Question about regex usage in storage-schemas.conf

### ISSUE THREAD

**Issue by gregvolk** [graphite-project/carbon#542]
I would like to have different retention rules for SNMP interface errors & discards versus interface traffic (Octets). So my storage-schemas.conf looks like this...

[carbon]
pattern = ^carbon\.
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[snmp_discards_errors]
pattern = ^snmp\.*(Discards|Errors)$
retentions = 60s:3d,5m:6d,120m:12d,1440m:360d

[snmp_interface_traffic]
pattern = ^snmp\.*Octets$
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[default_scheme]
pattern = .*
retentions = 60s:30d

I deleted some existing wsp files so I could see the change in file size that the new storage scheme would cause but as you can see below, all of the count.wsp files are the same size (518428 bytes). I expected the Octets files to be considerably larger than the Errors|Discards files based on the retention policy above.

Are my regex patterns incorrect? I think they should be matching "begins with snmp and ends with Octets" or "begins with snmp and ends with Discards or Errors". 

./snmp/inet/router/access1b/Te0-2-0/ifHCInOctets
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

./snmp/inet/router/access1b/Te0-2-0/ifHCOutOctets
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

./snmp/inet/router/access1b/Te0-2-0/ifInDiscards
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

./snmp/inet/router/access1b/Te0-2-0/ifInErrors
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

./snmp/inet/router/access1b/Te0-2-0/ifOutDiscards
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

./snmp/inet/router/access1b/Te0-2-0/ifOutErrors
-rw-r--r-- 1 nmsid nmsgroup 518428 Mar 30 11:54 count.wsp

Another related question I have is how can I do case insensitive matching? In perl I would write:
if ($var =~ /discards$|errors$/i) { do something } else { do something different }

Is it appropriate to put the 'i' for case insensitive matching as follows: pattern = ^snmp\.*(discards|errors)i$    ?

Thank you for your assistance.

**Comment by deniszh** [comment]
$ in regex means "end of line".
So, if all your your metric name ends in 'count' you need to change names to
```
[snmp_discards_errors]
pattern = ^snmp.*(Discards|Errors)\.count$
retentions = 60s:3d,5m:6d,120m:12d,1440m:360d

[snmp_interface_traffic]
pattern = ^snmp.*Octets\.count$
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d
```
or you can try to remove $:
```
[snmp_discards_errors]
pattern = ^snmp.*(Discards|Errors).*
retentions = 60s:3d,5m:6d,120m:12d,1440m:360d

[snmp_interface_traffic]
pattern = ^snmp.*Octets.*
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d
```

**Comment by gregvolk** [comment]
Thanks for your help.

Now I see where the metric name actually ends in count and not Octets, Discards, or Errors, so I removed the trailing $ characters in the pattern matches, removed the existing WSP files, and waited for new ones to be created. Unfortunately each new file is still 518428 bytes. Am I incorrect in assuming that the Errors|Discards WSP files should be smaller than the Octets files based on my retention settings? 

My new config (without the regex $ anchors) is below...

[carbon]
pattern = ^carbon\.
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[snmp_discards_errors]
pattern = ^snmp\.*(Discards|Errors).*
retentions = 60s:3d,5m:6d,120m:12d,1440m:360d

[snmp_interface_traffic]
pattern = ^snmp\.*Octets.*
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[default_scheme]
pattern = .*
retentions = 60s:30d



I also tried your first suggestion of using \.count$ at the end of the pattern but that resulted in the same 518428 byte file sizes.

**Comment by genisd** [comment]
Afaik schema allocation depends on your graphite/carbon versions.
Old versions will indeed allocate the full retention. Newer versions have a feature called sparse allocation. Maybe it's that (just guessing here honestly). You could double check using ```whisper-dump``` what retention was really allocated.

**Comment by deniszh** [comment]
:+1:  for @genisd advice - please use `whisper-info.py` utility to check retention scheme.

**Comment by gregvolk** [comment]
Thanks for the info about whisper-dump and whisper-info.py, I was not aware of those.

I ended up getting things to work with the following config...

[carbon]
pattern = ^carbon\.
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[snmp_discards]
pattern = ^snmp.*Discards*
retentions = 60s:3d,5m:6d,120m:12d,1440m:360d

[snmp_errors]
pattern = ^snmp.*Errors*
retentions = 5m:6d,120m:12d,1440m:360d

[snmp_interface_traffic]
pattern = ^snmp.*Octets*
retentions = 60s:30d,5m:60d,120m:120d,1440m:360d

[default_scheme]
pattern = .*
retentions = 60s:1d


With the above config parms, my file sizes look correspondingly correct...

/*large 747kbytes retention for Octets (traffic) data*/
access1b/Te0-2-0/ifHCOutOctets:
-rw-r--r-- 1 nmsid nmsgroup 747424 Mar 30 14:20 count.wsp

/*small 78kbyte retention for Discards*/
access1b/Te0-2-0/ifInDiscards:
-rw-r--r-- 1 nmsid nmsgroup 78688 Mar 30 14:20 count.wsp

/*even smaller 26kbyte retention for Errors*/
access1b/Te0-2-0/ifInErrors:
-rw-r--r-- 1 nmsid nmsgroup 26836 Mar 30 14:20 count.wsp


I experimented for quite some time trying to figure out how to make the pattern matches case insensitive but did not succeed at that. No matter, I'm content with the way it's working now.

Thank you all for your assistance.
