### ISSUE TITLE
graphite updating wrong node whisper file

### ISSUE THREAD

**Issue by rechena** [graphite-project/carbon#543]
Hi all, 
Not sure if this issue was raised before of its just some weird accident. Please apologise is this is the wrong place for this question. 
We currently had a couple VM's with, lets say the ip's 1.1.1.1 and 1.1.1.2 and named zbr.com xpto.com, they were destroyed and the ips reused with the new VMs with the names: this.com and that.com. 

We have collectd running on the hosts and configured to have:

<Plugin write_graphite>
  <Node "this.com">
    Host "graphitehost"
    Port "25826"
    Protocol "udp"
    LogSendErrors true
    Prefix "collectd_"
    StoreRates true
    AlwaysAppendDS false
    EscapeCharacter "_"
  </Node>
</Plugin>

What was hapenning was that it started to update the whisper files on the collectd_zbr_com instead of creating a collectd_this_com. I had to stop collectd on those nodes, remove the whisper files and eventually it started to get the right names/info. 

Has this happened to anyone? 

Thanks for the help.

**Comment by bmhatfield** [comment]
I've never observed this kind of behavior. The way graphite routes metrics to files is, at it's core level, possibly too simple for this to occur in practice - the IP address re-use should have no bearing on this problem unless those IPs were part of the metric path.

One thing I *have* observed is that new metrics can sometimes be slow to provision - sometimes 30m in our deployment. Is it possible that's what you observed?

**Comment by rechena** [comment]
HI @bmhatfield thanks for you reply, actually I don't think its that because the new server was up for around 2 days. plus when I removed the folder for the old host it started to create again with the old name.. only when I stopped collectd on the host and removed again it worked. I never saw this happen before/also.

**Comment by bmhatfield** [comment]
Could you tell us more information about how metrics get from Collectd to disk on the Graphite server in your infrastructure? List out the steps in the process, for example: `collectd -> dns a-record -> carbon-cache -> whisper`.

**Comment by rechena** [comment]
Hi, yes, thats the process we have collectd installed/configured via Puppet on our hosts which will then send via IP address to the graphite box where I have graphite+carbon cache sending to whisper files.

Does it help? 

Thanks
