### ISSUE TITLE
Is carbon appropriate for that situation

### ISSUE THREAD

**Issue by mrwd2009** [graphite-project/carbon#544]
Recently, while using carbon, I was confused with some problem, hope you could help me.

We need to monitor the performance of the `Storage` device,  the Storage have 65535 `volumes`, each volume have 30 performance data. 

**My questions are as follow:**
1.  Is it possible to create 1966050 ".wsp" by carbon theoretically?
2.  We have installed graphite on CentOS 7, we use **plaintext protocol** to send data to carbon. The total number of sended data is 65535 \* 30 = 1966050, the sended data format is `volume_id.performance_name performance_value timestamp\n`. But after data sended successfully, there only  **125964** .wsp file created. I have modified `limits.conf`  file and total capacity of my disk is 500G.  Is carbon not appropriate? Could you give me some suggestion?

**the contenf of the limits.conf** 

```
* soft nofile 1000000 
* hard nofile 1000000 
```

**Comment by deniszh** [comment]
Hi @mrwd2009 ,
>1. Is it possible to create 1966050 ".wsp" by carbon theoretically?
Yes. If you're using "volume_id.performance_name" metric name, you will have /opt/graphite/storage/whisper/<65535 directories>/<30 *.wsp files each>
Maybe you will need to increase number of inodes during FS creation, not sure if 500G defaults is enough with storing 2 mln files. Run `df -i` and check free inodes (IFree)

2. You also need to increase file creation limit in carbon - `MAX_CREATES_PER_MINUTE` variable.
By default it is 50, so creating 1966050 metrics will take 1966050/50/60/24 = 27 days
Increase it to e.g. 10000, but please note that yon can thrash your disk with very big value. 
On 10000 creating of 2mln metrics will take around 3 hours btw.

**Comment by deniszh** [comment]
Correction: default `MAX_CREATES_PER_MINUTE` is `Inf`, so, not set, but example config contains exactly 50. So good to check. If it's not in your config then it's `Inf` and maybe it will work OK for you.

**Comment by mrwd2009** [comment]
Hi@deniszh,
Thank you very much, I will try according your answer.
