### ISSUE TITLE
whisper 0.9.13 pinned in carbon 0.9.15 requirements.txt

### ISSUE THREAD

**Issue by jblaine** [graphite-project/carbon#545]
Is this a bug? Why wouldn't this be pinned to whisper 0.9.15?

https://github.com/graphite-project/carbon/blob/0.9.15/requirements.txt

**Comment by deniszh** [comment]
Looks like it.

**Comment by jblaine** [comment]
Would you like a PR that fixes it? Is there much point if 0.9.16 will come out and it will incorrectly then say 0.9.15? Not being a smart-ass, just wondering if there's a workflow in place where 0.9.13 was supposed to get auto-updated during the 0.9.15 release and the workflow failed someplace other than requirements.txt

**Comment by obfuscurity** [comment]
Yes, I would strongly consider a 0.9.16 if that will compel users on older releases to update for the fixes/enhancements added in 0.9.14 or 0.9.15.

**Comment by deniszh** [comment]
It's still pointed to 0.9.13 in 0.9.x, should be fixed
