### ISSUE TITLE
Slow Whisper DB Creation

### ISSUE THREAD

**Issue by tsantoyo** [graphite-project/carbon#547]
Hey all,

We're seeing somewhat unusually slow whisper database creation.  On a standalone test box I am seeing anywhere from 1 to 3 minutes for a database to show up.  This is a box with a carbon-relay in front of 4 carbon-cache instances.  Also, there were no other metrics being sent at the time.  Just the one initial one to create the DB.  Not sure if I am overlooking some config options here, or this is intended behavior.  Any insight would be great!

Here's my carbon.conf

```
[cache]
ENABLE_LOGROTATION = True
USER =
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 50
MAX_UPDATES_PER_SECOND_ON_SHUTDOWN = 1000
MAX_CREATES_PER_MINUTE = 2000
LINE_RECEIVER_INTERFACE = 127.0.0.1
ENABLE_UDP_LISTENER = True
UDP_RECEIVER_INTERFACE = 127.0.0.1
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
LOG_LISTENER_CONNECTIONS = False
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 127.0.0.1
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = False
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False
WHISPER_FALLOCATE_CREATE = True
USE_WHITELIST = True

[cache:a]
LINE_RECEIVER_PORT = 2103
PICKLE_RECEIVER_PORT = 2104
UDP_RECEIVER_PORT = 2105
CACHE_QUERY_PORT = 7102

[cache:b]
LINE_RECEIVER_PORT = 2203
PICKLE_RECEIVER_PORT = 2204
UDP_RECEIVER_PORT = 2205
CACHE_QUERY_PORT = 7202

[cache:c]
LINE_RECEIVER_PORT = 2303
PICKLE_RECEIVER_PORT = 2304
UDP_RECEIVER_PORT = 2305
CACHE_QUERY_PORT = 7302

[cache:d]
LINE_RECEIVER_PORT = 2403
PICKLE_RECEIVER_PORT = 2404
UDP_RECEIVER_PORT = 2405
CACHE_QUERY_PORT = 7402

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
ENABLE_UDP_LISTENER = True
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 2005
LOG_LISTENER_CONNECTIONS = True
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2104:a,127.0.0.1:2204:b,127.0.0.1:2304:c,127.0.0.1:2404:d
MAX_DATAPOINTS_PER_MESSAGE = 500
MAX_QUEUE_SIZE = 10000
USE_FLOW_CONTROL = True
```

**Comment by deniszh** [comment]
Try to increase MAX_CREATES_PER_MINUTE - now it's limited to 2000 creations per minute.

**Comment by piotr1212** [comment]
This can happen when a metric is already received by the cache but not written to disk.

graphite-web first checks if metrics exists on the local disk before it queries the cache.

**Comment by tsantoyo** [comment]
Thanks for the comments guys.  I think my testing method was flawed, as I was able to resolve this in our production environment.  It turns out our cache size (carbon.agents.*.cache.size) was very large, and this was effecting DB create time.  I was able to reduce the cache size by running a relay in front of multiple carbon caches.  

All is good now.  Closing this issue.

**Comment by obfuscurity** [comment]
Glad to hear it. 👍
