### ISSUE TITLE
Error reporting not-useful when whisper creation fails

### ISSUE THREAD

**Issue by Gillingham** [graphite-project/carbon#552]
I was encounterring an issue were carbon would fail to create any of the whisper files, it simply output the non-helpful message of:
```
02/05/2016 23:20:03 :: [creates] new metric carbon.agents.carbon-a.committedPoints matched schema carbon
02/05/2016 23:20:03 :: [creates] new metric carbon.agents.carbon-a.committedPoints matched aggregation schema default
02/05/2016 23:20:03 :: [creates] creating database file /opt/graphite/storage/whisper/carbon/agents/carbon-a/committedPoints.wsp (archive=[(60, 129600)] xff=None agg=None)
02/05/2016 23:20:03 :: [console] 'Error creating /opt/graphite/storage/whisper/carbon/agents/carbon-a/committedPoints.wsp'
02/05/2016 23:20:03 :: [creates] new metric carbon.agents.carbon-a.cache.bulk_queries matched schema carbon
02/05/2016 23:20:03 :: [creates] new metric carbon.agents.carbon-a.cache.bulk_queries matched aggregation schema default
02/05/2016 23:20:03 :: [creates] creating database file /opt/graphite/storage/whisper/carbon/agents/carbon-a/cache/bulk_queries.wsp (archive=[(60, 129600)] xff=None agg=None)
02/05/2016 23:20:03 :: [console] 'Error creating /opt/graphite/storage/whisper/carbon/agents/carbon-a/cache/bulk_queries.wsp'
```

I had to edit https://github.com/graphite-project/carbon/blob/master/lib/carbon/writer.py add change the except block outputting that Error creating %s line to also print out the exception, this should be done by default, leaving the user with no actual debugging message available without editing source is far from ideal.

It's tangential to this but apparently I had to disable `FALLOCATE` as I'm writing to an NFS drive.

**Comment by tmack0** [comment]
Just hit this as well, possibly due to version mis-match between whisper and carbon. The create() method in our whisper.py lib only takes 5 args, the version of carbon we had tried to pass 6, last tow being settings.WHISPER_CREATE_SPARSE and settings.WHISPER_FALLOCATE_CREATE)
Adding an extra arg that goes unused to the list for whisper.py:306 create() fixes the "error creating" problem for us.
