### ISSUE TITLE
carbon-cache does not respect umask

### ISSUE THREAD

**Issue by lassewesth** [graphite-project/carbon#555]
Hey,

I grabbed an AWS instance with Ubuntu 16.04 on it (AMI `ami-7a138709`), and did `$ sudo apt-get install graphite-carbon` to it. That got me among other things this:

```
...
Preparing to unpack .../python-twisted-core_16.0.0-1_all.deb ...
Unpacking python-twisted-core (16.0.0-1) ...
Selecting previously unselected package python-whisper.
Preparing to unpack .../python-whisper_0.9.15-1_all.deb ...
Unpacking python-whisper (0.9.15-1) ...
Selecting previously unselected package graphite-carbon.
Preparing to unpack .../graphite-carbon_0.9.15-1_all.deb ...
Unpacking graphite-carbon (0.9.15-1) ...
...
```

I then customize the service script and reload the service:

```
$ cat /lib/systemd/system/carbon-cache.service.d/umask.conf 
[Service]
UMask=0002
$ sudo systemctl daemon-reload
$ sudo service carbon-cache restart
```

I clear out `/var/lib/graphite/carbon` and wait a while. A little later, I have files and directories created by carbon-cache that clearly do not have the right permissions - they are supposed to have group writes too:

```
$ ll /var/lib/graphite/whisper/carbon/agents
total 12
drwxr-xr-x 3 _graphite _graphite 4096 May 18 10:08 ./
drwxr-xr-x 3 _graphite _graphite 4096 May 18 10:08 ../
drwxr-xr-x 3 _graphite _graphite 4096 May 18 10:09 ip-10-79-43-155-a/
$ ll /var/lib/graphite/whisper/carbon/agents/ip-10-79-43-155-a/creates.wsp 
-rw-r--r-- 1 _graphite _graphite 1555228 May 18 10:38 /var/lib/graphite/whisper/carbon/agents/ip-10-79-43-155-a/creates.wsp
```

My end goal is to have both files and directories end up with write permissions, so that group members can clear out the cache.

Can you help?

**Comment by lassewesth** [comment]
Ping @obfuscurity: does this ring any bells? Surely it is a common use case to want to clear out cache, no?

**Comment by deniszh** [comment]
carbon usually should obey umask. I'm suspecting some systemd bug.

**Comment by piotr1212** [comment]
It should but I just checked, and it doesn't so this is a bug.

**Comment by piotr1212** [comment]
So this is a twisted thing. The correct way to set the umask is use the --umask command line option, which is exposed in carbon, for example: `./bin/carbon-cache.py --umask 0002 start`.

For more info see: https://twistedmatrix.com/trac/ticket/966
