### ISSUE TITLE
Any alert component planed

### ISSUE THREAD

**Issue by andyxning** [graphite-project/carbon#556]
Currently, Graphite is very good for monitoring, there is no alert component now. 

Any play for supporting this.

**Comment by genisd** [comment]
There are tools that process the graphite metric stream and can trigger alerts. Riemann is one of them afaik

**Comment by gwaldo** [comment]
No, there are no plans to add an alerting component.  It is not "missing".

Graphite is explicitly designed to do one thing.  It is intended to be the metrics component in a pluggable / composable insight tooling ecosystem, where the tooling is agnostic to one-another, data is easy to extract, and components may be replaced easily.

**Comment by JeanFred** [comment]
@andyxning  In case you are looking for such tools that alert from Graphite data, you may look at this section of the docs: http://graphite.readthedocs.io/en/latest/tools.html#monitoring

**Comment by andyxning** [comment]
@JeanFred @genisd Ok, i will have a look at that. 👍 
@gwaldo , thanks for mentioning the purpose of Graphite. 👍
