### ISSUE TITLE
[relay] and [aggregator] sections do not inherit from [cache] section

### ISSUE THREAD

**Issue by danfrincu** [graphite-project/carbon#557]
Perhaps this is by design, but working with 0.9.15 on Centos 7 I've found that if you don't specify a USER in [relay] or [aggregator] sections it will start the processes under root, whereas for the [cache] section which has a default USER it will start the process under the said user, in this case carbon.

Given this behaviour, what other variables from the [cache] section are and are not inherited by the [relay] and [aggregator] sections?

I'm asking this because based on the docs I was expecting that the variables would be inherited from the [cache] section but I may have misinterpreted this and there is need for duplication of certain variables to the other sections, but it's unclear which are and which are not inherited, henceforth the question above.

Kind regards,
Dan

**Comment by deniszh** [comment]
IIRC and it's by design, indeed. And none of the variables are inherited BETWEEN sections - only from [x] to [x:instance], but not between [x] and [y]...

**Comment by danfrincu** [comment]
Is there a list of variables that exist in [cache] that can be applied to the other sections (not instances). The example being the USER variable, which is defined in [cache] but can be used in other sections.

**Comment by deniszh** [comment]
Sorry, but why that list could be needed if there's no inheritance between different section exists?...

**Comment by danfrincu** [comment]
Because for certain settings such as MAX_QUEUE_SIZE the config calls out the setting explicitly both in the [relay] and [aggregator] section, CARBON_METRIC_PREFIX is called out in all 3 sections, but the example above, USER, is only referenced in the [cache] section. 

Based on the example config file, the assumption is if the setting is only in one section, that's the only section it should be set to, but that's not entirely true as you can set USER in all the sections.

And for example, if I define STORAGE_DIR in [cache] as /something but I don't define it in the other sections, I assume that the other sections would use the default value for STORAGE_DIR and point someplace else.

A list of "what's available per section" is useful to deduct if any other settings can and should be added to the other sections.

**Comment by deniszh** [comment]
STORAGE_DIR has no sense for [relay] and [aggregator], isn't it?
IMO if you put all combinations of all options to all sections config example will be "overloaded". 
Sorry, still see no much gain from the effort. But feel free to fix documentation or config example if you want to - https://github.com/graphite-project/graphite-web/tree/master/docs

**Comment by danfrincu** [comment]
Yes, STORAGE_DIR wasn't the best example but you understand where I was going with this.

I understand adding all combinations to all sections would not be ideal.

Ok, then what would be a way for me to extract all of the valid options for each section?

**Comment by deniszh** [comment]
That's my point - reading source code is a single way how you can do that. It's all there - https://github.com/graphite-project/carbon/blob/master/lib/carbon/conf.py
Not a rocket science but some efforts are required.

**Comment by danfrincu** [comment]
Understood. In the meantime I've created a pull request for updating the docs as I think USER setting is an important one to have for all sections. https://github.com/graphite-project/carbon/pull/558
