### ISSUE TITLE
Carbon-Cache has strange cache-drain behavior

### ISSUE THREAD

**Issue by bmhatfield** [graphite-project/carbon#559]
Hi friends,

I'm filing this issue for two reasons: 1) to share that I am looking into it and 2) to see if anyone else is already aware of this problem.

Carbon-Cache is holding onto too much data and only really making progress draining on strange intervals. These intervals change over time, and different hosts show different timings.

Here's an image showing committed points across hosts:
![image](https://cloud.githubusercontent.com/assets/1119967/15687970/c4948202-2745-11e6-8302-c223b40f0c71.png)

Here's an image comparing committed points and the cache size:
![image](https://cloud.githubusercontent.com/assets/1119967/15687995/e5bc54e6-2745-11e6-9a82-b1811a9884f2.png)

This behavior is problematic for a few reasons:
1) It uses far too much memory. I prefer to have absolutely as much memory as possible available to Linux's disk caching, as years of experimentation have demonstrated that it's by far the best way to make a Graphite install on EBS perform well.
2) It means that I more-or-less cannot efficiently stop carbon-cache. If I SIGTERM it, it must drain for a long time, and it cannot accept new metrics during that time. We're talking 40-60 minutes here. If I SIGKILL it, it drops all the points in the cache, losing about 40-60 minutes worth of data.
3) It degrades performance. There's O(n) or worse sorts in carbon-cache. The larger the cache size is, the worse it performs.

Finally, I have tried a number of things, such as tuning MAX_UPDATES_PER_SECOND (generally by adding 0s to the number), which do not seem to have a large effect on this problem. Note that the time range of the image above is 12 *hours*, which implies to me that there's some emergent behavior here that's possibly unintended.

I don't really remember the internals of how carbon-cache works, nor do I currently see enough instrumentation to diagnose this problem without further probing, which I am embarking on now.

If you're familiar with this issue, I'd love to hear from you either if you're affected, or if you have some suggestions.

Thanks,
Brian

**Comment by bmhatfield** [comment]
I think an important clue is that I only see messages like this:

`Sorted 297165 cache queues in 1.151172 seconds` roughly every flush interval.

**Comment by bmhatfield** [comment]
After examining this some more, I believe that the delay here is in fact the loop over all of the series to be flushed. I'm not sure why it takes so long, but I have a few observations:

* `PointsPerUpdate` is much higher during the "fast drain" time. Coupled with the `OptimalWriteOrder()` function, which sorts series by number of points to write, this implies that "fast drain" is happening when we're handed series where we can call `updateMany()` on and get a lot of points out of the cache per each update. This also potentially implies that the "slow" write time is the long tail of all of the other series. I'm not sure why some series would have more points than others; as I expect each series to receive even updates.
* Carbon-cache is not CPU bound at this time, implying that it's the latency of going through each file that's the problem. The latency is not outrageous, but each carbon-cache process must go through 300k-400k whisper files each loop.
* Adding more carbon-cache processes helps (the loops are shorter); this implies that less series per process as well as more things "waiting in parallel" improve the total throughput (bandwidth delay product).

There may be some opportunity here. If we're waiting for access to each file, it may make sense to optimize this path in a few ways:

* Queue & Parallelize the `update_many()` calls
* Filter out low-value `update_many()` calls (1-5 points)
* Experiment with tuning down linux readahead values. This is tricky to do as each change requires restarting carbon-cache :-(

**Comment by bmhatfield** [comment]
Er, my mistake: `sorted` results in the *smallest* series first.

```python
>>> a = [('a', 5), ('b', 2), ('c', 3)]
>>> sorted(a, key=lambda x: x[1])
[('b', 2), ('c', 3), ('a', 5)]
```

https://github.com/graphite-project/carbon/blob/0.9.x/lib/carbon/cache.py#L37

**Comment by bmhatfield** [comment]
Okay, I think this is potentially even weirder.

```python
from carbon import cache

metrics = [
	'a','b','c','d','e','a','d'
]

c = cache.MetricCache

now = time.time()

for i in range(192):
	for m in metrics:
		c.store(m, (now + i, i))

while c:
	print c.pop()[0]
```

outputs something like you might expect:

```
d
a
e
b
c
```

But this isn't what Graphite is doing. Graphite is *also* calling `MetricCache.store()` via a separate thread in Twisted, while we are trying to drain our cache. I think we can simulate that behavior without threads by calling store for each loop we are retrieving an item:

```python
while c:
	c.store('a', (now, 12))
	c.store('b', (now, 14))
	print c.pop()[0]
```

That results in an infinite loop:

```
a
d
b
e
c
a
b
a
b
a
b
a
b
a
b
a
b
a
b
a
b
a
b
a
b
a
b
a
b
[...]
```

I wonder if instead of this being a pure latency problem getting through 360K metrics, it's instead a race condition?

**Comment by cbowman0** [comment]
Which CACHE_WRITE_STRATEGY do you use?

Last time I encountered something similar, while using the megacarbon branch so slightly different code, I decided that I had reached the max number of twisted events/sec that a single core on my servers could handle.  The writer thread was not being rate limited and io stats showed more available iops but it was not keeping up.  The solution was to run more carbon processes because I had more CPU and IO available.  Maybe there is/was something else going on, so I'm curious where this goes.

**Comment by bmhatfield** [comment]
I'm using 'sorted' (I believe this is the default). I haven't tried other modes. This is on 0.9.x of carbon.

**Comment by bmhatfield** [comment]
I think it's safe to say I had a bug.

<img width="345" alt="screen shot 2016-06-02 at 11 03 07 pm" src="https://cloud.githubusercontent.com/assets/1119967/15767472/35e1ee1e-2916-11e6-817d-fc41710302c1.png">

**Comment by bmhatfield** [comment]
Okay, after studying this behavior now that all of our over-sending systems have been adjusted, the fix here is as simple as not sending more data to carbon-cache than it can flush in a loop. It's especially bad if you have a high number of series and some of those series send data a lot more frequently, since the loop will take a long time to "get back" to the more-frequent series so you'll see this sawtoothed fill-flush behavior.

There's a few approaches one can take without code changes being necessary.

1) Don't send metrics at a frequency that doesn't match your whisper retention. This is obvious and was the fix in my case.
2) Run carbon-cache processes such that the number of series in each process is low enough that the loop time will be acceptable.
3) Investigate code changes to optimize this loop. I suspect that additional parallelization in-process could have a significantly positive effect on the total iteration time.

I hope this helps other folks who may see this in the future.
Brian
