### ISSUE TITLE
Replace racially charged language "whitelist/blacklist"

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/carbon#567]
Issue opened in Carbon to track the issue described in https://github.com/graphite-project/graphite-web/issues/1569

The Carbon PR will link to this issue.

**Comment by gwaldo** [comment]
Linking https://github.com/graphite-project/carbon/pull/568

**Comment by gwaldo** [comment]
Ready for review per https://github.com/graphite-project/carbon/pull/568#issuecomment-230126650 and https://github.com/graphite-project/carbon/pull/568#issuecomment-230126653

**Comment by obfuscurity** [comment]
Closing this issue and https://github.com/graphite-project/graphite-web/issues/1569 so we can focus on the technical aspects of the PRs themselves.
