### ISSUE TITLE
multi host send same metrics problem

### ISSUE THREAD

**Issue by billowqiu** [graphite-project/carbon#571]
I have two hosts which send same counter metrics into carbon.
then the graph only show one host's metrics.

**Comment by obfuscurity** [comment]
What are the metric names?

**Comment by billowqiu** [comment]
"PRODUCTION.host.ip-0.requests.m1_rate"
I follow this post 
http://www.franklinangulo.com/blog/2014/6/6/graphite-series-6-carbon-aggregators.

I want to use statsd and graphite together.
Service in two hosts will send same count metrics into one carbon.
I think the later sent metrics overwrite former metrics in interval(10s).

**Comment by obfuscurity** [comment]
Sorry, your reply is sort of all over the place. If you're sending two distinct metrics but only one of them is appearing, then one of the following is happening:

1. the 2nd metric is not actually arriving
1. both metrics actually have the same name
1. your render query is incorrect

Now you're talking about aggregating, which also introduces the possibility that you're **not** actually sending two distinct metrics, but only one. I'm not sure what your actual situation is but hopefully I've given you some things to investigate.

**Comment by billowqiu** [comment]
Thanks for your reply.
My situation is the second one: "both metrics actually have the same name"
So i use aggregating(statsd send to carbon-aggregator), but now there is no any data in  "storage/whisper/stats/counters/PRODUCTION/host/ip-0/requests/m1_rate/count.wsp"

I want to know if i send same name metrics in different hosts, how can i get the sum counter.

**Comment by obfuscurity** [comment]
Simple, don't send them with the same name. Embed their distinct hostname in each respective metric. 👍

**Comment by billowqiu** [comment]
Yes, send them with embed their hostname can solve this problem.
I can only  use carbon-aggregator to get the **sum** counter in different host? Or any other way?

**Comment by obfuscurity** [comment]
You can use carbon-aggregator to get the sum across all of your distinct hosts. https://github.com/graphite-project/carbon/blob/master/conf/aggregation-rules.conf.example provides examples.
