### ISSUE TITLE
Unhandled Error: return pickle_obj.load() exceptions.EOFError:

### ISSUE THREAD

**Issue by JFC-MC** [graphite-project/carbon#584]
Hi

We use carbon==0.9.15.
We send metrics to Carbon via pickle listener and get errors like these every 1-10 minute:

> 02/09/2016 10:55:30 :: Unhandled Error
> Traceback (most recent call last):
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
>     return callWithContext({"system": lp}, func, _args, *_kw)
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
>     return context.call({ILogContext: newCtx}, func, _args, *_kw)
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, _args, *_kw)
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
>     return func(_args,_*kw)
> --- <exception caught here> ---
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
>     why = selectable.doRead()
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
>     return self._dataReceived(data)
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "/opt/test/python/lib/python2.7/site-packages/twisted/protocols/basic.py", line 765, in dataReceived
>     self.stringReceived(packet)
>   File "/opt/test/packages/graphite/lib/carbon/protocols.py", line 102, in stringReceived
>     datapoints = self.unpickler.loads(data)
>   File "/opt/test/packages/graphite/lib/carbon/util.py", line 139, in loads 
>     return pickle_obj.load()
> exceptions.EOFError:

Any help would be appreciated. Thanks.

**Comment by deniszh** [comment]
```File "/opt/test/packages/graphite/lib/carbon/protocols.py", line 102, in stringReceived
datapoints = self.unpickler.loads(data)
File "/opt/test/packages/graphite/lib/carbon/util.py", line 139, in loads 
return pickle_obj.load()
exceptions.EOFError:
```
I'm suspecting that you sending some broken pickle message, which could not be successfully unpickled.

**Comment by JFC-MC** [comment]
Thank you for your answer.
We'll check it later on the next week. I'll let you know about results. Thanks.

**Comment by deniszh** [comment]
We should catch error properly, though
