### ISSUE TITLE
Error when using CACHE_WRITE_STRATEGY = native

### ISSUE THREAD

**Issue by jds86930** [graphite-project/carbon#585]
Seeing this on carbon-cache when I try to use "CACHE_WRITE_STRATEGY = native". "CACHE_WRITE_STRATEGY = sorted" works fine. I wanted to try native to see if it would improve IO. This is observed in Graphite 0.9.15.

> 04/09/2016 21:20:44 :: Unhandled Error
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
>     result = inContext.theWork()
>   File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
>     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
>     return func(*args,**kw)
> --- <exception caught here> ---
>   File "/opt/graphite/lib/carbon/writer.py", line 158, in writeForever
>     writeCachedDataPoints()
>   File "/opt/graphite/lib/carbon/writer.py", line 90, in writeCachedDataPoints
>     for (metric, datapoints, dbFilePath, dbFileExists) in optimalWriteOrder():
>   File "/opt/graphite/lib/carbon/writer.py", line 62, in optimalWriteOrder
>     (metric, datapoints) = MetricCache.pop()
>   File "/opt/graphite/lib/carbon/cache.py", line 76, in pop
>     self.size -= len(datapoints[1])
> exceptions.UnboundLocalError: local variable 'datapoints' referenced before assignment

**Comment by obfuscurity** [comment]
There is no "native" strategy. I think you mean "naive".
