### ISSUE TITLE
Sparse metric stuck in cache

### ISSUE THREAD

**Issue by deanbittner** [graphite-project/carbon#587]
Metric reporting hourly, as below on half hour.  Metric for one hour (~4:30, missing) reported in next hour (5:30, value 2.0).
```
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 01:30:10,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 02:30:10,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 03:30:10,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 05:30:10,2.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 06:30:10,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 07:30:10,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 08:33:00,1.0
invidi.etl.localhost_localdomain.loadCDSImpressionReports.success,2016-09-06 09:32:40,1.0
```
Telemetry elsewhere in the stack (at brubeck [StatsD alternative]) confirm that the metric was sent to carbon-cache at 3:30 as expected, second in list below.
```
instance=brubeck_etl sampler=statsd event=metchk metric=invidi.etl.localhost_localdomain.loadCDSImpressionReports.success value=1.0 type=meter stamp=1473143407
instance=brubeck_etl sampler=statsd event=metchk metric=invidi.etl.localhost_localdomain.loadCDSImpressionReports.success value=1.0 type=meter stamp=1473147008
instance=brubeck_etl sampler=statsd event=metchk metric=invidi.etl.localhost_localdomain.loadCDSImpressionReports.success value=1.0 type=meter stamp=1473150607
instance=brubeck_etl sampler=statsd event=metchk metric=invidi.etl.localhost_localdomain.loadCDSImpressionReports.success value=1.0 type=meter stamp=1473154208
```

**Comment by obfuscurity** [comment]
That would be a problem with your client or aggregator, not Graphite. Graphite just stores whatever value was sent to it.

**Comment by deanbittner** [comment]
The metric is sent to, and accepted by carbon, at 4:30am.  The expected behaviour is that this metric, like all the others sent hourly, is stored, and shows up in a graphite query with the associated time of around 4:30 with a value of 1.0.

The actual behaviour is that the metric sent at 4:30 doesn't show up until 5:30, along with the metric sent at 5:30 as a count of 2.0.

So, with respect to your comment.  It does eventually store what's sent, just an hour late.  I would expect it be stored when sent, as it is most of the time.  This happens near 1/20 (5%) of the time.

**Comment by obfuscurity** [comment]
Graphite will store the value given at the timestamp given. If the metric is being summed into the wrong period it's because it's coming from the aggregator as such.

**Comment by obfuscurity** [comment]
Apologies if I'm misunderstanding your question. It sounded like you were saying the metric is being stored incorrectly, but now I'm wondering if you're saying that it's simply not visible until an hour later. Can you elaborate?

**Comment by deanbittner** [comment]
Ok ... I get that now ... even if I report a metric @5:30 with a 4:30 timestamp, it will get logged into the 4:30 time period.  That's helpful.  It's getting stuck in brubeck is what you're saying.  Got it.

**Comment by deanbittner** [comment]
I don't think that's happening as I'm logging AFTER sent from brubeck, with the data/ timestamp in brubeck so ... I have a log from brubeck that I sent the metric at 4:30am with a 4:30am timestamp.  I guess I need a tcpdump showing the metric coming into carbon for things to be conclusive.

**Comment by obfuscurity** [comment]
Yes, Carbon/Whisper are generally pretty dumb in this regard. They will store the value at the timestamp provided; they make no other assumptions or alterations. The exception to this would be if you were using `carbon-aggregator` but that doesn't sound like it applies here.
