### ISSUE TITLE
Expiring aggregator MetricBuffers

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/carbon#588]
As described in https://github.com/graphite-project/carbon/issues/185#issuecomment-246122400, the aggregator's metric buffers are stored in a Python dict which will grow to accommodate the maximum number of keys at any point in time. Unfortunately, Python's gc does not attempt to release this memory at any point. Currently the only way to free up the buffer memory is to restart the aggregator process (or update your aggregator rules, at which point it clears all existing buffers).

It would be useful to incorporate an expiry into each MetricBuffer. Whenever a datapoint arrives the timer gets pushed back again, but if the timer is reached the buffer will close itself.

/cc @mleinart

**Comment by wridgers** [comment]
We believe we are still experiencing this. How is it that nobody is complaining about it? Hehe. :)

![2018-09-20-150238_1113x726_scrot](https://user-images.githubusercontent.com/235730/45823731-46bb9a80-bce6-11e8-8a96-c57bf0479295.png)

Log scale seems to show something doubling (Python dict allocation?)
