### ISSUE TITLE
Greate time difference between arrival of metric and retrievability

### ISSUE THREAD

**Issue by bemeyert** [graphite-project/carbon#602]
Hi all,

We're using Carbon-Cache 0.9.15. The disks are pretty fast NVMe SSDs which show no sign of congestion. All other data, like CPU, Interrupts etc are "very" healthy. We shard our metrics via a dedicated carbon-c-relay instance. Per Server we currently have 8 shards, so 8 carbon-cache processes per server. There runs only one Graphite-Web instance per server.

When I send a metric to the cache, it arrives without delay at the servers network stack (tcpdump). Parallel I start a GET on the metric via graphite-web, which loops so long until it can fetch the key/value from the sent metric. There is a lag of up to more than 12 seconds. The mean is around 5 seconds. Which is way too long, because we have a second graphite machine with much slower hardware and higher utilization where this takes around 0.2/.3 seconds.

The time of the HTTP-Requests are way below a second. So I don't think the problem comes from graphite-web.

Output of the script:
```
$ date ; ./check_graphite_service -g mon-carbon ; date
Do 6. Okt 17:51:39 CEST 2016
OK: Got expected value in at least 5.4 seconds
Do 6. Okt 17:51:47 CEST 2016
```
And the corresponding log line from the `update.log`:
```
06/10/2016 17:51:47 :: wrote 1 datapoints for admin.test.check_graphite_service.mon-carbon in 0.00006 seconds
```
So only when Carbon has written the metric it can be retrieved. Not only does it take too long, but also I thought that as soon as the metric arrives in Carbon it is retrievable from the in-memory cache regardless if it has been written to disk or not.

How can I find the culprit? Any help solving this "mystery" is much appreciated.

Cheers

P.S.: Sry if I post this here since this doesn't seem to be a bug/issue. But I couldn't find a mailing list or some such...

**Comment by deniszh** [comment]
It's a quite long and not quite easy issue - https://github.com/graphite-project/graphite-web/issues/629
Carbon uses files on disk to get existing metrics, and there's no way how you can resolve metrics with globs w/o checking files on disk. We can implement cache check for single metric only, but that's not really helping.
So, for now, please increase `MAX_CREATES_PER_MINUTE` value in your conf to some sane value. The default is 50 and that could be quite low for SSD disks.

**Comment by bemeyert** [comment]
@deniszh The whisper files have been created long ago before the test. So I don't think our problem is in the creation of the whisper files, if I understand you correctly.

**Comment by bemeyert** [comment]
@deniszh But after "really" reading the issue https://github.com/graphite-project/graphite-web/issues/629 this problem not only exists with new metrics but also with already existing whisper files. Or did I get this wrong?

There is still the problem why it takes Carbon-Cache that long to make the new value retrievable?

**Comment by deniszh** [comment]
No, the problem in issue #629 is only for new metrics. If metrics coming to cache it should be available immediately. If it's not - then your cache doesn't work. 
Do you use multiple carbon caches? Did you configure CARBONLINK_HOSTS in local_settings.py?

**Comment by bemeyert** [comment]
> No, the problem in issue #629 is only for new metrics.

Ok

>  If metrics coming to cache it should be available immediately. If it's not - then your cache doesn't work. 

Hmm, not so ok.

> Do you use multiple carbon caches?

Yes, we use eight instances per server. All with their own whisper directory.

> Did you configure CARBONLINK_HOSTS in local_settings.py?

We did. We also configured `DATA_DIRS`:
```
CARBONLINK_HOSTS = [ '127.0.0.1:7001:1', '127.0.0.1:7003:3', '127.0.0.1:7002:2', '127.0.0.1:7005:5', '127.0.0.1:7004:4', '127.0.0.1:7007:7', '127.0.0.1:7006:6', '127.0.0.1:7008:8' ]
DATA_DIRS = [ '/data/carbon/1/whisper', '/data/carbon/3/whisper', '/data/carbon/2/whisper', '/data/carbon/5/whisper', '/data/carbon/4/whisper', '/data/carbon/7/whisper', '/data/carbon/6/whisper', '/data/carbon/8/whisper' ]
```

**Comment by deniszh** [comment]
How do you relay metrics to multiple caches? Through usual relay?
Carbon trying to guess which cache instance responsible for which metric, using hostname and instance. So, your `DESTINATIONS` and `CARBONLINK_HOSTS` should be in sync.
If you have 
```
CARBONLINK_HOSTS = [ '127.0.0.1:7001:1', '127.0.0.1:7003:3', '127.0.0.1:7002:2', '127.0.0.1:7005:5', '127.0.0.1:7004:4', '127.0.0.1:7007:7', '127.0.0.1:7006:6', '127.0.0.1:7008:8' ]
```
then you need to have
```
DESTINATIONS = '127.0.0.1:xxxx:1', '127.0.0.1:xxxx:3', '127.0.0.1:xxxx:2', '127.0.0.1:xxxx:5', '127.0.0.1:xxxx:4', '127.0.0.1:xxxx:7', '127.0.0.1:xxxx:6', '127.0.0.1:xxxx:8'
``` - in exactly same order.
Port numbers don't matter, but IP and instance name are.
And you can share whisper directories between instances usually, btw. But that's not mandatory, just more convenient.

**Comment by deniszh** [comment]
PS: if you're using different relay - things should be the same - order of  CARBONLINK_HOSTS should match order of relay destinations.

**Comment by bemeyert** [comment]
We use Carbon-C-Relay to shard the metrics. It runs on a different server than Carbon-Cache and Graphite-Web. Graphite-Web (one instance) is running on the same host as Carbon-Cache.

How does the order matter here?

We did not share the whisper directories so that we can scale out to more hosts should we get to that point.

**Comment by deniszh** [comment]
If you're using carbon-c-relay then you need to use normal carbon_ch sharding, and not anything else, because graphite-web do not support that.
So, if you have
```
cluster default
    carbon_ch replication 1
        10.x.x.a:yyyy:1
        10.x.x.a:yyyy:2
        ....   
        10.x.x.c:yyyy:7
        10.x.x.d:yyyy:8   
 ;
```
then you need to use 
```
DESTINATIONS = '10.x.x.a:zzzz:1, '10.x.x.a:zzzz:2', ... '10.x.x.c:xxxx:7', '10.x.x.d:xxxx:8'
```
Cache will work properly only if you're using `carbon_ch` cluster and same IPs and same instance names (1,2 .. 8 in your case) in same order.

**Comment by bemeyert** [comment]
We use the fnv1a_ch sharding algorithm (see blow for our config). Thus we are independent from the hostnames and can easily scale out by changing the host:port part but not the hash. The order is the same with Carbon-Cache/Graphite-Web. 

Since Graphite-Web doesn't even touch the Relays how is the relays configuration important? We made sure to use the same IPs and instance numbers in the configuration of Carbon-Cache and Graphite-Web.

Also our cluster works well. The only thing is that it takes a long time (avg 5 seconds) for a sent metric (not a new whisper file) to be available via Graphite-Web (see my first statement).
```
cluster replica_1
    fnv1a_ch
        10.77.12.33:2001=ba603c36342304ed77953f84ac4d357b
        10.77.12.33:2003=5dd63865534f84899c6e5594dba6749a
        10.77.12.33:2002=866a18b81f2dc4649517a1df13e26f28
        10.77.12.33:2005=f11f9d9077a15d598264bee2a656cffd
        10.77.12.33:2004=0e1d9361595839c7af0e23d2254a4709
        10.77.12.33:2007=ca9c1797fb2c571d1cf8e4b2b8456266
        10.77.12.33:2006=c6158d217912563dcd580c68bfbb1b71
        10.77.12.33:2008=8390790aacd57bc6b7e6e679b51cb582
    ;

cluster replica_2
    fnv1a_ch
        10.77.12.34:2001=ba603c36342304ed77953f84ac4d357b
        10.77.12.34:2003=5dd63865534f84899c6e5594dba6749a
        10.77.12.34:2002=866a18b81f2dc4649517a1df13e26f28
        10.77.12.34:2005=f11f9d9077a15d598264bee2a656cffd
        10.77.12.34:2004=0e1d9361595839c7af0e23d2254a4709
        10.77.12.34:2007=ca9c1797fb2c571d1cf8e4b2b8456266
        10.77.12.34:2006=c6158d217912563dcd580c68bfbb1b71
        10.77.12.34:2008=8390790aacd57bc6b7e6e679b51cb582
    ;

match *
    send to
        replica_1
        replica_2
    stop
    ;
```

**Comment by deniszh** [comment]
If you're not using `carbon_ch` hashing then graphite-web will always miss the cache and read data from disk, so, you'll get a delay. Sorry.
Or you need to switch to `carbon_ch` or implement `fnv1a_ch` in graphite-web. We have issue for that https://github.com/graphite-project/graphite-web/issues/1645
I can try to investigate that this week.

**Comment by bemeyert** [comment]
> If you're not using carbon_ch hashing then graphite-web will always miss the cache and read data from disk, so, you'll get a delay. Sorry.

OK, that I didn't know. Maybe this should be mentioned in the documentation. I thought that Graphite-Web would "just" work through the carbonlink list from beginning to it's end to find the specified metric. It seems that there is something else going on. So, several hosts in carbonlink can only work when they are hashed with an algorithm known to graphite?

> Or you need to switch to carbon_ch or implement fnv1a_ch in graphite-web. We have issue for that graphite-project/graphite-web#1645
>  I can try to investigate that this week.

Switching to carbon_ch is not an option for us. Since we would lose the possibility to easily scale out our cluster. For the moment we'll try to make Carbon-Cache sync it's queue faster to disk. But currently I can only think of using `naive` as CACHE_WRITE_STRATEGY.
You would make me really happy if you could look into the issue. :D
BTW: Would it help to raise the priority of this issue if my company would make a donation? If so I could talk to my boss and try to raise some money.

**Comment by deniszh** [comment]
>OK, that I didn't know. Maybe this should be mentioned in the documentation. 

Yes, you're right. I thought it was.

>I thought that Graphite-Web would "just" work through the carbonlink list from beginning to it's end to find the specified metric. It seems that there is something else going on. So, several hosts in carbonlink can only work when they are hashed with an algorithm known to graphite?

Indeed. When graphite-web looking for metric in a cache it calculates on which carbon-cache instance it should be, using the same caching algorithm as relay does. If metrics is not found in that instance - then it decides that metrics is not in cache.
We can try to implement optional retry logic but I think on reasonable pool sizes (4-8 caches) it will be very slow.

>You would make me really happy if you could look into the issue. :D
BTW: Would it help to raise the priority of this issue if my company would make a donation? If so I could talk to my boss and try to raise some money.

I'm just a volunteer here, with little spare time (sometimes) and python knowledge. :)
Will try to look it anyway.

**Comment by bemeyert** [comment]
@deniszh Thanks a lot for your spare time!

**Comment by bemeyert** [comment]
I think that everything is said here. Closed

**Comment by deniszh** [comment]
@bemeyert : I added FNV1a support in PR https://github.com/graphite-project/graphite-web/pull/1723
But it's for master branch, which is still not released yet. If you using 0.9.x - please inform me, I'll give you a specific patch for 0.9.x - just give me exact version of your graphite.

**Comment by bemeyert** [comment]
@deniszh This is absolutely fantastic! Many thanks. Currently we use the version 0.9.15 (1.el7) from EPEL

**Comment by deniszh** [comment]
Let me make a patch against 0.9.15, should not be a problem.

**Comment by deniszh** [comment]
I'm not sure should I create patch against 0.9.x... So, I created it against 0.9.15 from EPEL repo - https://gist.github.com/deniszh/efc4e52364554f7be77f9a44476fba83

Manual:
1. Download patch
2. Copy it to `/usr/lib/python2.6/site-packages/graphite`
3. Run `patch -p1 < graphite_0.9.15_epel_fnv1a.patch` - should apply clean
4. Fix your `/etc/graphite-web/local_settings.py`.
If you have ```
cluster replica_1
    fnv1a_ch
        10.77.12.33:2001=ba603c36342304ed77953f84ac4d357b
        10.77.12.33:2003=5dd63865534f84899c6e5594dba6749a
        10.77.12.33:2002=866a18b81f2dc4649517a1df13e26f28
...
    ;
``` in relay.conf, you should put this as CARBONLINK_HOSTS:
`CARBONLINK_HOSTS = ["10.77.12.33:xx01:ba603c36342304ed77953f84ac4d357b", "10.77.12.33:xx03:5dd63865534f84899c6e5594dba6749a", "10.77.12.33:xx02:866a18b81f2dc4649517a1df13e26f28", ....]`
I.e. in same order as you have in relay.conf. Of course, replace xx01, xx03, xx02 etc with real carbonlink ports.

**Comment by deniszh** [comment]
Ah, and another solution just come into my mind.
You can also try https://github.com/lomik/go-carbon as replace for carbon. It has only single carbon port for multiple writers, so, shouldn't miss cache too (it's hard to miss single port)

**Comment by sevenval-admins** [comment]
@deniszh A big thank-you for the great work. I have just patched our graphite-web hosts and the result is brilliant. Thanks. You see the great difference in the screenshot. It shows the time a icinga check needs for write a datapoint and request it from graphite-web.

One question now is, if it is possible to get the patches into the next version which will be published in the EPEL repo for CentOS7.

![screenshot_2016-10-20_11 06 58](https://cloud.githubusercontent.com/assets/13047464/19554595/a190799e-96b9-11e6-898f-7b61a949ed93.png)

**Comment by deniszh** [comment]
We're planning next release from master branch, which is including this patch too.
Right, @obfuscurity ?

**Comment by obfuscurity** [comment]
Correct.

**Comment by sevenval-admins** [comment]
Great. Thank you.
