### ISSUE TITLE
TokenBucket.timestamp not updating, leads to time.sleep(NEGATIVE_VALUE)

### ISSUE THREAD

**Issue by kwisatz** [graphite-project/carbon#604]
We have an odd issue on one of our graphite instances. Carbon-cache throws the following exception:

```
11/10/2016 21:15:08 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 158, in writeForever
    writeCachedDataPoints()
  File "/usr/lib/python2.7/dist-packages/carbon/writer.py", line 134, in writeCachedDataPoints
    UPDATE_BUCKET.drain(1, blocking=True)
  File "/usr/lib/python2.7/dist-packages/carbon/util.py", line 198, in drain
    sleep(self.timestamp + seconds_left - time())
exceptions.IOError: [Errno 22] Invalid argument
```

The reason for this is `sleep(self.timestamp + seconds_left - time())` eventually calling time.sleep() on a negative value, because on this instance, self.timestamp does not update.

Here's a ValueError I raised manually to inspect the values (sorry, noob python dev):

On the failing carbon-cache instance, it looks as if TokenBucket was initialized as a singleton:

```
exceptions.ValueError: timestamp is 1476213947.34, seconds left is 1.0, time is 1476214448.31
exceptions.ValueError: timestamp is 1476213947.34, seconds left is 1.0, time is 1476214449.33
[…]
```

However, on the working instance we can clearly see that self.timestamp does not stay the same:

```
exceptions.ValueError: timestamp is 1476214614.48, seconds left is 1.0, time is 1476214614.48
exceptions.ValueError: timestamp is 1476214615.5, seconds left is 1.0, time is 1476214615.5
[…]
```

In `util.py`, self.timestamp is set when the TokenBucket class is initialized:

```
class TokenBucket(object):
  '''This is a basic tokenbucket rate limiter implementation for use in
  enforcing various configurable rate limits'''
  def __init__(self, capacity, fill_rate):
    '''Capacity is the total number of tokens the bucket can hold, fill rate is
    the rate in tokens (or fractional tokens) to be added to the bucket per
    second.'''
    self.capacity = float(capacity)
    self._tokens = float(capacity)
    self.fill_rate = float(fill_rate)
    self.timestamp = time()

```

And in writer.py, the TokenBucket is initialized:

```
if settings.MAX_UPDATES_PER_SECOND != float('inf'):
  capacity = settings.MAX_UPDATES_PER_SECOND
  fill_rate = settings.MAX_UPDATES_PER_SECOND
  UPDATE_BUCKET = TokenBucket(capacity, fill_rate)
```

then at some point, its `drain` method is called in `writeCachedDataPoints`:

```
     # If we've got a rate limit configured lets makes sure we enforce it
      if UPDATE_BUCKET:
        UPDATE_BUCKET.drain(1, blocking=True)
```

So with my limited python skills, I don't really know where to go on from here. Since the code is the same on both instances, I don't this is a code-related bug, so could this be related to a configuration error? 

Both instances run graphite-carbon 0.9.15, twisted 14.0.2, python 2.7.9…

**Comment by iksaif** [comment]
Can you check if it is now fixed ?

**Comment by kwisatz** [comment]
Yes, that also prevents from passing negative values into sleep(). But have you figured out what makes self.timestamp update on one instance, but not the other?

**Comment by kwisatz** [comment]
I have, however, experienced serious memory problems (88% memory usage of 4Gb) since applying this change. I have now reverted back to sleep(0.1) by default (my previous workaround) to see if I can reproduce the memory issues.
