### ISSUE TITLE
CommittedPoints vs MetricsReceived gaps

### ISSUE THREAD

**Issue by genericgithubuser** [graphite-project/carbon#606]
I'm trying to understand potential causes or where I should look to understand a fairly consistent gap I'm seeing between my metricsReceived and committedPoints.  
Running 0.9.15, we average 6 million metricsReceived per minute on our cache nodes.  I see an average of 5 million committedPoints per minute.  There is consistently this gap.  The max queue size is set to 10 million, and is NOT hitting a queue full scenario where metrics are getting dropped since they peak at around 5 million metrics in the queue.  Traditionally I'm used to committedPoints and MetricsReceived getting to a point where they end up being close to equal after some time, but that is not the case here.  The gap has persisted for a few weeks now.  
carbon.agents.<server>.errors is always 0
carbon.agents.<server>.overflow is always 0
queue size bounces between ~300k-325k per cache node.  Even adding what's in the queue to the committedPoints still has a significant gap between metricsReceived.  

One theory though I have not been able to validate from the code if it is actually a reasonable explanation... In doing some captures, I see a lot of clients sending metrics at a higher rate than the storage schema has defined for them.  i.e. for our paths that just do 5 minute minimums, users are pushing data every minute, and for 1 minute retention many are doing every 15 seconds.  Just for load we'll look to get the various teams to adjust their submit rates, but since carbon will only write the 1 stat per window, is this a realistic explanation for the gap?  I am not sure if metricsReceived counts ALL metrics received or if it already adjusts to reflect the dropped metrics. If this is not a reasonable explanation of the gaps, are there any other counters that might shed some light on what's happening here?  From the logs and carbon metrics, I see nothing indicating drops/problems.  Additionally I do not see significant gaps in the graphs, which I would expect given the 1mil gap between these stats.

**Comment by obfuscurity** [comment]
Yes, that sounds like a reasonable explanation, or that maybe multiple clients are sending the same metric.

**Comment by genericgithubuser** [comment]
Great, thanks for the response Jason.
