### ISSUE TITLE
integrating with a node app

### ISSUE THREAD

**Issue by shrynx** [graphite-project/carbon#609]
This is not an issue but i am looking for documentation. I want to integrate graphite with a node. The metric data is provided by [sitespeed.io](https://www.sitespeed.io/). I need a way to consume graphite data through some sort of rest apis. So that i can use it through a node app.

**Comment by SEJeff** [comment]
Please read [the documentation for the rest api](graphite.readthedocs.io/en/latest/render_api.html) if possible before opening issues:
