### ISSUE TITLE
carbon.util.TokenBucket.drain() always computes 1 second for `seconds_left`

### ISSUE THREAD

**Issue by 56quarters** [graphite-project/carbon#610]
Hi,

In the class `carbon.util.TokenBucket`, when the `.drain(cost, blocking=True)` method is called, it seems like the value computed for `seconds_left` is incorrect. 

The code in question is:

```python
tokens_needed = cost - self._tokens
seconds_per_token = 1 / self.fill_rate
seconds_left = seconds_per_token * self.fill_rate
sleep(self.timestamp + seconds_left - time())
```

Link: https://github.com/graphite-project/carbon/blob/master/lib/carbon/util.py#L232

`(1 / self.fill_rate) * self.fill_rate` will always be `1`. Thus `sleep()` is always called as `sleep(self.timestamp + 1 - time())`. This doesn't seem like it is the desired behavior. The `tokens_needed` variable is also unused. 

Seems like maybe the code was supposed to be:

```python
tokens_needed = cost - self._tokens
seconds_per_token = 1 / self.fill_rate
seconds_left = seconds_per_token * tokens_needed
sleep(self.timestamp + seconds_left - time())
```

Thanks.

**Comment by deniszh** [comment]
Hm. I'm a not twisted expert but looks plausible. Opinions? /cc @graphite-project/committers

**Comment by iksaif** [comment]
Can you check if it is now fixed ?

**Comment by 56quarters** [comment]
Looks correct to me. Thanks!
