### ISSUE TITLE
relay-rules aggregation

### ISSUE THREAD

**Issue by ramen74** [graphite-project/carbon#617]
We are trying to send metrics from carbon-relays -> carbon-aggregators via relay-method constistent-hashing-aggregators. 
We have tried multiple configurations but have only been able to send metrics to all aggregators OR have unaggregated metrics sent to separate aggregators, thus causing aggregation to fail. 
Is there documentation/examples ( aggregagtion-rules.conf, carbon.conf, relay-rules.conf ) for how to set this configuration up or am I misunderstanding the aggregation method?

**Comment by deniszh** [comment]
IIRC constistent-hashing-aggregators doing exactly that - sending metrics to all aggregators.
If you do not want it - just use relay-rules.conf to point metric to specific aggregators, then you do not need onstistent-hashing-aggregators route at all.

**Comment by obfuscurity** [comment]
I think you're referring to `aggregated-consistent-hashing`? If so, it should indeed map metrics to a consistent downstream aggregator. What version of carbon are you running?

**Comment by ramen74** [comment]
Yes I was trying aggregated-consistent-hashing. 0.9.15.  Thanks!

**Comment by ramen74** [comment]
If there is any further follow-up here it would be appreciated.
