### ISSUE TITLE
Caches receiving mangled metrics from relays

### ISSUE THREAD

**Issue by howdoicomputer** [graphite-project/carbon#618]
So I have this cluster that I'm playing with and everything is talking to each other... more or less. I have two relays, three caches, one 'solo' graphite web, one grafana, etc. Everything is on `0.9.15`.

So I have haggar sending metrics to a relay but when they hit the caches... I get something like this:

```
2017-01-06_15:16:01.55760 06/01/2017 15:16:01 :: [listener] invalid line (Uhaggar.agent.26.metrics.7533GA@G@aq
                                                                                                              Uhaggar.agent.26.metrics.7539GA@G@\q
                                                                                                                                                  Uhaggar.agenUhaggar.agent.26.metrics.7552GA@G@qUhaggar.agent.26.metrics.7557GA@G@qUhaggar.agent.26.metrics.7563GA@G@b@qUhaggar.agent.26.metrics.7573GA@G@`qUhaggar.agent.26

...

2017-01-06_15:16:01.60592 06/01/2017 15:16:01 :: [listener] MetricLineReceiver connection with 172.23.34.93:48674 lost: Connection to the other side was lostin a non-clean fashion.
```

I couldn't find anything like this through googling and I'm not sure what I'm doing wrong.

**Comment by howdoicomputer** [comment]
Might be MTU size for the caches.

**Comment by obfuscurity** [comment]
That's definitely a weird one, I don't recall having seen that before. When
you say you're running "two relays, three caches" is that all on the same
box or different nodes?

**Comment by howdoicomputer** [comment]
@obfuscurity All on different nodes.

```
2017-01-06_16:38:21.48069 06/01/2017 16:38:21 :: [listener] invalid line (]q(Uhaggar.agent.2.metrics.2GAG@0qUhaggar.agent.2.metrics.11GAG@qUhaggar.agent.2.metrics.13GAG@8qUhaggar.agent.2.metrics.18GAG@qUhaggar.agent.2.metrics.19GAG@fqUhaggar.agent.2.metrics.21GAG@}qUhaggar.a`gent.2.metrics.27GAG@p Uhaggar.agent.2.metrics.35GAG@~0q Uhaggar.agent.2.metrics.39GAG@q) received from client 172.23.34.93:52185, ignoring
```

Really weird stuff.

**Comment by howdoicomputer** [comment]
Anything weird here? Config for the cache.

```
ubuntu@ip-172-23-35-18:/opt/graphite/conf$ cat carbon.conf
# This file is managed by Chef, your changes *will* be overwritten!

[cache]
ENABLE_LOGROTATION = True
USER = graphite
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 500
MAX_CREATES_PER_MINUTE = 50
LINE_RECEIVER_INTERFACE = 0.0.0.0
ENABLE_UDP_LISTENER = True
CACHE_WRITE_STRATEGY = sorted
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
WHISPER_AUTOFLUSH = False
LOCAL_DATA_DIR = /mnt/graphite_storage/whisper/

[cache:a]
CACHE_QUERY_PORT = 7002
LINE_RECEIVER_PORT = 2003
UDP_RECEIVER_PORT = 2003
PICKLE_RECEIVER_PORT = 2004

[cache:b]
CACHE_QUERY_PORT = 7003
LINE_RECEIVER_PORT = 2005
UDP_RECEIVER_PORT = 2005
PICKLE_RECEIVER_PORT = 2006
```

And for the relays

```
ubuntu@ip-172-23-34-93:/opt/graphite/conf$ cat carbon.conf
# This file is managed by Chef, your changes *will* be overwritten!

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 12104
RELAY_METHOD = consistent-hashing
DESTINATIONS = 172.23.33.65:2003:a, 172.23.33.65:2005:b, 172.23.33.26:2003:a, 172.23.33.26:2005:b, 172.23.35.18:2003:a, 172.23.35.18:2005:b

```

**Comment by obfuscurity** [comment]
Have you tried running a relay on the same host as the caches, to handle fanout? I personally never run "just caches" on any scaled-up Carbon node. It may not fix your issue but it might be worth a try.

I've [benchmarked Haggar](http://obfuscurity.com/2016/08/Benchmarking-Carbon-and-Whisper-on-AWS) at some pretty significant scale and never encountered any path corruption like you're seeing.

**Comment by howdoicomputer** [comment]
I don't think the problem is haggar, specifically. Just... something is going on between relays and caches and it's confusing me. I'll consolidate the relays and caches and get back to you. Thanks for responding to me ticket! Very appreciated!

**Comment by obfuscurity** [comment]
Sure thing, looking forward to hearing your progress.

**Comment by howdoicomputer** [comment]
@obfuscurity Now that everything is on one box, I'm seeing the same problem. All within AWS and within a VPC. So nothing is really going on between the relays and the caches.

```
G@rUaggar.agent.0.metrics.4363GAU<G@rUaggar.agent.0.metrics.4364GAU<G@prUaggar.agent.0.metrics.4366GAU<G@rUaggar.agent.0.metrics.4367GAU<G@vrUaggar.agent.0.metrics.4369GAU<G@@rUaggar.agent.0.metrics.4371GAU<G@{0Uaggar.agent.0.metrics.4373GAU<G@Gr    Uaggar.agent.0.metrics.4374GAU<G@Xr) received from client 127.0.0.1:59914, ignoring
2017-01-10_21:41:12.00757 10/01/2017 21:41:12 :: [listener] MetricLineReceiver connection with 127.0.0.1:59916 established
```

**Comment by howdoicomputer** [comment]
So, running haggar with `-carbon="localhost:port"` I still get path corruption. This is driving me nuts.

**Comment by howdoicomputer** [comment]
So if I set ten agents to send out ten metrics at a time things are fine.

**Comment by obfuscurity** [comment]
I empathize, I really do. But nobody else has reported corruption issues like this so I'm obliged to think it has something to do with your systems and/or network. I'm unable to reproduce this at all.

**Comment by howdoicomputer** [comment]
@obfuscurity Hm, I actually don't think it's anything system or network bound because I just did something I should have started with.

I used synthesize to stand up a single node and... it worked fine. What I'm using now is sous-chef/graphite and I think it's just fubaring everything. What I'll probably do is just ditch that cookbook and try to write something more lightweight

**Comment by obfuscurity** [comment]
Weird. Still, I'm glad you were able to narrow it down to a variable. Please let us know if you uncover anything more "incriminating".

**Comment by howdoicomputer** [comment]
@obfuscurity Sure. I'll poke around. If you can think of anything that would mangle incoming metrics like that then let me know. I have Terraform and Chef setting up clusters and it's super slick but... stuff is weird.

**Comment by howdoicomputer** [comment]
Oh, and Synthesize just sets up a cache - there isn't a relay involved. Hmmmmmm.

**Comment by howdoicomputer** [comment]
@obfuscurity One last one before I conk out. I threw carbon-relay-ng onto my Chef spawned cache node and *boom* it just works. So, uh, I dunno.
