### ISSUE TITLE
After whisper-resize of current metrics, wsp files size has increased.

### ISSUE THREAD

**Issue by gargnisha1605** [graphite-project/carbon#622]
Hi I used the following command to change the retention policies of my existing metrics:
find ./ -type f -name '*.wsp' -exec whisper-resize {} 10s:6h ;

Before changing the retention policies:
find ./ -type f -name 'count.wsp' -exec whisper-info {} ;
maxRetention: 86400
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 17308

Archive 0
retention: 86400
secondsPerPoint: 60
points: 1440
size: 17280
offset: 28

After changing the retention policy from 60s:1d to 10s:6h, my file size has increased.
find ./ -type f -name 'count.wsp' -exec whisper-info {} ;
maxRetention: 21600
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 25948

Archive 0
retention: 21600
secondsPerPoint: 10
points: 2160
size: 25920
offset: 28

I have changed the retention policy to clear some space from graphite server, but wsp file size has increased after whisper-resize. Can any body guide my how to clean whisper data.

**Comment by obfuscurity** [comment]
There's nothing to "clean up". Your new retention stores more datapoints (2160 vs 1440), so it's only natural that the file will be larger. Note that the files will not grow any _larger_ than they begin with (unless you specify sparse files, which you did not).
