### ISSUE TITLE
Mixing aggregator and cache

### ISSUE THREAD

**Issue by iksaif** [graphite-project/carbon#626]
It looks like in various setups it would be better to have the aggregator and caches running as a single process, this makes the setup easier and avoid loosing CPU and network (most of the time spent by the aggregator is spent deserializing and re-serializing).

Anybody tried that already ? What would be the prefered way ? A new carbon-aggregator-cache command ?

**Comment by deniszh** [comment]
I think it's better to merge it with relay. IMO aggregator is the weakest link in Graphite infrastructure.  Even alternative implementations like relay-ng or carbon-c-relay have own drawbacks.

**Comment by iksaif** [comment]
You need to now which aggregator to talk to most of the time (this is why we have aggregated-consitent-hashing). Since clients are usually talking directly to relays that wouldn't really work (unless they are all using TCP all the time, which also ins't really practical).

`how are you gonna aggregate same data on different caches then`: simply use the replication factor ? If you want true redundancy you also need to set the RF to 2 from your relays to your aggregators in case one of them dies.

If I could, I would just get rid of the aggregators in our infrastructure .. but backward compatibility and all that.

I'm going to re-write part of the aggregation part based on what we learned from biggraphite, but I would also like to get rid of the network/pickle overhead that having different processes creates, thus my proposal.

An alternative proposal if to add a way to configure pipelines in the config file (which would basically let you do whatever you want :) )

**Comment by deniszh** [comment]
I'm totally fine with merging aggregator with cache if it will work. Pipelines are much more interesting but much harder to implement.

**Comment by iksaif** [comment]
I'm pretty sure this has been merged
