### ISSUE TITLE
Feature Request: SSL support for AMQP connector

### ISSUE THREAD

**Issue by mcbsdEU** [graphite-project/carbon#630]
Hi,

I can't see any option to specify SSL parameters when Carbon is configured to be subscribed to RabbitMQ.
Is it hidden somewhere or it is considered in feature?
Only option so far seems to be stunnel.

Thanks a lot

**Comment by deniszh** [comment]
Yes, stunnel is only viable option for SSL-backed AMQP for now.

**Comment by mcbsdEU** [comment]
Ok, thanks for confirmation.
