### ISSUE TITLE
Problem with cabon-cache to disk destage

### ISSUE THREAD

**Issue by munokar** [graphite-project/carbon#632]
Hello,

I want to use graphite together with grafana to visualize storage system performance metrics.
Since these storage systems are having a lot of volumes with a lot of metrics I have a very high amount of datapoints I want to write to the carbon-cache.
Approx. 25000 volumes x 20 metrics each minute. Currently I have 387148 whipser files in the filesystem...

The script I have written to write data to carbon-cache seams to work but I run into issues running it more frequently.
In the past I had configured MAX_CACHE_SIZE to infinite which brought my server to swapping after the carbon-cache process had 4 GB memory allocated. Now I limited MAX_CACHE_SIZE to 12000000 which will allocate approx. 1.6 GB of memory.
If I run the script that inserts the data into carbon 1 or 2 times approx. 900 MB will be allocated. Running it another 2 - 3 times will trigger the following message in the console.log.

```
28/02/2017 15:22:23 :: MetricCache is full: self.size=12000001
28/02/2017 15:22:23 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 78, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/usr/lib/python2.6/site-packages/carbon/protocols.py", line 64, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/usr/lib/python2.6/site-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/carbon/cache.py", line 48, in store
    events.cacheFull()
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined
```

I have found another issue about the "global name 'carbon' is not defined" stuff so perhaps I need a patch here but this is not the issues.
My issue is that the cache is not been given free again! It looks like carbon-cache is not really destaging data to the disk...

On a iostat I can see that the service times of the disk where the whisper files are located are fine and in generall he should be able to perform much more write IOPS.
I allready "played" with diffrent parameters. Currently carbon-cache is configured with the following parameters:

```
MAX_CACHE_SIZE = 12000000
MAX_UPDATES_PER_SECOND = 5000
MAX_CREATES_PER_MINUTE = 10000
LOG_LISTENER_CONNECTIONS = True
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = True
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = True
WHISPER_FALLOCATE_CREATE = True
```

I allready tried all diffrent cache strategies in combination with AUTOFLUSH true/false.

I have never seen more than 1000 IOPS been processed to the disk.

Below an output from a IOSTAT where dm-6 is the disk where the whisper files are created.
Currently this is just a single disk but it should be able to perform better in my optinion.

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda              23.00    20.00   87.00  111.00     0.45     0.39     8.73     1.92    9.20    3.07   14.00   4.48  88.80
dm-6              0.00     0.00  109.00  103.00     0.45     0.40     8.19     1.95    8.70    3.43   14.28   4.19  88.90

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00    22.22   95.96  143.43     0.41     0.50     7.73     2.11    8.90    2.64   13.09   4.07  97.37
dm-6              0.00     0.00   95.96  126.26     0.41     0.49     8.29     2.03    9.20    2.64   14.18   4.38  97.27

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00    17.82  103.96  160.40     0.45     0.53     7.61     1.98    7.69    3.21   10.60   3.64  96.24
dm-6              0.00     0.00  103.96  134.65     0.45     0.53     8.37     1.86    8.00    3.22   11.70   4.03  96.24

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00    21.21   71.72  111.11     0.30     0.40     7.78     2.14   11.87    3.45   17.30   5.36  98.08
dm-6              0.00     0.00   72.73   98.99     0.30     0.39     8.19     2.05   12.08    3.40   18.46   5.72  98.18
```

What would be strategies for futher investigation of that issue?
Even if I don't import new data for and hour or two the amount of used memory doesn't decrease - I know that this doesn't neccessary mean that nothing got destage but how can I check how much and how fast data is destaged to disk?

As an update:

![destage_issue](https://cloud.githubusercontent.com/assets/26091678/23414897/c7242378-fddd-11e6-9b5b-9ca144a76a97.JPG)

The picture show that I really have an issue with the destage from cache to disk.
Amount of received points is far higher than amount of commited. Do I interpret this stats corrent?

It would really be nice if you could give me some hints.

Thanks in advance.

Regards
Timo

**Comment by deniszh** [comment]
"global name 'carbon' is not defined" issue is fixed in https://github.com/graphite-project/carbon/pull/486 - it's a small fix.

How many carbon cache instances do you have?

**Comment by munokar** [comment]
Hi,

thanks for the feedback.
Currently we are only working with one carbon cache instance.

We have accelerated our disk backend which improved the situation a lot.
We are now able to perform up to  615000 commits per seconds.

See picture:

![improvement](https://cloud.githubusercontent.com/assets/26091678/23604636/d57c3b9c-0259-11e7-97c1-885e65595cd4.JPG)

Since we are importing the data every 30 Minutes we might run into out of memory issue if the cache is not destaged after end of an import before the next import starts...

Is there any possibility to have multiple processes for destage of cache to disk?

Regards
Timo

**Comment by deniszh** [comment]
Hi Timo,
Having faster disk is always better, agreed. But you can try to add multiple carbon-caches too.
You need to add another section of variables to carbon cache and install some relay in front of it, like
```
[cache]
MAX_CACHE_SIZE = 12000000
MAX_UPDATES_PER_SECOND = 5000
MAX_CREATES_PER_MINUTE = 10000
LOG_LISTENER_CONNECTIONS = True
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = True
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = True
WHISPER_FALLOCATE_CREATE = True
...
[cache:0]
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7012
[cache:1]
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_PORT = 2024
CACHE_QUERY_PORT = 7022

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
LOG_LISTENER_CONNECTIONS = True
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2014,127.0.0.1:2024
MAX_DATAPOINTS_PER_MESSAGE = 500
MAX_QUEUE_SIZE = 10000
USE_FLOW_CONTROL = True
```
I can help you if you will provide your carbon.conf and local_settings.py (with comments stripped).

**Comment by munokar** [comment]
Hi,

this sound like a good way to scale up our environment.
So there is a hash generated by the relay to decide which cache to use.
What is getting hashed there with setting:

`RELAY_METHOD = consistent-hashing`

Is it the metric?

Regards
Timo

**Comment by deniszh** [comment]
Yes, metric name.
