### ISSUE TITLE
Pip packages installing to dist

### ISSUE THREAD

**Issue by sandstheman** [graphite-project/carbon#645]
Installing the 1.0.0 using pip install package_name==1.0.0 and the packages are installing under:
/usr/lib/python2.7/dist-packages

can see the opt/graphite..... structure is created under there, was this behaviour changed for a reason?

Minor niggle, and easily fixed in my deployment scripts using the updated instructions in the docs.

**Comment by deniszh** [comment]
@sandstheman : Make sure that you are following [installation documentation]:(https://graphite.readthedocs.io/en/latest/install-pip.html#installing-in-the-default-location).
