### ISSUE TITLE
Trying understand wrong aggregation

### ISSUE THREAD

**Issue by gtonello** [graphite-project/carbon#648]
Hello guys,

I'm using `carbon-aggregator` to receive my metrics with some basic rules. One of these rules do a simple sum of a metric. i.e.:
`<app>.<location>.all.value (10) = sum <app>.<location>.\d{4}_domain.value`
In general, it's a constant value, think about `node01 = 1000`, `node02 = 2000`, `node03 = 1000`.
So, the sum of my sample should be 4000. (am I right, yes?)
But the value that is being writing in whisper is something different, 2000 or 3000.. depends on location.

I'm trying investigate why aggregator is writing a different value, I'm not sure if I'm forgetting. But my question is if there is another configuration that I should looking for?
Someone had an issue like that with aggregator before?

**Comment by deniszh** [comment]
Hello @gtonello ,
Sorry, but looks like not many people still using aggregator now.

**Comment by stan-sack** [comment]
@gtonello did you solve this issue?
