### ISSUE TITLE
"send_queue is full"    之后出现 Send.OSError   Connection reset by peer 错误

### ISSUE THREAD

**Issue by vagabond1132** [graphite-project/carbon#650]
![qq20170428-0](https://cloud.githubusercontent.com/assets/7650878/25518361/05ac3f06-2c26-11e7-87c1-f4aa4d011372.png)

**Comment by vagabond1132** [comment]
这个问题是 因为 python  与 ubutnu 冲突引起吗？

**Comment by vagabond1132** [comment]
@alex @smn

**Comment by deniszh** [comment]
Hello @vagabond1132 ,
I'm sorry, but it's not clear from the screenshot above what your problem is, and why do you blaming carbon for it?

**Comment by vagabond1132** [comment]
Server 程序是python编写的   我使用客户端与之通讯的时候，发现不能接收到服务端数据， 查看服务端log， 发现 send_queue is full , 并且 Send.OSError   , 并不知道到底发生了什么？ 请求帮助， thanks

**Comment by vagabond1132** [comment]
@deniszh  hi,  Server 程序是python编写的 我使用客户端与之通讯的时候，发现不能接收到服务端数据， 查看服务端log， 发现 send_queue is full , 并且 Send.OSError , 并不知道到底发生了什么？ 请求帮助， thanks

**Comment by deniszh** [comment]
Hi @vagabond1132,
If you have this error in carbon - upgrade to Graphite 0.9.16 or 1.0.1
See https://github.com/graphite-project/carbon/issues/505
But as far as I see this message is not from carbon, but from some other program, it's just similar error message.

**Comment by vagabond1132** [comment]
yes,   it`s  just similar error message  but I don't know how to solve ;  What reason caused this situation ; so  Please help  thank you
