### ISSUE TITLE
ImportError: No module named carbon.util

### ISSUE THREAD

**Issue by mizhdi** [graphite-project/carbon#667]
When I trying to run in a virtualenv：
carbon-cache.py start

how to fix?

**Comment by deniszh** [comment]
Something is wrong with your installation.
How do you installing it?
Try e.g. this:
```
virtualenv /opt/graphite
source /opt/graphite/bin/activate
cd ~ && git clone  https://github.com/graphite-project/carbon.git
cd carbon && pip install -r requirements.txt
python setup.py install --prefix=/opt/graphite --install-lib=/opt/graphite/lib
cd /opt/graphite/
cp conf/carbon.conf.example conf/carbon.conf
cp conf/storage-schemas.conf.example conf/storage-schemas.conf
./bin/carbon-cache.py start
```

**Comment by mizhdi** [comment]
It works. Thank you @ deniszh

**Comment by ybizeul** [comment]
Same problem here, except I'm not using virtualenv.
It seems to be related to the recent changes in https://github.com/graphite-project/carbon/commit/7516cf148c5d75c2cd066c32ad95f5d617cca2f0#diff-2eeaed663bd0d25b7e608891384b7298

Trying to install with both `--prefix=/opt/graphite --install-lib=/opt/graphite/lib` solved the problem

**Comment by deniszh** [comment]
TBH I also suspected that change, but have no idea how it can be related.... Any ideas, @piotr1212 ?

**Comment by deniszh** [comment]
Ah, @ybizeul is right, it's because of https://github.com/graphite-project/carbon/commit/7516cf148c5d75c2cd066c32ad95f5d617cca2f0#commitcomment-22693426
Looks like we should restore this logic.

**Comment by deniszh** [comment]
Or it has clashed with python3, @piotr1212 ?

**Comment by piotr1212** [comment]
Yes I removed it. The code wasn't py3 compatible, seemed like a big hack,
broke installing in other prefix than opt. Overriding it with the env
variable was not intuitive. Many new users had trouble finding out to set
the correct Python path. Opt isn't the default for python modules.
I didn't realize this would break users installations, thought it was some
old strange leftover. Will try to restore it this evening.

Op do 22 jun. 2017 09:46 schreef Denis Zhdanov <notifications@github.com>:

**Comment by piotr1212** [comment]
https://github.com/graphite-project/carbon/issues/668 restores the original behaviour with installing to /opt/graphite by default.

@mizhdi @ybizeul : Were you running clean installation or upgrading older ones?

**Comment by ybizeul** [comment]
It was on a clean installtion
