### ISSUE TITLE
exception logging for carbonlink failures

### ISSUE THREAD

**Issue by rpk113** [graphite-project/carbon#675]
I'm receiving the following error in the exception.log, not sure what do with it...

2017-07-26,10:21:44.046 :: Failed CarbonLink query 'PRODUCTION.network1.traffic.mbitsec'
Traceback (most recent call last):
  File "/graphite/common/webapp/graphite/readers.py", line 211, in fetch
    cached_datapoints = CarbonLink().query(self.real_metric_path)
AttributeError: 'NoneType' object has no attribute 'query'

**Comment by deniszh** [comment]
It's for graphite-web, not carbon. 
Do you have CARBONLINK_HOSTS defined in local_settings.py ?
if not then it will use default - `CARBONLINK_HOSTS = ["127.0.0.1:7002"]` - then you need to have carbon installed on same server and listening port 7002.

**Comment by piotr1212** [comment]
closing due to no response, reopen if needed
