### ISSUE TITLE
rewrite-rule is being applied twice, resulting in double replacements

### ISSUE THREAD

**Issue by kalebwalton** [graphite-project/carbon#676]
Example rewrite-rules.conf:

```
[post]
^(.*) = newprefix.\1
```

Results in the following metric: _newprefix.newprefix.mymetric_

I see that in service.py a pipeline is being created that applies rewrite:pre and rewrite:post rules, and it also includes an 'aggregate' pipe. The aggregate processor in lib/carbon/aggregator/processor.py also performs pre/post rewrites, so it's doubling them up. Submitting a PR to remove the rewrites from processor.py, although I am unsure if that's the most accurate solution.

**Comment by deniszh** [comment]
My knowledge of rewriter is scarce, I'm not even sure does it a bug or not.

**Comment by ganiserb** [comment]
This issue is also happening to me with the only rule:

```
[pre]
^(.+) = somePrefix.someOther.\1
```

The whisper files created result in something like this:
/var/lib/graphite/whisper/somePrefix/someOther/somePrefix/someOther/app1/...
