### ISSUE TITLE
Carbon Cache to 0

### ISSUE THREAD

**Issue by ttftw** [graphite-project/carbon#678]
![image](https://user-images.githubusercontent.com/22228023/29136297-65d0a098-7d02-11e7-9f70-7da6c60b9244.png)

![image](https://user-images.githubusercontent.com/22228023/29136504-0f5d46ac-7d03-11e7-8510-16f6809fc57e.png)

Earlier today, I noticed this happen...and a little later someones metrics started to hang...where it would update a gauge, then on the next tick, revert to old value.  I restarted graphite and it fixed the issue, but a few hours later, the cache went to 0 again.  It's still showing cache queries metrics, and the other metrics are not stalling like before.  

Is this typical?

**Comment by Meowbeast** [comment]
Some stats die, and when I restart, they start right back up.

![image](https://user-images.githubusercontent.com/22228023/29141555-4d39bcd8-7d14-11e7-90ff-d45e96e1aa55.png)

**Comment by deniszh** [comment]
Do you have something in the logs?
It's not really clear what symptoms of the problem are?

**Comment by Meowbeast** [comment]
I've tried looking through them and didn't see anything that stuck out. 

Where would I start to diagnose? Twice now I've had metrics freeze where I've had to restart and things will start flowing in again. It's like the cache is freezing or something I'm just not sure where to check.

**Comment by piotr1212** [comment]
You could check cpu usage, disk IO usage, open file descriptors, memory usage, cache size, attach strace to the process or gdb with python extensions to get a backtrace. os logs, etc. Which python version are you running? I've experienced issues with garbage collection freezing carbon on python 2.6. This was with huge cachesized though (> 300.000 unique metrics with >100 points per metric in one carbon-cache)

**Comment by Meowbeast** [comment]
The cache size is what I'm saying is wrong. It dropped to zero before they would start to freeze. Though they seemed to keep coming in for a bit but then they hang. The gauge goes up like it received an update, but on the next tick it goes back to the original value and it will go back down until the next event it receives, it will go up, then back down again next tick. I can attach a screen shot here in a bit. It looks like a flat line with peaks when this gauge should be an increasing slope. 

I've looked through what logs I can find and haven't noticed anything. I also have metrics of the server from netdata and nothing stands out. All the I/O, mem, cpu, etc seem typical. 

I'll check python when I get back, but there's only about 9k updates happening at a time. 

Sorry I'm a little short, I'm on mobile. :)

**Comment by piotr1212** [comment]
I have no clue. Maybe some issue with actually receiving the metrics over the network, you could check open sockets, network stats, tcpdump, etc to verify....

**Comment by piotr1212** [comment]
ps. might help if you specify which Graphite version, Python version, OS type/version, number of metrics, type of setup (number of caches/relays), etc.

**Comment by Meowbeast** [comment]
I'll do some digging around a bit more, I just don't know what might cause the cache to drop to zero.  It seems like it's related.  Not sure if that is normal behavior when we have 8-9k events coming in.

![image](https://user-images.githubusercontent.com/22228023/29151515-4a831038-7d47-11e7-8cd7-dcc6e57419a2.png)

**Comment by eliten00b** [comment]
I have a similar issue with gauges.

For example:
Query inmemory value from statsd: `echo "gauges" | nc 127.1 8135` show me `'maxwell.row.meter.count': 52271942,` (52M)

If I check the value with Grafana I get this value, after 10 seconds I refresh and the value jump up to `410M` where it was same days ago. Than I refresh again after 10 seconds and it `52M` again for the recent value. But it goes always back to `410M`. I have a flat line with `410M` all time now.

I'm using Docker with alpine:3.5, Graphite 1.0.2, Whisper 1.0.2, Carbon 1.0.2, Python 2.7.13

![bildschirmfoto 2017-09-06 um 12 59 12](https://user-images.githubusercontent.com/1175070/30108652-63946636-9303-11e7-9ee1-88c906c7a11c.png)
> Last 7 days, it was working fine, most recent value `410M`

![bildschirmfoto 2017-09-06 um 13 03 23](https://user-images.githubusercontent.com/1175070/30108757-d622c436-9303-11e7-8ef0-65d81eb6a1f0.png)
> Last 7 days, recent value lower (Grafana cant display the value that low because of auto avarage)

![bildschirmfoto 2017-09-06 um 13 00 24](https://user-images.githubusercontent.com/1175070/30108651-63682062-9303-11e7-9e93-0ecb9700d189.png)
> Last 30 min, recent value `52M`

**Comment by piotr1212** [comment]
In the second image the number of metrics received goes down. If the number of metrics received is less than the system can handle (and is lower than MAX_UPDATES) the cache will go to zero, points per update goes down to 1. This seems perfectly fine.

Question for you would be to find out why the number of metrics received drops from 9k to 6k.

If you still need help please give some more information about your setup, eg: number of caches, relays, python version, os version, graphite version, how the metrics are sent, wether you use statsd or not, etc.
