### ISSUE TITLE
How to manage carbon-relay's pid

### ISSUE THREAD

**Issue by bkez322** [graphite-project/carbon#680]
I'm having trouble understanding how one is expected to manage the pid for carbon-relay. The carbon config file allows one to specify PID_DIR, but only for the carbon-cache process. As far as I can tell, no pidfile for carbon-relay is being created anywhere, and `echo $!` does not return the correct pid. What is the correct way to keep track of carbon-relay's pid?

In the meantime I'm extracting the pid from the output of the "status" command, but I would hope there's a better way to do this.

**Comment by deniszh** [comment]
TBH I'm not using build-in pid management a lot. IIRC it's standart `twistd` pid management - you can use `--pidfile` cli parameter to override default, but usually I'm using `supervisord` or `upstart` for process management.
