### ISSUE TITLE
Error in webapp/error.log

### ISSUE THREAD

**Issue by margozzi** [graphite-project/carbon#684]
I saw the below error in my webapp.log. I am unfamiliar with graphite. I am new to a project using it.
Data is not being populated into the charts. Running on Centos 7.3. Is this a known issue?

mv: cannot move â€˜/opt/graphite/storage/.index.tmpâ€™ to â€˜/opt/graphite/storage/indexâ€™mv: : No such file or directorycannot stat â€˜/opt/graphite/storage/.index.tmpâ€™
: No such file or directory

**Comment by deniszh** [comment]
You can safely ignore this error

**Comment by margozzi** [comment]
Seems like maybe it was trying to use single quote and was encoded wrongly?
https://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of
