### ISSUE TITLE
Cannot Start Carbon-cache

### ISSUE THREAD

**Issue by hussain-s** [graphite-project/carbon#688]
twistd 11.1.0 (/bin/python 2.7.5) starting up.
12/10/2017 13:36:42 :: reactor class: twisted.internet.epollreactor.EPollReactor.
12/10/2017 13:36:42 :: ServerFactory starting on 7002
12/10/2017 13:36:42 :: Starting factory <twisted.internet.protocol.ServerFactory instance at 0x25ceb48>
12/10/2017 13:36:42 :: Installing SIG_IGN for SIGHUP
12/10/2017 13:36:42 :: Traceback (most recent call last):
12/10/2017 13:36:42 ::   File "./carbon-cache.py", line 32, in <module>
12/10/2017 13:36:42 ::     run_twistd_plugin(__file__)
12/10/2017 13:36:42 ::   File "/opt/graphite/lib/carbon/util.py", line 108, in run_twistd_plugin
12/10/2017 13:36:42 ::     runApp(config)
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
12/10/2017 13:36:42 ::     _SomeApplicationRunner(config).run()
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 390, in run
12/10/2017 13:36:42 ::     self.postApplication()
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 208, in postApplication
12/10/2017 13:36:42 ::     self.startApplication(self.application)
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 326, in startApplication
12/10/2017 13:36:42 ::     app.startApplication(application, not self.config['no_save'])
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 674, in startApplication
12/10/2017 13:36:42 ::     service.IService(application).startService()
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 282, in startService
12/10/2017 13:36:42 ::     service.startService()
12/10/2017 13:36:42 ::   File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 282, in startService
12/10/2017 13:36:42 ::     service.startService()
12/10/2017 13:36:42 ::   File "/opt/graphite/lib/carbon/protocols.py", line 61, in startService
12/10/2017 13:36:42 ::     self._port = reactor.adoptStreamPort(
12/10/2017 13:36:42 :: AttributeError: 'EPollReactor' object has no attribute 'adoptStreamPort'

**Comment by DanCech** [comment]
You need twisted >= 13.2.0
