### ISSUE TITLE
Whitelist/Blacklist seems to be ignored

### ISSUE THREAD

**Issue by mcbsdEU** [graphite-project/carbon#689]
Hi,

I am trying to implement trivial functionality like whitelisting.
First I found some inconsistency (maybe just from my point of view):
-whitelist file is expected to be in "WHITELISTS_DIR" (according carbon.conf)
-later in file carbon.conf, it refers to CONF_DIR/whitelist
-it's not clear if it should be just file whitelist, or whitelist.conf
-internet documentation says GRAPHITE_CONF_DIR is searched for whitelist.conf - let's believe this one

I have installed Graphite from EPEL repo, RedHat 7. Version 0.9.16
Metrics are received by AMQP.
I have file /etc/carbon/whitelist.conf present and there entries, etc. first one is "^carbon\."
I pointed variable WHITELISTS_DIR to conf dir just for sure
USE_WHITELIST = True is present in carbon.conf

When I send dummy metric via rabbitmq, creates.log shows that metric was created (there is file in whisper location), even the whitelist does not allow such metric name to be accepted.

I also started service like:
carbon-cache --config=/etc/carbon/carbon.conf --whitelist=/etc/carbon/whitelist.conf start
-with no result

How can i verify if carbon-cache process actually loaded whitelist configuration?
I tried the same with blacklist and same result - totally ignored.
What is the proper way of troubleshooting this? Where to start?

Thanks a lot

**Comment by mcbsdEU** [comment]
Anyone here to give advice?
Thanks!

**Comment by piotr1212** [comment]
I think the AMQP input does not do whitelist/blacklist processing.

**Comment by mcbsdEU** [comment]
Oh, I didn't think about such reason...
Thanks a lot for the hint! I'll try to elaborate on this.

**Comment by mcbsdEU** [comment]
Hi,

just if anyone is interested.
I can confirm that AMQP is not considering white/blacklist. But we also did upgrade to latest carbon....
So if you use latest carbon & TCP input (not AMQP) - this filtering should work.

Thanks
