### ISSUE TITLE
Extensive log message amount without disable switch

### ISSUE THREAD

**Issue by Kenterfie** [graphite-project/carbon#693]
lib/carbon/database.py use log.msg in tag function what cause a huge log come up without option to disable.

Also the tagging function himself use many single http calls what also ends up in many refused connections. Would be great to modify these behavior.

**Comment by DanCech** [comment]
Switching the success messages to debug isn't too hard, I'll pop a PR for that.  If you are seeing a lot of messages like `Error tagging X` then you need to properly configure your `GRAPHITE_URL='http://127.0.0.1:8000'` setting to point to your graphite-web install.

As far as the connections, it should be using a pool of persistent connections and you can adjust the frequency of the updates if they're overloading your graphite server using the `TAG_UPDATE_INTERVAL=100` config setting.  To halve the number of calls to graphite increase it to `200`.

**Comment by DanCech** [comment]
The referenced PR also includes a setting `ENABLE_TAGS` which you can set to `False` if you aren't using tags at all and want to disable it altogether.

**Comment by deniszh** [comment]
Merged to master, will be included in next release.
