### ISSUE TITLE
RPM packages for 1.0.x and CentOS-7 ?

### ISSUE THREAD

**Issue by zdenekpizl** [graphite-project/carbon#695]
Greetings,

 is there any reliable source of CentOS-7 RPM packages? I was not able to get any at all.

Thank you, .zp.

**Comment by deniszh** [comment]
Hi @zdenekpizl,
Maybe @piotr1212 knows? I heard that he was involved in Graphite packaging some time ago.
Please note that Graphite 1.0.x uses quite new versions of its dependencies, so, it could we hard to backport that.

**Comment by zdenekpizl** [comment]
My concerns is about those dependencies exactly. It would be a hell to build all those packages :-/ apparently

**Comment by zdenekpizl** [comment]
Anybody else do have an idea where or how to get latest version as RPMs with all dependencies? Thanks ...

**Comment by deniszh** [comment]
Build using `fpm`? https://github.com/jordansissel/fpm
`fpm -s python -t rpm whisper`
`fpm -s python -t rpm carbon`
`fpm -s python -t rpm graphite-web`
...
repeat for all dependencies (and dependencies of dependencies ofc). Unfortunately, `fpm` is  not able to to that automatically. You can get dependencies from rpm package using `rpm -qRp` command.

**Comment by zdenekpizl** [comment]
OK, that looks like a plan :) Thank you.

**Comment by deniszh** [comment]
Yep, it's a bit clumsy - but that's how it is, sorry. 🤷‍♂️
