### ISSUE TITLE
Exception monitoring (sentry.io and others..)

### ISSUE THREAD

**Issue by iksaif** [graphite-project/carbon#702]
I'd like to plugin my carbon installs to sentry. The way to do that seems to be:

```python
from twisted.python import log
from raven import Client

client = Client(dsn='twisted+http://YOUR_DSN_HERE')

def logToSentry(event):
    if not event.get('isError') or 'failure' not in event:
        return

    f = event['failure']
    client.captureException((f.type, f.value, f.getTracebackObject()))

log.addObserver(logToSentry)
```

Would you be against putting some (optional) code to do that in util.py/log.py ? (basically, if the raven settings are here + the lib is available, then the code gets enabled).

**Comment by deniszh** [comment]
I'm totally 👍 for Sentry, if it's optional ofc. :)

**Comment by wridgers** [comment]
This would be great! We already have Sentry hooked into graphite-web and it's very useful.

**Comment by iksaif** [comment]
I have a patch ready, will send it during the week. I have one for graphite-web too

**Comment by iksaif** [comment]
done
