### ISSUE TITLE
REPLICATION_FACTOR it not working as expected

### ISSUE THREAD

**Issue by leochen4891** [graphite-project/carbon#705]
In carbon.conf, I have three nodes in the DESTINATIONS for carbon-relay, and set REPLICATION_FACTOR to 2.
I used to see two wsp files for each metric on two of the three nodes in DESTINATIONS, however, after upgrading to 1.1.0-pre4, I have observed only one wsp file is written for each metric.
Correct me if I'm wrong, but is the case of multiple nodes in DESTINATIONS covered by the tests?
(https://github.com/graphite-project/carbon/pull/661)

My apologies for not being able to debug deeper and find the root cause.

**Comment by deniszh** [comment]
Hi @leochen4891,
I made a quick test using docker - I do not see any problems with routing in relay in 1.1.0-pre4
Could you please describe your setup a bit more in details and share your configs?
Thanks!

**Comment by leochen4891** [comment]
I have the following settings for carbon-relay in carbon.conf
DESTINATIONS = node1:2004, node2:2004, node3:2004
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 2

Before upgrading to 1.1.0-pre4, I see two wsp files on two of the three nodes for a particular metric.
After upgrading however, there is only one wsp file for a metric.

**Comment by deniszh** [comment]
That's strange. I can't reproduce, unfortunately. I can only suggest to debug problem in your local env more closely.

**Comment by deniszh** [comment]
Made another test, with 3 destinations and REPLICATION_FACTOR=2 I see the normal behavior.

**Comment by leochen4891** [comment]
Thanks @deniszh. Appreciated.
I will check again later with the official 1.1.0 release and see if I can reproduce.
