### ISSUE TITLE
MetricPickleReceiver not catching exception for None data value

### ISSUE THREAD

**Issue by retzkek** [graphite-project/carbon#706]
When the `MetricPickleReceiver` is sent a metric with `None` as the value, it will throw a `TypeError`, while only `ValueError` is handled. As a result any following datapoints will be lost. 

https://github.com/graphite-project/carbon/blob/master/lib/carbon/protocols.py#L232

**Comment by deniszh** [comment]
Yes, indeed. Could you please open a PR for your fix, @retzkek ?
