### ISSUE TITLE
Carbon-cache

### ISSUE THREAD

**Issue by AsenZahariev** [graphite-project/carbon#712]
Hello folks,
Is there a tool/method from which i can check if a given metric is stored into the carbon-cache ?
Thank you!
Asen Z.

**Comment by reyjrar** [comment]
graphite-web?

**Comment by deniszh** [comment]
@AsenZahariev: you can make carbonlink call, please see https://gist.github.com/cbowman0/32b0fe59be7d5d4228be902e2e7aef19
