### ISSUE TITLE
Don't use six in setup.py

### ISSUE THREAD

**Issue by iksaif** [graphite-project/carbon#721]
Using six in setup.py is annoying because all packages depending on carbon need to install six before trying to install carbon. It should be easy enough to get rid of this dependency.

**Comment by deniszh** [comment]
Yep, should be easy.
Just replace
`from six.moves import configparser`
with https://github.com/graphite-project/graphite-web/blob/master/setup.py#L6-L9:
```
try:
    from ConfigParser import ConfigParser, DuplicateSectionError  # Python 2
except ImportError:
    from configparser import ConfigParser, DuplicateSectionError  # Python 3
```
