### ISSUE TITLE
Random gap in recent data since upgrading to 1.1.1

### ISSUE THREAD

**Issue by wridgers** [graphite-project/carbon#729]
Since upgrading to carbon 1.1.1 I'm seeing a gap in recent metrics. The data doesn't seem to be "missing" - it does eventually get written to disk. There seems to be a 10m gap in the last 20m at all times.

![2018-01-10-110846_845x294_scrot](https://user-images.githubusercontent.com/235730/34769840-ed40ba14-f5f6-11e7-9837-66a024556939.png)
![2018-01-10-110906_1261x379_scrot](https://user-images.githubusercontent.com/235730/34769843-eeb2fd6c-f5f6-11e7-8d45-00be952982d2.png)

Sometimes the last 10m of data is missing, and then all my grafana alerts will fire and complain about no data.

**Comment by deniszh** [comment]
Is it only for carbon (internal) metrics or all metrics?

**Comment by wridgers** [comment]
All metrics. :(

**Comment by DanCech** [comment]
Sounds like maybe whisper is lagging 20m behind but the most-recent data is getting served by carbonlink.  Do you have your graphite url set in the carbon config?

**Comment by deniszh** [comment]
>Sounds like maybe whisper is lagging 20m behind but the most-recent data is getting served by carbonlink.

In this case should be no gaps, if carbonlink merging works properly ofc...

**Comment by wridgers** [comment]
We've set `ENABLE_TAGS=False` and restarted the caches. It looks like the problem is solved, but it'll take a while to confirm.

https://github.com/graphite-project/carbon/issues/730 Seems like might be fixed too.

Waiting on more data to come in.

**Comment by deniszh** [comment]
#730 is clear, but non-configure Tags causing gaps... That's a bit worrying.

**Comment by wridgers** [comment]
I diffed the config that I commited into version control, and there nothing but new lines with comments. :/

**Comment by wridgers** [comment]
> We've set ENABLE_TAGS=False and restarted the caches. It looks like the problem is solved, but it'll take a while to confirm.
> Seems like #730 might be fixed too.
> Waiting on more data to come in.

It's not fixed - the gaps are back. Perhaps the restart just made the problem go away for a bit.

**Comment by DanCech** [comment]
Ok, so if you have `ENABLE_TAGS=False` then it has to be something else.  Are you seeing memory usage increasing also?

**Comment by wridgers** [comment]
> Are you seeing memory usage increasing also?

Yeah, memory usage of the caches is still growing while the number of metrics in the cache stays constant.

**Comment by deniszh** [comment]
I'm a bit confused now. 
@wridgers, does `ENABLE_TAGS=False` fixing memory consumption or not?
If not, I'll better reopen #730

**Comment by wridgers** [comment]
> I'm a bit confused now.
> @wridgers, does ENABLE_TAGS=False fixing memory consumption or not?
> If not, I'll better reopen #730

Still experiencing the gap and the memory consumption.

Here you can see the memory growing steadily after I restarted it to turn off tagging. You can also see the gap in metrics to the far right.

![2018-01-10-232352_956x284_scrot](https://user-images.githubusercontent.com/235730/34800830-7d5fa07c-f65d-11e7-832b-2753047b8311.png)

Here's another random graph which shows the ever present gap more clearly.

![2018-01-10-232424_654x213_scrot](https://user-images.githubusercontent.com/235730/34800869-a4a2c18c-f65d-11e7-851b-7a81be99843b.png)

The gap is always there. There will be a few (n) samples, then a gap of ~15 minutes, then the rest of the data. I can see in the graphite-web logs "got n samples from carbon cache", and if I dump the whisper files I can see samples up to where the gap starts.

**Comment by wridgers** [comment]
If it helps, here is our `carbon.conf` with commets and empty lines removed.

```
root@graphite2:/opt/graphite/conf# cat carbon.conf | grep -v '^$\|^\s*\#'
[cache:1]
PICKLE_RECEIVER_PORT = 2314
CACHE_QUERY_PORT = 7012
[cache:2]
PICKLE_RECEIVER_PORT = 2324
CACHE_QUERY_PORT = 7022
[cache:3]
PICKLE_RECEIVER_PORT = 2334
CACHE_QUERY_PORT = 7032
[cache:4]
PICKLE_RECEIVER_PORT = 2344
CACHE_QUERY_PORT = 7042
[cache]
DATABASE = whisper
ENABLE_LOGROTATION = True
USER =
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 100
MAX_CREATES_PER_MINUTE = 1000
MIN_TIMESTAMP_RESOLUTION = 1
LINE_RECEIVER_PORT = 0
ENABLE_UDP_LISTENER = False
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 127.0.0.1
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CREATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = True
CACHE_WRITE_STRATEGY = timesorted
WHISPER_AUTOFLUSH = False
WHISPER_FALLOCATE_CREATE = True
GRAPHITE_URL = http://127.0.0.1:80
ENABLE_TAGS = False
[relay:1]
LINE_RECEIVER_PORT = 2113
PICKLE_RECEIVER_PORT = 2114
[relay:2]
LINE_RECEIVER_PORT = 2123
PICKLE_RECEIVER_PORT = 2124
[relay]
LINE_RECEIVER_INTERFACE = 127.0.0.1
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
RELAY_METHOD = aggregated-consistent-hashing
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2214:1, 127.0.0.1:2224:2, 127.0.0.1:2234:3, 127.0.0.1:2244:4
DESTINATION_PROTOCOL = pickle
MAX_QUEUE_SIZE = 50000
MAX_DATAPOINTS_PER_MESSAGE = 500
QUEUE_LOW_WATERMARK_PCT = 0.8
TIME_TO_DEFER_SENDING = 0.0001
USE_FLOW_CONTROL = True
USE_RATIO_RESET=False
MIN_RESET_STAT_FLOW=1000
MIN_RESET_RATIO=0.9
MIN_RESET_INTERVAL=121
[aggregator:1]
PICKLE_RECEIVER_PORT = 2214
[aggregator:2]
PICKLE_RECEIVER_PORT = 2224
[aggregator:3]
PICKLE_RECEIVER_PORT = 2234
[aggregator:4]
PICKLE_RECEIVER_PORT = 2244
[aggregator]
LINE_RECEIVER_PORT = 0
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
FORWARD_ALL = True
DESTINATIONS = 127.0.0.1:2314:1, 127.0.0.1:2324:2, 127.0.0.1:2334:3, 127.0.0.1:2344:4
REPLICATION_FACTOR = 1
MAX_QUEUE_SIZE = 50000
USE_FLOW_CONTROL = True
MAX_DATAPOINTS_PER_MESSAGE = 500
MAX_AGGREGATION_INTERVALS = 5
LOG_AGGREGATOR_MISSES = False
```

**Comment by DanCech** [comment]
@wridgers can you try #731 and see if that has any impact?

**Comment by wridgers** [comment]
> @wridgers can you try #731 and see if that has any impact?

Just restarted our cache's with this patch. I'll update this thread with results.

**Comment by wridgers** [comment]
#731 did not fix our problem. The gaps came back after a few hours.

#733 however has fixed both this and the the memory leak.

**Comment by deniszh** [comment]
Thanks, will make a bugfix release soon!
