### ISSUE TITLE
carbon-relay drops metrics when a backing carbon-writer is down

### ISSUE THREAD

**Issue by burr86** [graphite-project/carbon#73]
Our configuration is to have 1 carbon-relay proxying metrics to 4 carbon-writers. We just had a case where one of them was down, and (I assume) metrics that it would've received were just being dropped instead. We're using the Consistent Hashing algorithm.

In our case, all of the writers were on the same machine, so we would've rathered have it fail to another node rather than dropping the metrics; not sure if that logic still holds in a multiple server setup.

**Comment by piotr1212** [comment]
This is implemented in https://github.com/graphite-project/carbon/pull/661/commits/356c34a32306d8d9627e606bab49f0671f86a937 Dynamic_router
