### ISSUE TITLE
Memory leak since upgrading to carbon 1.1.1

### ISSUE THREAD

**Issue by wridgers** [graphite-project/carbon#730]
Looks like a memory leak to me. Cache size hasn't changed, but the memory is growing.

![2018-01-10-131405_1261x270_scrot](https://user-images.githubusercontent.com/235730/34774778-9fa65bda-f608-11e7-8cb3-1da1004e7cba.png)
![2018-01-10-131400_838x267_scrot](https://user-images.githubusercontent.com/235730/34774785-a293f1b8-f608-11e7-8914-0f7147088064.png)

**Comment by DanCech** [comment]
Did you set GRAPHITE_URL in your carbon config?  If not it may be due to it being unable to update the tag db

**Comment by wridgers** [comment]
`GRAPHITE_URL` is set in `carbon.conf` to `http://127.0.0.1:80/`.

**Comment by DanCech** [comment]
Is that a valid url for your graphite-web install?

**Comment by wridgers** [comment]
> Is that a valid url for your graphite-web install?

`curl -s http://127.0.0.1:80` returns a PNG, so I'm pretty sure it's correct.

**Comment by wridgers** [comment]
I'm not seeing any errors in the logs about an invalid URL and the `tags` tables in the database (postgres) are being populated.

**Comment by DanCech** [comment]
Folding this into #729

**Comment by deniszh** [comment]
Looks like different issue, reopening.

**Comment by deniszh** [comment]
Thanks, @wridgers !
Fix' merged, will be released soon.
