### ISSUE TITLE
Install requires access to /opt/graphite

### ISSUE THREAD

**Issue by awestendorf** [graphite-project/carbon#74]
This makes sense for system installs but does not allow for virtualenv installs. The binaries are libraries should end up in the vritualenv path, and then the creation of a storage and conf directory can be left to the user.  A simple message that one can see from pip would be enough to let them know that they have to create the directory.

**Comment by Whitespace** [comment]
I'm quite surprised that it's 2015 and this is still an issue :(

**Comment by mleinart** [comment]
Protip: making volunteer maintainers feel bad isn't a great way to get
progress on an issue

**Comment by timbunce** [comment]
And asking how you can help is a great way to move the issue forward.

**Comment by piotr1212** [comment]
See https://github.com/graphite-project/carbon/pull/835

**Comment by twm** [comment]
For anyone stumbling across this, you can set the `GRAPHITE_NO_PREFIX` environment variable to disable the `/opt/graphite` stuff.

**Comment by twm** [comment]
This is still a thing AFAIK.

**Comment by piotr1212** [comment]
setting the `GRAPHITE_NO_PREFIX` env variable ommits `/opt/graphite`.  We also have https://github.com/graphite-project/carbon/pull/835#issuecomment-613110341 open, closing this issue to centralise discussion.
