### ISSUE TITLE
Carbon answers tcp connections slowly on 1.1.1

### ISSUE THREAD

**Issue by jdblack** [graphite-project/carbon#745]
Hello, 

I'm not quite sure how to describe what happened for us, but  carbon became very slow for us when we tried upgrading from carbon 1.0.1 to 1.1.1.    Graphite-web  1.1.1 seemed unable to connect to it, and conecting to to carbon directly on port 201x  (we have 3 on each box)   took somewhere around 3/4 of a second before a connection was established.

The problem went away when going back to carbon 1.0.1

DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
Kernel: 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python version: 2.7.12

pip list:
jblackwell:~$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
appdirs (1.4.3)
attrs (15.2.0)
awscli (1.11.64)
Babel (2.4.0)
boto (2.46.1)
botocore (1.5.27)
cachetools (2.0.1)
cairocffi (0.8.0)
carbon (1.0.1)
carbonate (1.1.1)
cffi (1.10.0)
chardet (2.3.0)
colorama (0.3.7)
cryptography (1.2.3)
Django (1.9.13)
django-appconf (1.0.2)
django-shortcuts (1.5)
django-staticfiles (1.2.1)
django-tagging (0.4.3)
docutils (0.13.1)
enum34 (1.1.2)
funcsigs (1.0.2)
futures (3.0.5)
gevent (1.1.0)
graphite-web (1.1.1)
greenlet (0.4.9)
gunicorn (19.4.5)
idna (2.0)
imagesize (0.7.1)
ipaddress (1.0.16)
Jinja2 (2.9.6)
jmespath (0.9.2)
MarkupSafe (1.0)
mock (2.0.0)
mocker (1.1.1)
mysqlclient (1.3.7)
ndg-httpsclient (0.4.0)
packaging (16.8)
PAM (0.4.2)
pbr (2.0.0)
pip (9.0.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycparser (2.18)
Pygments (2.2.0)
pyOpenSSL (0.15.1)
pyparsing (2.2.0)
pyserial (3.0.1)
python-dateutil (2.6.0)
python-memcached (1.53)
pytz (2017.2)
PyYAML (3.12)
requests (2.9.1)
rsa (3.4.2)
s3transfer (0.1.10)
scandir (1.5)
service-identity (16.0.0)
setuptools (38.5.1)
simplejson (3.8.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.6.3)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
sqlparse (0.1.18)
stevedore (1.21.0)
Twisted (16.0.0)
txAMQP (0.7.0)
typing (3.6.1)
urllib3 (1.21.1)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wheel (0.29.0)
whisper (1.0.1)
whitenoise (3.3.0)
zope.interface (4.1.3)

carbon

**Comment by deniszh** [comment]
You can try to 1.1.x branch or apply this fix above directly, of course.
