### ISSUE TITLE
carbon cache using 100 IO PID

### ISSUE THREAD

**Issue by alexandershelega** [graphite-project/carbon#750]
Hello, i have a problem with carbon cache daemons. They are using 100% disk IO and i don't understand why. I spent a few weeks to resolve this issue without result. 

Output of iotop in screenshot. 
<img width="922" alt="screen shot 2018-02-21 at 10 57 46 am" src="https://user-images.githubusercontent.com/24225604/36467007-22de2b32-16f6-11e8-95e9-63f398a500ab.png">

This is my carbon cache configuration.

```
[cache:a]
DATABASE = whisper
ENABLE_LOGROTATION = True
USER =
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 500
MAX_CREATES_PER_MINUTE = 5000
LOG_LISTENER_CONNECTIONS = False
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 1103
ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 1103
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 1104
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 0.0.0.0
CACHE_QUERY_PORT = 7002
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = False
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = True
WHISPER_FALLOCATE_CREATE = True
```

I have installed latest carbon, but also tried old versions, i have installed graphite on other hosts with same bad result.

**Comment by deniszh** [comment]
Hello @alexandershelega 
You can try to set CACHE_WRITE_STRATEGY=max or CACHE_WRITE_STRATEGY=timesorted, but please note that whisper is really IO hungry format - during write it updates all archives in whisper file, so, write amplification can be huge.
You can also increase the number of carbon caches or try to use golang implementation  of carbon - https://github.com/lomik/go-carbon
But if nothing helps then it means that you need to scale horizontally and add another server for storing data.

**Comment by deniszh** [comment]
MAX_CREATES_PER_MINUTE is too much comparable with MAX_UPDATES_PER_SECOND. Probably, you should lower that to same 500.

**Comment by alexandershelega** [comment]
Hello, i have two servers in my configuration , problem is in high IO as you see each carbon cache write 100kb data and it is not much, my old graphite server with 6 carbon cache work perfectly with same configuration but it have small storage.

I will try to change cache strategy, i hope it will help, and also will try decrease updates and creates.

**Comment by alexandershelega** [comment]
Hello, 

I have tried all options which you provided, doesn't help, i have same situation 100% IO on TID.

**Comment by piotr1212** [comment]
Isn't it just a "slow" disk? Try to lower MAX_UPDATES_PER_SECOND, set it to 50 or so to see what happens.

**Comment by piotr1212** [comment]
WHISPER_AUTOFLUSH = True <-- Set this to false.

**Comment by alexandershelega** [comment]
@piotr1212 same problem with MAX_UPDATES_PER_SECOND = 50. I have set it to False, carbon-cache processes show me 0% IO , but kworker IO 100%. 

@deniszh how can i use go-carbon with default relay and aggregators, because in log i see [clients] Destination is down: 172.16.33.90:2004:a (424/5). As i see default relay and aggregator don't work with go-carbon.

**Comment by piotr1212** [comment]
Isn't your disk just slower than on the other server?

**Comment by alexandershelega** [comment]
Yes, in old server was SSD on this server RAID5 with HDD, but as you see total write on server around 1 MB p/s, I do not believe that 1 MB can kill a disk.

**Comment by piotr1212** [comment]
whispers random reads can really kill a spinning disks performance. Although I don't see much reads in your screenshot. Besides throughput the number of IO operations is critical for performance, especially on spinning disks, check your IOPS with iostat -x 10 (or some other tool).  Anyway, you really cannot compare the performance of a SSD with a spinning disk. You might also want to do some tuning on your raid controller.

**Comment by alexandershelega** [comment]
@piotr1212 thanks, i will try install graphite again on server with SSD disks, if problem appeared again will notify you.
