### ISSUE TITLE
What is the strategy of carbon-aggregator to deal with delayed data

### ISSUE THREAD

**Issue by nfw999** [graphite-project/carbon#751]
Hi,
I'm using carbon-aggregator to receive my metrics with some basic rules. 
sum.\<env\>.all.min.metricsReceived (10) = sum \<env\>.*.min.metricsReceived
If the data is calculated, but there is an , this one overrides the calculated value.
At this moment, sum.test.all.min.metricsReceived:
[10.0, 1519714380]
After ten minutes,send
test.host1.min.metricsReceived 2  1519714380
after that sum.test.all.min.metricsReceived change to:
[2.0, 1519714380]
What is the strategy of carbon-aggregator to deal with delayed data? Is there any setup to avoid this?
Thanks in advance

**Comment by DanCech** [comment]
It sounds like the bucket had already been processed during that 10-minute period and the value of 10 flushed, so when the new reading was received it was treated as a new bucket.  The aggregator always uses the current time, delayed data is not supported.

**Comment by nfw999** [comment]
@DanCech 
This situation does exist, and the problem seems to can be fixed, and whether there is a plan to fix it

**Comment by deniszh** [comment]
Hello @nfw999,
It's a know limitation of aggregator, unfortunately.
We are not happy with the current state of aggregator, indeed, but I'm afraid it's not possible to easily fix that. Aggregator should be totally reworked to support delayed and we have no such plans currently.
