### ISSUE TITLE
carbon-cache cpu usage regression between 1.1.0 and 1.1.2

### ISSUE THREAD

**Issue by mravkine** [graphite-project/carbon#755]
Hi Guys,

I have noticed a fairly severe performance regression when comparing 1.1.0 with 1.1.2

I have a simple 4-core VM (Softlayer/IBM "BL4x4"), each core has a carbon-cache instance that I am manually load balancing - I am not using relay, nor do I use aggregator.

In my baseline tests, carbon-1.1.0 achives 72K metrics/sec with 40% CPU load, and everyone is happy:

![graphite_1 1 0_quicktest](https://user-images.githubusercontent.com/16022275/37539332-da836c4e-2929-11e8-8f33-7364aa6f396b.PNG)

In my soak tests of the latest carbon-1.1.2, the same traffic level generated the same way now requires almost 60% CPU load!

![graphite_1 1 x_soaktest](https://user-images.githubusercontent.com/16022275/37539446-1ec10e8e-292a-11e8-8f16-f995a5a111a2.PNG)

This regression appears to manifest only under fairly high loads (>50K metrics/sec), and based on the changelogs the only major change I can see to this area is #739  - Could you guys perhaps explain the rationale for changing from async -> sync?

Thanks,
--Mike

**Comment by deniszh** [comment]
#739 is backport of #738 
IIRC it was causing some problems with multitreading code. Right, @DanCech ?
