### ISSUE TITLE
carbon-aggregator ignores CONF_DIR setting

### ISSUE THREAD

**Issue by stahor** [graphite-project/carbon#757]
I'm getting the following error when trying to launch carbon-aggregator (I'm using the newest version of carbon AFAIK). 
```
sudo /opt/graphite/bin/carbon-aggregator.py start                                                                                                                                       
Starting carbon-aggregator (instance a)
aggregation processor: file does not exist /opt/graphite/conf/aggregation-rules.conf
```
but in carbon conf `CONF_DIR = /etc/grafite` and carbon-cache starts without any issues so it seems to me that config lookup path is hardcoded somewhere

**Comment by deniszh** [comment]
@stahor : I'm not sure that carbon will properly resolve all paths in that case, indeed.
Did you try to put `carbon.conf` to `/etc/grafite` and run  it  like 
`sudo /opt/graphite/bin/carbon-aggregator.py --config=/etc/grafite/carbon.conf start` ?

**Comment by stahor** [comment]
TBH I've already moved everything to the default location. But I still think that it's better to have all daemons working in the same way.

**Comment by deniszh** [comment]
Agreed, but TBH I do not know how it was working before. I tried to reproduce on similar configuration  (`CONF_DIR` in `/opt/graphite/conf/carbon.conf` and all files in other dir) but for me, it was not working at all.  :(
`--config` is working, though.

**Comment by stahor** [comment]
Also it looks like carbon-aggregator-cache ignores logging settings. I mean LOG_UPDATES, LOG_CREATES etc. They all are false but I still get tons of logs =/. Should these settings be moved somewhere else? They are under [cache] section now.

**Comment by stahor** [comment]
Btw putting all settings under `[aggregator-cache]` helped me. Still not sure if helps for carbon-aggregator config location issue. But I think that if this works as well then the issue can be closed.
Maybe changes to documentation and example configs are required.
