### ISSUE TITLE
uninstall carbon and reinstall to new directory

### ISSUE THREAD

**Issue by JosephFY** [graphite-project/carbon#758]
I have initially installed carbon ( and whisper, graphite-web)  on a dev environment through

cd /tmp; git clone   https://github.com/graphite-project/carbon.git;
cd /tmp/carbon; git checkout 1.1.1;   python setup.py install; wait;

graphite is installed under /opt/gaphite and working as expected 

so now I want to install 1.1.2 but want to I want to move my installation directory  to /graphite instead of /opt/graphite. I have done a new installation on different directory on another box but that was a brand new installation without any existing installation.

Been looking for a way to uninstall all the of graphite components but couldnt find any clear documentation.  **pip list** only shows whisper 1.1.1 only 

what is the best way of uninstalling graphite and reinstalling ? couldnt find any documentation about that.

I am running it on a redhat 7.4 box.

Thank you

**Comment by deniszh** [comment]
@JosephFY 
In general, `pip uninstall` should work (but please note culprit from https://github.com/graphite-project/carbon/issues/711), but `pip list` should give you the list of your packages in that case. Maybe you using virtualenv?

**Comment by JosephFY** [comment]
No I am not using virtualenv. And whats is interesting is that i went a head an installed carbon as below (on a different directory with renaming the old /opt/graphite to /opt/xgraphite)  and still not showing under `pip list` is there anything I am missing here ? kinda weird !

`pip   install carbon --install-option="--prefix=/graphite"   --install-option="--install-lib=/graphite/lib" `

**Comment by deniszh** [comment]
Well, python packaging is a mess TBH. 🤷‍♂️

**Comment by JosephFY** [comment]
I am just afraid that i will have issues down the road if that carbon and the graphite-web components do not show as installed under pip packages. specially if i needed to used carbonate/buckytools down the road. 

I remember seeing an issues that you commented at with a guy having issues installing carbonate because it's not seeing carbon installed. Will share that link when I find it

**Comment by redbaron4** [comment]
You need to tell pip to look in the `/opt/graphite` directory.

Maybe something like:

`PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/" pip freeze`

**Comment by piotr1212** [comment]
IIRC: If you use `python setup.py install` then it is not registered with pip and `pip uninstall` will not work.

I would recommend to always install through pip (unless you are developing). From a source directory you can use:
```
cd graphite-source-dir
pip install .
```
I'll add this to the docs.

I don't think the reason carbonate cannot see carbon is related to the package showing in pip. I expect this has to be a PYTHONPATH issue, which should be simplified with https://github.com/graphite-project/carbon/pull/835
