### ISSUE TITLE
Delay on queries data from cache after upgrading to 1.1.2

### ISSUE THREAD

**Issue by JosephFY** [graphite-project/carbon#759]
I am working on a stress testing on a box to see how many metrics writes it can hold.

first of all thank you for all the efforts on 1.1.2.  I have seen a huge enhancement on that stress testing after upgrading from 1.1.1 to 1.1.2 specially with #729 . now I have consistent behavior with no gaps.

my stress numbers are as following:
7.5 Millions metrics per minutes, sending data on 20 chunks across 20 seconds across 10 carbon caches
Memoy usage ~35% (20 GB total memory)
CPUs oscillating from ~ 10% to 75% every minutes ( across the 10 carbon caches)

the environment is pretty steady and been running for couple of days, I am facing two issues:

1. I can see delays querying the stress metrics ( not the carbon metrics). The metrics will eventually appear on grafana dashboard but it will take some time. Note that here is no delay on carbon internal metrics at all at any time. 
![image](https://user-images.githubusercontent.com/28739923/38169925-ad67486e-353d-11e8-93a3-e8b7a0607c44.png)

I am suspecting a limit on the memory queries that causing this behavior specially that each of the ten carbon caches are consuming 700 MB and has ~5.0 Million metrics all the time

2. The second issue is that when I restart the carbon-cache via **systemctl restart carbon-cache** the process get killed by the kernel because I guess it's timing out to write all the metrics in cache within a proper time frame. If what i am suspecting is right then shouldnt this behavior be tweaked so the kernel would wait till a successful flush of all the metrics ?

Appreciate the help on this, hopefully it's something within my setup and not a bug somewhere.

**Comment by deniszh** [comment]
Hello @JosephFY ,
 >I can see delays querying the stress metrics ( not the carbon metrics). The metrics will eventually appear on grafana dashboard but it will take some time.

Yes, that's a known issue - new metrics become visible only after corresponding whisper file become created on disk, which is limited by MAX_CREATES_PER_MINUTE (default is 50) and overall disk activity. Unfortunately, there's no simple way how this can be fixed.

> If what i am suspecting is right then shouldnt this behavior be tweaked so the kernel would wait till a successful flush of all the metrics ?

Flushing metrics on shutdown also can be tweaked by MAX_UPDATES_PER_SECOND_ON_SHUTDOWN (default is 1000) but also limited by disk subsystem characteristics. I'm not aware how to carbon can signal `systemd` that flush is done, unfortunately - you just need to wait until carbon process finishes and not kill it before it.

**Comment by JosephFY** [comment]
> Yes, that's a known issue - new metrics become visible only after corresponding whisper file become created on disk, which is limited by MAX_CREATES_PER_MINUTE (default is 50) and overall disk activity. Unfortunately, there's no simple way how this can be fixed.

sorry to not mention that but these metrics are already written to disk, in other word my creates are 0. So I guess something is not right here !


> Flushing metrics on shutdown also can be tweaked by MAX_UPDATES_PER_SECOND_ON_SHUTDOWN (default is 1000) but also limited by disk subsystem characteristics. I'm not aware how to carbon can signal systemd that flush is done, unfortunately - you just need to wait until carbon process finishes and not kill it before it.

I wasnt killing the carbon process manually, I kinda found why the carbon-cache service get killed, this section under /etc/init.d/carbon-cache which get called when performing `systemctl restart carbon-cache` so I guess i need to tweak the wait `sleep 3` to something that works for me 

if [ `sleep 3; /usr/bin/pgrep -f "carbon-${CARBON_DAEMON}.py --instance=${INSTANCE}" | /usr/bin/wc -l` -gt 0 ]; then
            echo "Carbon did not stop yet. Sleeping longer, then force killing it...";
            sleep 20;
            /usr/bin/pkill -9 -f "carbon-${CARBON_DAEMON}.py --instance=${INSTANCE}";
        fi;

**Comment by deniszh** [comment]
>sorry to not mention that but these metrics are already written to disk, in another word my creates are 0. So I guess something is not right here!

Then I'm completely puzzled by the graph above. What does it mean and why it's declining? My initial thought was that you creating many new metrics with name `stress.serverX.mertricY` and value 1 - then it was definitely affected by the scenario which I described above.
If it's not the case - could you please elaborate issue then? Adding details about your setup and configs also help.
Thanks!

> I guess i need to tweak the wait sleep 3 to something that works for me

Yes, 20 seconds is too low. Or you can alter script to really wait until process is stopped, but it can be tricky...

**Comment by JosephFY** [comment]
@deniszh thank you for the response on this

> Then I'm completely puzzled by the graph above. What does it mean and why it's declining? My initial thought was that you creating many new metrics with name stress.serverX.mertricY and value 1 - then it was definitely affected by the scenario which I described above.
If it's not the case - could you please elaborate issue then? Adding details about your setup and configs also help.
Thanks!

so these are are just metrics I am generating from a test program to s tress test graphite, I am sending 7.5 million of metrics per minutes. All the metrics have been created and my creates are just zero as I mentioned. Just to test the data I made a panel in Grafana which was the one I have attached to see if the datepoints are being available to from disk and cache as my cache is pretty big per carbon process ( ~5.5 million per each carbon process, 10 process total ) It looks like some datepoints and not all are not showing on the graph. if i wait a while ~ hours these will eventually show on the graph but will always have this 2 hours-behind metrics. here is a more clear screen shot for one server metrics 
![image](https://user-images.githubusercontent.com/28739923/38272710-a5b1ccc0-374f-11e8-8d7e-b0ab4dccfc93.png)

if my issue was from a miss configuration on the `CARBONLINKS_HOSTS` it would cause the issue for all metrics not only few of them I guess. 

my `carbon-cache.config` file

[cache]
DATABASE = whisper
ENABLE_LOGROTATION = True
USER =
MAX_CACHE_SIZE = 10000000
MAX_UPDATES_PER_SECOND = 5
MAX_CREATES_PER_MINUTE = 50000
MIN_TIMESTAMP_RESOLUTION = 1
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 2003
#PICKLE_RECEIVER_INTERFACE = 0.0.0.0
#PICKLE_RECEIVER_PORT = 2004
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 0.0.0.0
CACHE_QUERY_PORT = 7002
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CREATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = False
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False
WHISPER_FALLOCATE_CREATE = True
CARBON_METRIC_INTERVAL = 10
MAX_UPDATES_PER_SECOND_ON_SHUTDOWN = 1000000
ENABLE_TAGS = False
LOG_UPDATES = False
LOG_CREATES = False
LOG_CACHE_HITS = True
LOG_CACHE_QUEUE_SORTS = True


[cache:b]
LINE_RECEIVER_PORT = 2103
CACHE_QUERY_PORT = 7102
[cache:c]
LINE_RECEIVER_PORT = 2203
CACHE_QUERY_PORT = 7202
[cache:d]
LINE_RECEIVER_PORT = 2303
CACHE_QUERY_PORT = 7302
[cache:e]
LINE_RECEIVER_PORT = 2403
CACHE_QUERY_PORT = 7402
[cache:f]
LINE_RECEIVER_PORT = 2503
CACHE_QUERY_PORT = 7502
[cache:g]
LINE_RECEIVER_PORT = 2603
CACHE_QUERY_PORT = 7602
[cache:h]
LINE_RECEIVER_PORT = 2703
CACHE_QUERY_PORT = 7702
[cache:i]
LINE_RECEIVER_PORT = 2803
CACHE_QUERY_PORT = 7802
[cache:j]
LINE_RECEIVER_PORT = 2903
CACHE_QUERY_PORT = 7902


[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2014
RELAY_METHOD = rules
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2004
MAX_QUEUE_SIZE = 10000
MAX_DATAPOINTS_PER_MESSAGE = 500
QUEUE_LOW_WATERMARK_PCT = 0.8
TIME_TO_DEFER_SENDING = 0.0001
USE_FLOW_CONTROL = True
USE_RATIO_RESET=False
MIN_RESET_STAT_FLOW=1000
MIN_RESET_RATIO=0.9
MIN_RESET_INTERVAL=121
[aggregator]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2024
FORWARD_ALL = True
DESTINATIONS = 127.0.0.1:2004
REPLICATION_FACTOR = 1
MAX_QUEUE_SIZE = 10000
USE_FLOW_CONTROL = True
MAX_DATAPOINTS_PER_MESSAGE = 500
MAX_AGGREGATION_INTERVALS = 5

`CARBONLINK_HOSTS = ["127.0.0.1:7002:a", "127.0.0.1:7102:b", "127.0.0.1:7202:c", "127.0.0.1:7302:d", "127.0.0.1:7402:e", "127.0.0.1:7502:f", "127.0.0.1:7602:g", "127.0.0.1:7702:h", "127.0.0.1:7802:i", "127.0.0.1:7902:j"]`

So if I were to summarize the issue it would be that some metrics (not all) are getting delayed to show on the graph, there are NOT gone and no gaps will be in the graphs. Is's just they are always behind for about 2 hours.

Please let me know if I any other clarification is needed. we are working on getting this box in production but now it seems like we cant till we get this issue squared away.  Appreciate the help on this.
Yousef

**Comment by JosephFY** [comment]
UPDATE: 
Just wanted to add a screen shot when all metrics have eventually shown in the query for the same time frame without any issues (its taking aprox 2 hours ). I am positively sure something is not right with reading from the cache portion that causing the delay showing the live data for **some** metrics.

![image](https://user-images.githubusercontent.com/28739923/38286006-a81da180-3788-11e8-8a88-47fe396dbcf0.png)

**Comment by deniszh** [comment]
@JosephFY 
Could you please show your relay-rules.conf ? Usually you need to use `consistent-hash` routing for loaded system, though.

**Comment by JosephFY** [comment]
I am actually using carbon-c-relay and it is residing on another box, and I am using **fnv1a_ch**  for sending metrics to  these 10 carbon-caches instances ? Would that make any difference ? I cant remember what version but i remember the most recent versions of graphite has **fnv1a_ch** feature.  I will try to use  **carbon_ch** today and see if there is any difference.

**Comment by deniszh** [comment]
You can use fnv1a_ch but then you need to enable in in loca_settigs.py:
```
CARBONLINK_HASHING_TYPE = 'fnv1a_ch'
```
because default it `carbon_ch`.

**Comment by JosephFY** [comment]
still no luck even after changing the to `fnv1a_ch`. to eliminate any doubt, I am using an older version of carbon-c-relay, v2.6. there was a lot of enhancements since that and they are now on version 3.3 which I am trying to install, once I get all that in place I will circle back on this. I wonder if anyone else had such an issue with the 1.1.2 release, could be that most peopeel still using the older releases so it wasn't caught yet !

question on the side, are you familiar with carbon-c-relay installations by any chance ? you have any installation guide/steps handy ?

thank you @deniszh  for the help on this, I wouldn't have corrected my config without you pointing me to the hashing configuration

**Comment by deniszh** [comment]
Well, that's definitely hashing issue - graphite-web just picks wrong instances for data, missing cache and reads (delayed because not flushed yet) data from disk. Probably you configured `carbon-c-relay` in non-matching way. I would recommend to test `carbon_ch` hashing in `carbon-c-relay` and  `graphite-web`.
Could you please show your carbon-c-relay config?

**Comment by JosephFY** [comment]
I totally agree it's a hashing issue, tracking the modified dates for the WSP files matches the last datepoints shown on graphs. Meaning that for the metrics that get delayed I will only see them on graph after the datapoints get written to their WSP files.

I tried the carbon_ch and faced the same issue !

here is my carbon-c-relay config file, have different stuff in it and this is there related portion to my stress testing

cluster physical-node2-70
#fnv1a_ch
carbon_ch
10.238.104.70:2003=a
10.238.104.70:2103=b
10.238.104.70:2203=c
10.238.104.70:2303=d
10.238.104.70:2403=e
10.238.104.70:2503=f
10.238.104.70:2603=g
10.238.104.70:2703=h
10.238.104.70:2803=i
10.238.104.70:2903=j
;

match ^stress
send to
        physical-node2-70
stop
;

I was reading this thread from the carbon-c-relay project [Q: using carbon_ch/fnva1_ch together with graphite's CARBONLINK_HOSTS #285](https://github.com/grobian/carbon-c-relay/issues/285)

> More occurrences of metrics' data file, old files will stop updating, new files will have no old data, plus your cache will be effectively broken. IMO it's better to wipe all data then.

your comment kinda confused me. I though the hashing has only to do with querying the datapoints in cache memory. My question is if my metrics was initially created when I was using `fnv1a_ch`, does switching to `carbon_ch` requires me to delete or adjust anything on the whisper files side (recreating the files for example) ? or I can switch between those two methods without any issues? 
My scenario isthat I was using  `fnv1a_ch` on carbon-c-relay and my carbon was left on default config which is 'carbon_ch' as you mentioned.

I wish there is a decent documentation that explains the all hashing details and the logic behind it.

**Comment by deniszh** [comment]
PS.
>does switching to carbon_ch requires me to delete or adjust anything on the whisper files side (recreating the files for example) ? 

No, my comment was relevant in time of its writing because there was no tools for rebalancing `fnv1a_ch` cluster. Now you can use [buckytools](https://github.com/go-graphite/buckytools) for that.

**Comment by JosephFY** [comment]
@deniszh I really appreciate your help and time (and patience) going through this with the issue. changing the carbonlink to `CARBONLINK_HOSTS = ["10.238.104.70:7002:a", "10.238.104.70:7102:b", "10.238.104.70:7202:c", "10.238.104.70:7302:d", "10.238.104.70:7402:e", "10.238.104.70:7502:f", "10.238.104.70:7602:g", "10.238.104.70:7702:h", "10.238.104.70:7802:i", "10.238.104.70:7902:j"` fixed the issue right away (changing the IP from 127.0.0.1). 
would  you please (if you have time) explain technically why is that for my own information ? is it like the hash algorithm does the hashing and decide which metric goes to which of the carbon process running ? and then in order for the carbon process to look those metrics up they should have the same exact way of "deciphering if we can say" that by using the same exact list ? and why it's working on `carbon_ch` not `fnv1a_ch`

it's kinda interesting ..

Thank you again

**Comment by deniszh** [comment]
@JosephFY 
>changing the carbonlink fixed the issue right away (changing the IP from 127.0.0.1).

Good, glad to hear!

>is it like the hash algorithm does the hashing and decide which metric goes to which of the carbon process running ? 

Yes.

>and then in order for the carbon process to look those metrics up they should have the same exact way of "deciphering if we can say" that by using the same exact list ? 

Yes, you're absolutely right.

> and why it's working on carbon_ch not fnv1a_ch

Carbon hash using IP and instance for hashing, e.g. "10.238.104.70:a", "10.238.104.70:b". But fnv1a_ch using IP and port - but port is different for carbonlink and carbon - 20xx vs 70xx - so, it's just will not work.

**Comment by JosephFY** [comment]
Really appreciate all the help @deniszh  you will definitely hear from me on other issues as we are preparing for a decent implantation of a graphite/grafana across the enterprise.

I will be closing this now but just before I do that, by you saying

>  But you can easy fix that using 2-tier relay - top level relay will route metrics to hosts, and for every host you use another relay to spread metrics across local carbon daemons.

you meant two instances running carbon-c-relay on two different servers right ? one stand alone and one in the box where graphite is running. Just to make it clear

Thanks again

**Comment by JosephFY** [comment]
Hello @deniszh , sorry to reference this close issue but wanted to make sure before opening new thread. was there any changes in 1.1.3 regarding this ?

I am getting and my configuration is identical to the old one, this is a totally new installation of 1.1.3 on a new server

`Failed CarbonLink query 'servers.linux.server1.carbon.agents.server1-h.memUsage'
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers/utils.py", line 106, in merge_with_carbonlink
    cached_datapoints = CarbonLink().query(metric)
  File "/opt/graphite/webapp/graphite/carbonlink.py", line 99, in query
    results = self.send_request(request)
  File "/opt/graphite/webapp/graphite/carbonlink.py", line 132, in send_request
    conn = self.get_connection(host)
  File "/opt/graphite/webapp/graphite/carbonlink.py", line 89, in get_connection
    connection.connect((server, port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused`

**Comment by deniszh** [comment]
@JosephFY: no. error above means that one of your CARTBONLINK_SERVERS is down and refusing connections.

**Comment by JosephFY** [comment]
it's not :( .  and it's listening on the ports, (on all 8 instances ...)

`telnet xx.xxx.xx.xxx 7102
Trying xx.xxx.xx.xxx...
Connected to xx.xxx.xx.xxx.`

**Comment by JosephFY** [comment]
Alright my bad on this, the error is not relevant to the issue I am facing, error only showing when I restart `carbon-cache` which makes sense. 

My issue is the same as before, same configurations but I am only querying the metrics on desk not in the cache, so metrics takes time to appear on graphs. reviewed my configurations like ten times between the carbon-c-relay and the carbon.config and local_settings.py. No luck so far ...
been a serious issue for me since yesterday ... need to get this box in prod very soon ...

**Comment by deniszh** [comment]
You mean, metric distribution changed after upgrade from 1.1.3 to 1.1.4? Strange, I do not remember any hashing changes in 1.1.4

**Comment by JosephFY** [comment]
No, let me explain, the issue I opened for this thread had 1.1.2 and carbon-c-relay 3.2 which we figured it out before and was working fine.

now I am installing on a totally new box with 1.1.3 and carbon-c-relay 3.3 and facing the issue again, Just missing query metrics in the memory.

I was just wondering if anything has changed between 1.1.2 and 1.1.3 on graphite side, not sure if you are up to date on carbon-c-relay versions.

I am on top of this issue as I am typing ...

**Comment by deniszh** [comment]
Try to isolate change first - changing versions of everything is not helping. I do not see anything relevant in carbon changelog for 1.1.3 too - https://graphite.readthedocs.io/en/latest/releases/1_1_3.html

**Comment by JosephFY** [comment]
totally agree, will try the carbon-c-relay first as it's easier, will get back with results. I hope I dont have to do anything on graphite side :S

**Comment by JosephFY** [comment]
@deniszh Just to add to this, I don't think that carbon-c-relay is the issue, the delay is showing even on carbon internal metrics when gets routed internally and not through carbon-c-relay. 

is there any configuration you suggest to check ? before I downgrade to 1.1.2 which I dont like ...

Do you think any prerequisites version has anything related to carbonlink specifically that I have to look into ?

**Comment by deniszh** [comment]
carbon internal metrics are always reading from disk (by design), so, that's not the case.
Sorry, nothing specific coming to my mind. TBH I doubt that downgrade will help, looks like a configuration issue to me - but please let me know if it's really the case - i.e. same config and carbon-c-relay works with 1.1.2 and do not works with 1.1.3 - carbon changes there are quite minimal...

**Comment by JosephFY** [comment]
Sorry got really busy and couldn't get back to this.
So one thing I missed on my side and one strange (maybe not documented) behavior that I wasn't expecting.

So the delays were NOT on the actual metrics we are sending, there were only with carbon metrics, I was just assuming carbon metrics are treated like the other metrics.

So I had my carbon prefix different than default, and I was seeing the delays on those metrics. So having `CARBON_METRIC_PREFIX` in `local_settings.py ` made me suspicious to change it also here, one I did the delays are gone and everything was good after.

But that does not reflect your statement of:
> carbon internal metrics are always reading from disk (by design)

Meaning I should not see the delays in the first place with the internal metrics.
