### ISSUE TITLE
Metrics do no contain all tags (graphite-web 1.1.1; carbon 1.1.3)

### ISSUE THREAD

**Issue by calebtote** [graphite-project/carbon#763]
No custom tags are associated with metrics when polling a series that's been tagged (unless I'm just misunderstanding how to use the feature).

`curl -vv -X POST "http://10.19.1.1:8080/tags/tagSeries" --data-urlencode 'path=dev.stats.responses.OK.calls.p99;env=qa-dev'`

Then if I do: `curl -vv "http://10.19.1.1:8080/tags/findSeries?pretty=1&expr=env=dev"`, I get what I'd expect as output:

```
[
  "dev.stats.responses.OK.calls.p99;env=dev"
* Connection #0 to host 10.19.118.17 left intact
]
```

However, when querying this series:
`curl "http://10.19.1.1:8080/renderer?target=dev.stats.responses.OK.calls.p99&format=json"`

The only `tag` returned is `name:`:

`[{"datapoints": [[0.01, 1523203920], [0.01, 1523203980], [0.01, 1523204040], [...], [null, 1523289900], [null, 1523289960], [null, 1523290020], [null, 1523290080], [null, 1523290140], [null, 1523290200], [null, 1523290260]], "target": "dev.stats.responses.OK.calls.p99", "tags": {"name": "dev.stats.responses.OK.calls.p99"}}]`

**Comment by DanCech** [comment]
That isn't how the tagging system works.  The tagSeries API is used by carbon when it receives metrics that include tags.  There is not currently a mechanism to add "extra" tags to existing series, though that is something I have been thinking about.

http://graphite.readthedocs.io/en/latest/tags.html

**Comment by calebtote** [comment]
I'm confused on the wording of this section of the documentation: http://graphite.readthedocs.io/en/latest/tags.html#adding-series-to-the-tagdb

Specifically:

> Series can be submitted via HTTP POST using command-line tools such as `curl` or with a variety of HTTP programming libraries.
> 
> `$ curl -X POST "http://graphite/tags/tagSeries" 
>   --data-urlencode 'path=disk.used;rack=a1;datacenter=dc1;server=web01'`
> 
> `"disk.used;datacenter=dc1;rack=a1;server=web01"`
> 
> This endpoint returns the canonicalized version of the path, with the tags sorted in alphabetical order.

The way it's written makes it appear as though adding tags to existing series is possible (especially considering the POST doesn't include a metric value or timestamp, just a series).

**Comment by DanCech** [comment]
The command in the documentation adds the path `disk.used;rack=a1;datacenter=dc1;server=web01` to the index.

Your `/tags/findSeries` call consults the index and returns the entry (because you just added it).

If you do a call to:

```
curl "http://10.19.1.1:8080/tags/findSeries?pretty=1&expr=name=dev.stats.responses.OK.calls.p99"
```

You'll get 2 results back; one for `dev.stats.responses.OK.calls.p99` and one for `dev.stats.responses.OK.calls.p99;env=qa-dev`.

> When using tag support, each series is uniquely identified by its name and set of tag/value pairs.

The series `dev.stats.responses.OK.calls.p99;env=qa-dev` has the same `name` as the series `dev.stats.responses.OK.calls.p99` but it is a *different* series.
