### ISSUE TITLE
carbon-aggregator-cache.py does not read correct config

### ISSUE THREAD

**Issue by stan-sack** [graphite-project/carbon#764]
https://github.com/graphite-project/carbon/blob/master/lib/carbon/conf.py

on line 615: `section = program[len("carbon-"):]`

This will search carbon.conf for config [aggregator-cache] when we actually want to read configs for both [aggregator] and [cache].

**Comment by deniszh** [comment]
Yes, looks like a bug

**Comment by AsenZahariev** [comment]
Hey is there any development regarding this ?

**Comment by deniszh** [comment]
No, not at the moment, unfortunately. You can create a section named ` [aggregator-cache]` and copy your parameters there as a workaround.

**Comment by AsenZahariev** [comment]
That's more than enough for me. Just to clarify , copying the parameters from both cache and aggregation into [aggregator-cache] section or just the aggregation ?

**Comment by deniszh** [comment]
Both will be more explicit.
