### ISSUE TITLE
Latest change in storage-aggregation.conf.example breaks statsd counters

### ISSUE THREAD

**Issue by antonsoroko** [graphite-project/carbon#768]
Previously for counters aggregationMethod was sum, now it is max
https://github.com/graphite-project/carbon/commit/e4953da4a37c07177fdccb1abda3679e017a83e8

This is good for use case described in https://answers.launchpad.net/graphite/+question/286462 but wrong for statsd counters which are reset every (statsd) flush interval.

Maybe it would be more reasonable to add a comment to the storage-aggregation.conf.example about which of `aggregationMethod` is suitable for different `counter` use cases.

What do you think?

**Comment by DanCech** [comment]
That sounds like a good idea, and would clear up confusion about counters that reset every interval (statsd-style) vs counters that accumulate over time (snmp-style).
