### ISSUE TITLE
Suggest using whisper-resize in storage-schemas.conf

### ISSUE THREAD

**Issue by helmo** [graphite-project/carbon#775]
When changing retention settings it's not directly obvious that you need to manually resize all data files.

I suggest adding a note to 
https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example

While looking into this I found that #379 had also been looking for this info.

The documentation does mention this:
> This retention is set at the time the first metric is sent.
> Changing this file will not affect already-created .wsp files. Use whisper-resize.py to change those.

And I found a few command suggestions in https://gist.github.com/kirbysayshi/1389254

**Comment by deniszh** [comment]
Thanks!
PRs are welcome, btw. :)
