### ISSUE TITLE
mod_wsgi is using 100% cpu when carbon-relay is started

### ISSUE THREAD

**Issue by flowppp** [graphite-project/carbon#776]
Hi 
I'm using graphite 1.2, django 1.11.12, Apache/2.4.6, mod-wsgi 4.5.24. redhat 7 in a virtual env
I'm facing a weird issue since i have implemented carbon-relay.
When graphite is started and carbon-relay are running at the same time, wsgi process are going crazy and are using 100% cpu. 
I did a strace during this and it appears that wsgi process are continuously doing lseek/read on file /opt/graphite/storage/graphite.db

here is the carbon.conf
[cache]
GRAPHITE_URL = http://127.0.0.1:81
#GRAPHITE_STORAGE_DIR = /var/lib/graphite/
#GRAPHITE_ROOT  = /opt/graphite/
#CONF_DIR       = /etc/carbon/
#LOG_DIR        = /var/log/carbon/
#PID_DIR        = /var/run/carbon/

LOG_UPDATES = False
#WHISPER_AUTOFLUSH = True
USE_WHITELIST = False
#USER = apache
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 100000
MAX_CREATES_PER_MINUTE = 600
MAX_DATAPOINTS_PER_MESSAGE = 50000
MAX_QUEUE_SIZE = 1300000
USE_FLOW_CONTROL = True
LINE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
CACHE_QUERY_INTERFACE = 127.0.0.1
CACHE_WRITE_STRATEGY = naive

[cache:a]
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_PORT = 2024
CACHE_QUERY_PORT = 7022
MAX_CACHE_SIZE = inf

[cache:b]
LINE_RECEIVER_PORT = 2033
PICKLE_RECEIVER_PORT = 2034
CACHE_QUERY_PORT = 7032
MAX_CACHE_SIZE = inf

[cache:c]
LINE_RECEIVER_PORT = 2043
PICKLE_RECEIVER_PORT = 2044
CACHE_QUERY_PORT = 7042
MAX_CACHE_SIZE = inf

[cache:d]
LINE_RECEIVER_PORT = 2053
PICKLE_RECEIVER_PORT = 2054
CACHE_QUERY_PORT = 7052
MAX_CACHE_SIZE = inf

[cache:e]
LINE_RECEIVER_PORT = 2063
PICKLE_RECEIVER_PORT = 2064
CACHE_QUERY_PORT = 7062
MAX_CACHE_SIZE = inf

[cache:f]
LINE_RECEIVER_PORT = 2073
PICKLE_RECEIVER_PORT = 2074
CACHE_QUERY_PORT = 7072
MAX_CACHE_SIZE = inf

[relay]
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 5020
RELAY_METHOD = consistent-hashing
max_queue_size = 900000
DESTINATION_PROTOCOL = pickle
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2024:a, 127.0.0.1:2034:b, 127.0.0.1:2044:c, 127.0.0.1:2054:d, 127.0.0.1:2064:e, 127.0.0.1:2074:f

graphite-vhost.conf

<IfModule !wsgi_module.c>
    LoadModule wsgi_module /opt/graphite/lib/python2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so
#LoadModule wsgi_module modules/mod_wsgi.so
</IfModule>

# XXX You need to set this up!
# Read http://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGISocketPrefix
# For example, create a directory /var/run/wsgi and use that.
WSGISocketPrefix run/wsgi

<VirtualHost *:81>
        ServerName graphite
        DocumentRoot "/opt/graphite/webapp"
        ErrorLog /opt/graphite/storage/log/webapp/error.log
        CustomLog /opt/graphite/storage/log/webapp/access.log common

        # I've found that an equal number of processes & threads tends
        # to show the best performance for Graphite (ymmv).
        WSGIDaemonProcess graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
        WSGIProcessGroup graphite
        WSGIApplicationGroup %{GLOBAL}
        WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite application-group=%{GLOBAL}
        # XXX You will need to create this file! There is a graphite.wsgi.example
        # file in this directory that you can safely use, just copy it to graphite.wgsi
        WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi

        # XXX To serve static files, either:
        # * Install the whitenoise Python package (pip install whitenoise)
        # * Collect static files in a directory by running:
        #     django-admin.py collectstatic --noinput --settings=graphite.settings
        #   And set an alias to serve static files with Apache:
        Alias /static/ /opt/graphite/static/

        ########################
        # URL-prefixed install #
        ########################
        # If using URL_PREFIX in local_settings for URL-prefixed install (that is not located at "/"))
        # your WSGIScriptAlias line should look like the following (e.g. URL_PREFX="/graphite"

        # WSGIScriptAlias /graphite /srv/graphite-web/conf/graphite.wsgi/graphite
        # Alias /graphite/static /opt/graphite/webapp/content
        #  <Location "/graphite/static/">
        #        SetHandler None
        # </Location>

        # XXX In order for the django admin site media to work you
        # must change @DJANGO_ROOT@ to be the path to your django
        # installation, which is probably something like:
        # /usr/lib/python2.6/site-packages/django
        Alias /media/ "@DJANGO_ROOT@/contrib/admin/media/"

        # The graphite.wsgi file has to be accessible by apache. It won't
        # be visible to clients because of the DocumentRoot though.
        <Directory /opt/graphite/>
                <IfVersion < 2.4>
                        Order deny,allow
                        Allow from all
                </IfVersion>
                <IfVersion >= 2.4>
                        Require all granted
                </IfVersion>
        </Directory>

</VirtualHost>

Any idea?
Thanks
Flo

**Comment by deniszh** [comment]
Are you using graphite events and/or tags? 
Also please note that SQLite storage is not designed for production usage, please migrate to proper database (PostgreSQL or MySQL)

**Comment by flowppp** [comment]
Ok, i created the directory /var/run/wsgi with apache user as owner, it changes nothing, and i don't see any files in the directory.
Did i miss something?
And why carbon-relay would change something there?
@Deniszh no i don't want use it, but looks like that graphite try to use it and i did not find the way to disable it.
Thanks Guys

**Comment by flowppp** [comment]
Any hint?
graphite running along no problem, then i start carbon-relay and everything is going wrong with wsgi

**Comment by deniszh** [comment]
>Ok, i created the directory /var/run/wsgi with apache user as owner, it changes nothing, and i don't see any files in the directory.
Did i miss something?

Sorry, not sure why you doing that.

> And why carbon-relay would change something there?
It's not.

> no i don't want use it, but looks like that graphite try to use it and i did not find the way to disable it.
There's a way - please put `TAG_DB=None` in local_settings.py and restart web server - that should help.

**Comment by flowppp** [comment]
Ok, so i disable tagging from carbon.conf with : 
ENABLE_TAGS = FALSE 
and by removing : 
GRAPHITE_URL = http://127.0.0.1:81

And It works now. I don't understand how this kind of incompatibility could be....

Why that "Ok, i created the directory /var/run/wsgi with apache user as owner, it changes nothing, and i don't see any files in the directory.
Did i miss something?" <--my post 
has been modified with this -->
"XXX You need to set this up!
Read http://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGISocketPrefix
For example, create a directory /var/run/wsgi and use that.
WSGISocketPrefix run/wsgi"

**Comment by flowppp** [comment]
ok finally i understood (i think)......Carbon was sending tagging information to graphite and as the tagging configuration was not done correctly i was falling in this situation.

**Comment by deniszh** [comment]
Thanks, we should amend documentation to clearly state that.
