### ISSUE TITLE
Failure to indicate dropped metrics

### ISSUE THREAD

**Issue by mwtzzz** [graphite-project/carbon#781]
I'm doing some benchmarking of different EBS configurations in order to determine the optimal configuration for my graphite installation. I've come across a puzzling thing: 

I had a carbon-cache host writing to a set of GP2 disks in a Raid10 configuration. This was doing a total of about 40MB/s write throughput with 5,000 IOPS (as shown by cloudwatch). `carbon.agents.metricsReceived` was showing 1,900K/minute. `carbon.agents.committedPoints` was showing also about 1,900K/minute (this would fluctuate up and down). 

I reconfigured the drives as HDD ST1. The write throughput is now 2,000K with 500 IOPS. `metricsReceived` is still at 1,900K, but `committedPoints` is now only 200K.

I should expect that many of the metrics are no longer being written to disk, but I cannot find evidence of this. `carbon.agents.errors` is 0. `carbon.agents.cache.overflows` is 0. 

Is there some way to verify that metrics are not being written? I'm assuming that carbon-cache is dropping/discarding them after some threshold is reached?

**Comment by mwtzzz** [comment]
I noticed that the internal metrics (carbon.agents) haven't been updated in a while and the percentage of used RAM has been slowly growing, so I assume this means incoming metrics are collecting in RAM and not making it to disk. At some point this should generate an OOM event, I suppose?

**Comment by deniszh** [comment]
> At some point this should generate an OOM event, I suppose?

If you not limit cache size - yes. Or it will start throwing metric out - then overflows will increase.

**Comment by mwtzzz** [comment]
That's what I was thinking. Except there wouldn't be any way to see whether overflows increase since its own metrics aren't getting written.

**Comment by mwtzzz** [comment]
@deniszh If it starts throwing metrics out, will it log this fact?

**Comment by mwtzzz** [comment]
Another question: is there a way to calculate the expcected amount of data that will be written to disk based on the number of `metricsReceived`? Assuming these are update operations, is it a static amount of disk throughput for each?

**Comment by deniszh** [comment]
>If it starts throwing metrics out, will it log this fact?

Not sure. Overflow counter will increase, though.

> is there a way to calculate the expcected amount of data that will be written to disk based on the number of metricsReceived? 

If you not using sparse files - yes. Whisper files are preallocated, so, every new metric will create a new file of fixed size. After preallocation updates are not consuming extra space, so, space are consuming new metrics only, and not received metrics.

**Comment by deniszh** [comment]
PS: for sparse files that's not true - but it's quite hard to calculate that. It's much easier to monitor and predict.

**Comment by mwtzzz** [comment]
Actually I meant, after all the metrics have been created, how expense are updates?

**Comment by deniszh** [comment]
By default Whisper is preallocating, so, no expense by size.

**Comment by mwtzzz** [comment]
Sorry I should be more clear, i'm trying to calculate the expected disk i/o based on number of received metrics, for simplicity assuming all metric files already exist on disk. I read that each update would be about 12 bytes that gets written to disk?

**Comment by deniszh** [comment]
Bytewize - yes, it's 12 bytes per metric per archive. But IMO it's almost impossible to properly convert it to iopses, it's very indeterministic.

**Comment by mwtzzz** [comment]
Thanks for the info Denis!
