### ISSUE TITLE
Is it necessary to stop/start carbon-cache when using whisper-resize ?

### ISSUE THREAD

**Issue by mwtzzz** [graphite-project/carbon#783]
Quick and easy question: Is it necessary to stop/start carbon-cache when using whisper-resize?

I couldn't actually find any documentation that addressed this.

**Comment by mwtzzz** [comment]
Thought about it and looked into it a bit. I'm pretty sure there's no need to restart. It shouldn't be keeping whisper files open any longer than it needs to write to them (which is born out by looking at lsof). It doesn't make sense that it would try to keep potentially millions of files open all the time. I think it's a good assumption to say that it reloads each .wsp file and figures out its retention/schema each time it needs to access it.

**Comment by deniszh** [comment]
Yes, it should work exactly like you described.

**Comment by piotr1212** [comment]
It should be safe to run resize with a running cache, resize works as following:

1. whisper-resize writes to the resized data to a new tempfile. 
2. whisper-resize renames the original to .bak
3. whisper-resize renames the new file to the original name.

There is a potential race condition if the cache recreates a whisper file between step 2 and 3, but then resize should bail out with an exception and you still have the .bak file. I've never run into this.

**Comment by mwtzzz** [comment]
It's working perfectly without needing to restart cache. Thanks for the info.
