### ISSUE TITLE
Enable UDP Listerner - Multiple Carbon Cache Daemon

### ISSUE THREAD

**Issue by rgleme** [graphite-project/carbon#785]
Hello

I know it is not the best practice, but with the following configuration:

[relay]
USER = nginx
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
MAX_QUEUE_SIZE = 10000
MAX_DATAPOINTS_PER_MESSAGE = 1000
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 1
DESTINATIONS = 127.0.0.1:2014:1, 127.0.0.1:2024:2, 127.0.0.1:2034:3, 127.0.0.1:2044:4, 127.0.0.1:2054:5

[cache]
ENABLE_LOGROTATION = True
USER = nginx
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
GRAPHITE_URL = http://graphite.uolhost.intranet/
**ENABLE_UDP_LISTENER = True**
LINE_RECEIVER_INTERFACE = 127.0.0.1
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
CACHE_QUERY_INTERFACE = 127.0.0.1
LOG_UPDATES = True
LOG_CREATES = True
LOG_CACHE_HITS = True
LOG_CACHE_QUEUE_SORTS = True
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False
USE_WHITELIST= False

[cache:1]
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7012

[cache:2]
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
LINE_RECEIVER_PORT = 2023
PICKLE_RECEIVER_PORT = 2024
CACHE_QUERY_PORT = 7022

[cache:3]
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
LINE_RECEIVER_PORT = 2033
PICKLE_RECEIVER_PORT = 2034
CACHE_QUERY_PORT = 7032

[cache:4]
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
LINE_RECEIVER_PORT = 2043
PICKLE_RECEIVER_PORT = 2044
CACHE_QUERY_PORT = 7042

[cache:5]
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 25000
MAX_CREATES_PER_MINUTE = 21500
LINE_RECEIVER_PORT = 2053
PICKLE_RECEIVER_PORT = 2054
CACHE_QUERY_PORT = 7052

Can I enable UDP Listener on all cache daemon ? How ?

In this situation, only cache daemon1 starts. Others try to bind on 2003 port.

Thank you in advance

**Comment by DanCech** [comment]
set UDP_RECEIVER_PORT for each cache instance

**Comment by rgleme** [comment]
nevermind

ENABLE_UDP_LISTENER = True was needed on [relay] options.

Now it works as expected
