### ISSUE TITLE
Memory leak when CARBON_METRIC_INTERVAL = 0

### ISSUE THREAD

**Issue by DanCech** [graphite-project/carbon#786]
If you set `CARBON_METRIC_INTERVAL = 0` in the carbon config the metrics will never be flushed and the list of update times will grow unbounded.

`carbon` should handle this case by adding a task to periodically flush the accumulated timers if the metrics are not going to be reported.  It doesn't seem like we can stop collecting them altogether in this case, as the stats are also used in `client.py`.

Until this is fixed, the workaround is to set `CARBON_METRIC_INTERVAL` to a value higher than `0`, with the default of `60` being the recommended value.

**Comment by yogeshgangurde** [comment]
Thank you @DanCech 

I had encountered  same issue and workaround to set CARBON_METRIC_INTERVAL to value of 60 helped me.
