### ISSUE TITLE
`sorted` strategy is sorting backward?

### ISSUE THREAD

**Issue by lexelby** [graphite-project/carbon#788]
Please pardon my ignorance if I have the wrong understanding of how all this works.

I'm trying to debug a performance issue in my graphite setup, and in doing so, I discovered something that seemed strange to me.  The sorted strategy's docstring says that it prefers metrics with more data points.  However, it sorts the list of metrics by the number of data points: https://github.com/graphite-project/carbon/blob/master/lib/carbon/cache.py#L104

Sorting in this way will produce a list going from fewer to more data points.  Is `reverse=True` necessary here?  Or am I misunderstanding the meaning of "prefer"?

**Comment by piotr1212** [comment]
Not sure. but doesn't .pop() work from the back of the list?
https://github.com/graphite-project/carbon/blob/master/lib/carbon/cache.py#L109

**Comment by lexelby** [comment]
Bah.  Yes, that was the missing piece.  Thank you! :)
