### ISSUE TITLE
package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)

### ISSUE THREAD

**Issue by m2cci-KGY** [graphite-project/carbon#791]
Hi
I'm installing carbon the module of graphite so  when I make this commands "python setup.py install" 
I have this error.
package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)

So before, I installed the carbon module I install all package of twisted 
I need your help to resolve my problem.
Thank you.

**Comment by deniszh** [comment]
Looks similar to https://github.com/graphite-project/carbon/issues/128 but there was very old `pip` and/or `grapjhite`.
Which OS are you using, @m2cci-KGY ? and what `pip --version` command says?

**Comment by m2cci-KGY** [comment]
I don't install carbon with pip but from the sources by python "setup.py install". so my VM is a DMZ machine. and I read the #128 I don't andersand his way to  fix the error.
Thank you.

**Comment by deniszh** [comment]
Looks like `package init file 'lib/twisted/plugins/__init.py__' not found (or not a regular file)` is not an error, but warning. Carbon should work despite that warning.

**Comment by piotr1212** [comment]
That warning is known and should be ignored. see https://stackoverflow.com/questions/7275295/how-do-i-write-a-setup-py-for-a-twistd-twisted-plugin-that-works-with-setuptools?answertab=active#tab-top
