### ISSUE TITLE
When size of the pickle message contains roughly around 50 data points , carbon silently drops the message 

### ISSUE THREAD

**Issue by tidthomas** [graphite-project/carbon#794]
I am new to carbon/graphite.  My data collector is written in  c#  and I am using pickle to feed data into carbon.  When the message contains around 50 data points carbon is dropping the message but smaller pickled frames are working correctly.  Is there a way to configure the  pickle message-size through carbon conf or through Code. Thanks  (4096 is Max length allowed)

**Comment by DanCech** [comment]
If you're using UDP you could try switching to TCP, you may be running into MTU issues with the larger UDP packets.

**Comment by piotr1212** [comment]
I don't think Pickle receiver is listening on UDP. The MAX_LENGTH is configured to [1mb](https://github.com/graphite-project/carbon/blob/master/lib/carbon/protocols.py#L212) but I don't see how 50 metrics can reach that limit.

**Comment by tidthomas** [comment]
Carbon is installed on an Ubuntu box
-------------------------------------------------------------
I am using TCP to send the pickled data. TCP Configurations are as follows in the Linux Box where carbon is installed 
- cat /proc/sys/net/ipv4/tcp_wmem
- 4096    16384   4194304
- cat /proc/sys/net/ipv4/tcp_rmem
- **4096    87380   6291456**
- cat /proc/sys/net/ipv4/tcp_mem
- **23004   30674   46008**

Unfortunately  no exceptions in listener.log of console.log

**my Carbon Conf.**
LOCAL_DATA_DIR = /var/lib/graphite/whisper
ENABLE_LOGROTATION = True
USER = _graphite
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 500
MAX_CREATES_PER_MINUTE = 50
LINE_RECEIVER_INTERFACE = 0.0.0.0
LINE_RECEIVER_PORT = 200
ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 0.0.0.0
UDP_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
LOG_LISTENER_CONNECTIONS = True
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 0.0.0.0
CACHE_QUERY_PORT = 7002
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = True

We are not using Relay or Aggregator service. I am assuming that when the data frame length exceeds 4096 its not reaching the **MetricPickleReceiver in protocols.py.  I can see max length is defined as  MAX_LENGTH = 2 ** 20 in that method.** 

however when pickled data length is less than 4096 its working perfectly via TCP.

**Comment by piotr1212** [comment]
I cannot reproduce this. I just successfully sent messages up to approximately 1mb.

```
In [55]: def send_metrics(n):
    ...:     t = []
    ...:     for i in range(n):
    ...:         t.append(('{}'.format(i), (float(i), int(time.time()))))
    ...:     package = pickle.dumps(t, 1)
    ...:     size = struct.pack('!L', len(package))
    ...: 
    ...:     sock = socket.socket()
    ...:     sock.connect(('10.0.0.17', 2004))
    ...:     sock.sendall(size)
    ...:     sock.sendall(package)
    ...:     sock.close()
    ...:     print('size in bytes (minus the int32 prefix) {}'.format(len(package)))
    ...: 
```
And when sending packages larger than 1 mb the connection gets close cleanly (according to the logs).

ps. Is there any particular reason why you need to use pickle?

**Comment by tidthomas** [comment]
Thank you for your response, Pickle is working very well. Issue was with our firewall configuration it was dropping packets when it exceeds 1024*4 .
