### ISSUE TITLE
carbon-cache memory leak when put under LB

### ISSUE THREAD

**Issue by rmrf** [graphite-project/carbon#810]
Recently we put our  graphite service under Load Balance, then seeing lots of log as bellow, the IP address here are from LB connection, carbon-cache process memory increasing slowly and finally OOM, 
suspect the LB short connection which making carbon-cache memory leak. 

```
n.
09/09/2018 05:06:34 :: [listener] MetricLineReceiver connection with 192.117.87.3:41731 lost: Connection to the other side was lost in a non-clean fashio
n.
09/09/2018 05:06:34 :: [listener] MetricLineReceiver connection with 192.117.87.131:8879 lost: Connection to the other side was lost in a non-clean fashi
on.
09/09/2018 05:06:34 :: [listener] MetricLineReceiver connection with 192.97.72.130:42744 lost: Connection to the other side was lost in a non-clean fashi
on.
```

**Comment by deniszh** [comment]
@rmrf : It can be non-related carbon memory can grow above the limit if not configured properly.
What's your metric flow? 
How many carbon-caches are you running? 
Could you please share carbon config?

**Comment by piotr1212** [comment]
Are you sure it is caused by the lost connections? Can you reproduce this on a carbon with LB without any actual metrics? Which Twisted and Python version are you using?
