### ISSUE TITLE
Tagging causing important performance issues?

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/carbon#816]
I'm not really sure where to start, the bottomline is : it seems since tagging was added in carbon my project is suffering significant performance impact.

Now, I'm not really sure I'm understanding this correctly : I do not use tagging, meaning, the daemon injecting data into carbon do not use the tagging syntax, so I expected disabling tagging wouldn't help, but it apparently did.

Before disabling tagging, carbon logs were flooded with `Error tagging...` message, consuming a lot of space and i/o (yes `GRAPHITE_URL` is defined correctly, but getting `Error response 500 from http://127.0.0.1:81/graphite/tags/tagMultiSeries` kind of messages)

Is that so, that even if you do not make use of tagging, every single series is tentatively added to the tagging database?
In large environments, running multiple carbon instances, would that cause locking and performance issues?

I was wondering if it wouldn't make sense to have `ENABLE_TAGS = False` by default.

Thanks for your time enlightening me!

**Comment by DanCech** [comment]
It sounds like you don't have your graphite-web install set up properly, likely because you didn't run the database migrations after upgrading.  The only difference as far as carbon is concerned with the ENABLE_TAGS flag is that when enabled it starts a separate thread that updates the tag database in graphite-web, and the only difference in the "normal" path is that series are added to the queue that feeds that thread.

**Comment by ybizeul** [comment]
Thanks Dan,

Would the following query work then? It seems graphite-web has all the required db components.

```
curl http://127.0.0.1:81/graphite/tags?pretty=1
[
  {
    "id": 1, 
    "tag": "name"
  }
]
```

Ok, so that separate thread tries to put every single series in the database, performing tagMultiSeries by bunch until everything is in the tag database?

In my case it gets a 500 error, but querying tag list works fine.

I have 8 carbon thread running, does each carbon cache runs its own separate thread to feed tag database? How about locking and concurrency, it should work just fine? We're probably talking about tenth thousands os series here.

**Comment by DanCech** [comment]
That all sounds like it should be working fine.  Each carbon instance will run its own thread to feed the tagdb, you'll definitely want to start looking at the logs to figure out why the tagdb would be returning 500.

**Comment by deniszh** [comment]
Well. I was not aware that we're updating tagdb even in tagging is not in use. I  can be really a problem - tagdb over sqlite is very slow, over mysql/postgresql - quite slow, only redis is working fine with significant load IMO.
But I do not think that we need to disable tagging - IMO it's better to make it not touch tagdb if metric has no tags. Will try check if it's possible/easy to implement.

**Comment by DanCech** [comment]
It would be relatively easy to have carbon not write metrics without tags to the tagdb, `writeCachedDataPoints` would need to avoid adding them to the tag queue.

**Comment by sbarrier** [comment]
I'm using graphite-web 1.1.5 with 4 carbon cache and having similar issue with tagdb.

tagdb work for list and even POST but on busy server it mostly fail with an error 500
for /tags/tagMultiSeries which is result of "error": "database is locked".

Looking at carbon logs it look like the read timeout is reached.

```Error requesting http://graphite/tags/tagMultiSeries: HTTPConnectionPool(host='graphite', port=80): Max retries exceeded with url: /tags/tagMultiSeries (Caused by ReadTimeoutError("HTTPConnectionPool(host='graphite', port=80): Read timed out. (read timeout=5)",))```

**Comment by deniszh** [comment]
Hello @sbarrier ,
Try to increase TAG_UPDATE_INTERVAL to 1000 or even more, or migrate to RDBMS or even Redis. Redis is fastest.
Or you can disable tags overall if not used, with ENABLE_TAGS=False

**Comment by piotr1212** [comment]
> tagdb work for list and even POST but on busy server it mostly fail with an error 500
for /tags/tagMultiSeries which is result of "error": "database is locked".

Are you using sqlite? I think that only supports table locking so that would explain that.

**Comment by sbarrier** [comment]
@deniszh ENABLE_TAGS=False work that how i run it actually
i tried to increase TAG_UPDATE_INTERVAL to 1000 and 10000 but that don't help.

@piotr1212 yes it's default backend setup with sqlite

**Comment by alespour** [comment]
@sbarrier  I had the same error `Read timed out. (read timeout=5)`, switching to Redis did not help. It disappeared when I configured uwsgi to have as many processes as I had carbon-cache instances.

**Comment by alexmaccabi** [comment]
Had the same issue, with the tags. 
/graphite/tags/ URI got 500 
ENABLE_TAGS = False didn't help
my only solution was 
TAGDB=None

**Comment by abbas-gadhia** [comment]
I'm facing the exact same issue. Took me a good 2 days to figure out why i was able to send metrics to graphite via nc but not via micrometer and dropwizard.io.
As a newbie, I used the default docker image from the website and pointed my micrometer registry at it. Below is the error i got for a simple hello world.

`09/02/2021 16:00:34 :: [tagdb] Error tagging tests.timings.hello.world;metricattribute=p95, tests.timings.hello.world;metricattribute=p75, tests.timings.hello.world;metricattribute=p50, tests.timings.hello.world;metricattribute=stddev, tests.timings.hello.world;metricattribute=min, tests.timings.hello.world;metricattribute=mean, tests.timings.hello.world;metricattribute=max: Error requesting http://127.0.0.1:8080/tags/tagMultiSeries: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)`
