### ISSUE TITLE
whisper files created with no permissions

### ISSUE THREAD

**Issue by mleinart** [graphite-project/carbon#82]
#### Imported from https://bugs.launchpad.net/bugs/702066
|||
|----|----|
|Reported by|[pete-appnexus](https://launchpad.net/~pete-appnexus)|
|Date Created|Jan 12, 2011|
I'm using carbon-relay (Graphite-0.9.6) to send metrics from one server to another.

Currently, I populate a metric on one server, and it looks fine in the browser.

I look on the other server, and I get this:

Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/django/core/handlers/base.py", line 86, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 97, in renderView
    seriesList = evaluateTarget(target, timeInterval)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 14, in evaluateTarget
    result = evaluateTokens(tokens, timeInterval)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 30, in evaluateTokens
    return evaluateTokens(tokens.expression, timeInterval, originalTime)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 43, in evaluateTokens
    dbResults = dbFile.fetch( timestamp(startTime), timestamp(endTime) )
  File "/opt/graphite/webapp/graphite/storage.py", line 232, in fetch
    (timeInfo,values) = whisper.fetch(self.fs_path, startTime, endTime)
  File "/usr/lib/python2.4/site-packages/whisper.py", line 462, in fetch
    fh = open(path,'rb')
IOError: [Errno 13] Permission denied: '/opt/graphite/storage/whisper/path/to/my/metric.wsp'

The permissions on the file are 0000 instead of 0644 as I'm seeing on the source server.

The directory used for this is a 20GB tmpfs, although I'm not sure that should play into it.

Have you seen anything like this before, and can you help me track this down?

Thanks,
Pete

**Comment by JensRantil** [comment]
Any progress on this? Just hit this bug...

**Comment by deniszh** [comment]
https://github.com/graphite-project/carbon/issues/82#issuecomment-52194451

**Comment by jacobrichard** [comment]
Sorry there hasn't been movement on the twisted patch in awhile, I'm the one that tracked it down and have been working on it -- I havent had the time to see it through to the end. The twisted people want me to jump through a bunch of hoops that I do not have time to jump through at the moment. To get the patch all the way through into the trunk, they seem to want unit tests and regression tests the code lacked to begin with, as well as documenting the difficulty of producing the bug, etc. 

Alternatively, I'd suggest writing a monkey patched logger with the updated code. Thats what im using on my private graphite instance (as well as other code using twisted.python.logfile), and I have run into no issues, aside from the obvious dirtiness of doing it that way.

**Comment by JensRantil** [comment]
@jacobrichard Ok. Thanks for the update!

**Comment by obfuscurity** [comment]
@jacobrichard How ugly would the patch be against Carbon?

**Comment by jacobrichard** [comment]
@obfuscurity This is the commit that would be required. I wouldn't advise pulling it in without some testing. My existing patch was against a much older version of carbon that seemed to have some syntax changes. I modified it and dropped it in a fork of the newest carbon version from master, and I'm testing it a bit right now.

https://github.com/jacobrichard/carbon/commit/c3502caef98c45b76886534a3a7d5f68f695a440

**Comment by obfuscurity** [comment]
That doesn't look too painful. I'll take a look this weekend and see about putting together a working PR. Thanks.

**Comment by obfuscurity** [comment]
This should be fixed now. If you try HEAD from master or 0.9.x and the problem still exists, please let us know. Thanks to everyone who participated in this issue for their patience and support.
