### ISSUE TITLE
Documentation is very unclear on regex pattern of storage-schemas.conf

### ISSUE THREAD

**Issue by cminnoy** [graphite-project/carbon#821]
Problem:
Unclear rules of the regular expression, lacking documentation
Expected:
Clear explanation in the documentation on what the meaning is of ^, *, \ ( ) .
Solution:
Enhance carbon documentation to a professional level

**Comment by deniszh** [comment]
I am agreed that documentation should be improved, but do not think that we need to explain the meaning of regex symbols - link to some regex documentation, mentioning which regex flavor Graphite uses and possibly link to some online regex testbed will be enough.

**Comment by piotr1212** [comment]
I would assume the intended audience, sysadmins and developers, are familiar with basic regexes as this is part of any entrance level sysadmin or programming training.
