### ISSUE TITLE
why  carbon-aggregate  cost CPU so much

### ISSUE THREAD

**Issue by idling11** [graphite-project/carbon#833]
Hi ,all
I use  carbon-aggregate to receive data and  make a  aggregation.  There is a lot of  metrics  sent to  carbon-aggregate  deamon and I  found  carbon-aggregate CPU usage  is  nearly  100% .  what confused me 
is that when  increase the amount of  metrics ,   carbon-aggregate seems like   can`t   have the  ability  to  process them。

can someone  explain this ?  Appreciate it 

thanks

Hanmiao Li

**Comment by piotr1212** [comment]
Aggregation costs CPU, if you send more metrics than it can handle it will drop metrics. If you have multiple cores you could run multiple aggregators with a relay in front of it to load balance the metrics.
