### ISSUE TITLE
performance issue :  v0.9.16 vs v1.1.5

### ISSUE THREAD

**Issue by hamelg** [graphite-project/carbon#839]
Hello,

We have 2 carbons-cache running on identical hardware with the same setup.
One is running version 0.9.16 and the other the latest version in a docker image found at  https://github.com/graphite-project/docker-graphite-statsd.
We are very happy with the performance of the v0.9.16, but not with v1.1.5.

Here are some performance graph.

**v0.9.16**
![screenshot_2019-02-11 grafana - puits2 1](https://user-images.githubusercontent.com/9417309/52590369-65f7c780-2e41-11e9-8127-b421dc1e7776.png)
![screenshot_2019-02-11 grafana - puits2 2](https://user-images.githubusercontent.com/9417309/52591520-7198bd80-2e44-11e9-86dc-6d8f42b2ec35.png)
![screenshot_2019-02-11 grafana - linux 1](https://user-images.githubusercontent.com/9417309/52590376-6abc7b80-2e41-11e9-89df-fcdf463aca8e.png)

Here carbon-cache processes near 1000 updates op/s with less than 0.5 core.

**v1.1.5**
![screenshot_2019-02-11 grafana - puits2](https://user-images.githubusercontent.com/9417309/52590405-7ad45b00-2e41-11e9-90d8-25ca46d68555.png)
![screenshot_2019-02-11 grafana - puits2 3](https://user-images.githubusercontent.com/9417309/52591557-88d7ab00-2e44-11e9-9935-b6ea3652eb72.png)
![screenshot_2019-02-11 grafana - linux](https://user-images.githubusercontent.com/9417309/52590408-7c9e1e80-2e41-11e9-886f-989b64e95c07.png)

Here carbon-cache v1.1.5 is cpubound with less than 50 updates op/s !?

Here is the setup
[carbon.conf.txt](https://github.com/graphite-project/carbon/files/2852886/carbon.conf.txt)

On v1.1.15, we took profiling data with --profile but it gives us no meaning things.
[profile-v115.txt](https://github.com/graphite-project/carbon/files/2852890/profile-v115.txt)

Anybody to help me to understand these differences or to give me some hints to find out where is the issue ?
thank you.

**Comment by piotr1212** [comment]
try `ENABLE_TAGS = False` .

If it doesn't work it would be helpful if you could do some bisecting. Think 1.x got forked off about 3 years ago from 0.9 so the codebase is completely different.

**Comment by hamelg** [comment]
Tags are already disabled. Perhaps, the profiling would be helpfully but unfortunately I am unable to decode it. I wonder where the cpu is eaten ...

**Comment by deniszh** [comment]
@hamelg : 
Thanks for testing this, but results look very odd. 1.1.5 definitely works better than 50 ops/s.
Not sure what issue can be.
I need to think about how it can be reliably bisected...

**Comment by deniszh** [comment]
Well, just test latest release on my laptop with https://github.com/graphite-project/graphite-test-docker
Single carbon, 1000 metrics/s, cpu 20%, with enabled tags and very suboptimal storage.
<img width="1351" alt="screenshot 2019-02-12 at 10 50 40" src="https://user-images.githubusercontent.com/1227222/52626845-5e253b00-2eb4-11e9-9021-e957c07758cf.png">

That's why I barely can explain your results. Something is very off in your case, but I don't know what exactly.

**Comment by piotr1212** [comment]
Denis, from the trace it seems to be a concurrency issue, could you try
with more agents? Looks like the docker image does only 10 agents.

**Comment by deniszh** [comment]
Could be, but I'm afraid that a laptop can't handle that. :(
100 agents x 100 metrics (before it was 10 agents x 1000 metrics) providing the same result - 
<img width="1353" alt="screenshot 2019-02-12 at 14 35 03" src="https://user-images.githubusercontent.com/1227222/52638973-7b1d3680-2ed3-11e9-990e-3910ce11b234.png">

**Comment by hamelg** [comment]
I found out where is the issue, see https://github.com/graphite-project/carbon/issues/840.
Thanks much for you hints, I didn't know the graphite-test-docker project :)
