### ISSUE TITLE
CACHE_WRITE_STRATEGY=max triggers a high cpu usage

### ISSUE THREAD

**Issue by hamelg** [graphite-project/carbon#840]
The issue is described here :
https://github.com/graphite-project/carbon/issues/839

You can reproduce this bug on the latest release with https://github.com/graphite-project/graphite-test-docker.

In the container simple_graphite_1, replace this carbon setting :
CACHE_WRITE_STRATEGY=sorted
by
CACHE_WRITE_STRATEGY=max

then restart the carbon-cache service. Few minutes later, CPU is busy at 100%. 

The workaround is to not use CACHE_WRITE_STRATEGY=max.

**Comment by piotr1212** [comment]
Yeah, I see now... I added a lock in my last commit to fix other issues. Works fine for sorted as it locks around an iterator which is only O(1). But didn't notice that in the max strategy this locks max() which is O(n). 0.9.x doesn't lock at all, no clue how that could ever work.

Did you ever actually compared the performance of max vs sorted? My experience is that sorted performed better. Which is explainable as max loops once over all queue's at every write making it n^2 while sorted sorts all queue's only once and then writes them sequentially.

**Comment by hamelg** [comment]
Thanks !
No, our carbon 0.9.16 runs fine with CACHE_WRITE_STRATEGY=max since years.  I'll try that ...
