### ISSUE TITLE
Feature request: support millisecond metric frequency

### ISSUE THREAD

**Issue by camtarn** [graphite-project/carbon#843]
We're operating a research platform which logs a bunch of metrics at 20Hz. Graphite seems to be the perfect storage and analysis solution for these metrics - we would like to graph them using Grafana, but graphing a year's worth of 20Hz metrics is obviously a no-go, so automatic time series aggregation is perfect.

However, Carbon's metric frequency config only goes down as far as seconds, with no option to specify ms as a unit.

I understand that millisecond metrics are definitely unusual for the type of workload Graphite normally serves - lots of servers submitting metrics fairly infrequently, instead of our case where we have one server submitting very frequent metrics. So I'd understand if this is not a priority - but if it's an easy fix, would you consider supporting it?

Thanks!

**Comment by camtarn** [comment]
Having a read through the code for Whisper, it seems that time is treated as an integer number of seconds in multiple places - selecting which archive file to use, and finding offsets within that file. I'm guessing that means that this definitely isn't easy to support - would that be accurate?

**Comment by deniszh** [comment]
I would say, it's pretty accurate. I think implementing microseconds will be quite hard and not sure how accurate anyway.
