### ISSUE TITLE
New icinga2 service is not recognised by carbon

### ISSUE THREAD

**Issue by Kulturserver** [graphite-project/carbon#846]
We have added a new service (nginx-status) to icinga2, which seems to be working fine and delivers the results assumed. However, this new service is not recognised by carbon and does not appear in the accompanying directory /var/lib/graphite/whisper/icinga2/hostname/services/ - so, no graph is available for this new service, whereas all others are working like expected.

Any help in solving this issue would appreciated - Thanks in advance!

**Comment by piotr1212** [comment]
It seems that carbon works fine but some metrics are not being sent. I would suggest you check the sending side (Icinga). If you are sure the metrics are being sent (verified with a tcpdump or something like that) and they still don't show please reopen this.
