### ISSUE TITLE
Why can not change storage-schemas.conf?

### ISSUE THREAD

**Issue by sevaTechoPark** [graphite-project/carbon#850]
I use dockerfile, and when I COPY this file from host everything is good, but if I try to change this file (in dockerfile with https://www.gnu.org/software/sed/manual/sed.html) this file does not change

I spent 4 hours and I have no idea why is this happening
I am very interested to know, apparently I have spaces in Linux
But I am sure that I change this file right
does not work ONLY in this folder /opt/graphite/conf/

**Comment by deniszh** [comment]
Sorry, not really clear and not really releted to carbon. If related to our docker image - please reopen in  https://github.com/graphite-project/docker-graphite-statsd
Thanks!

**Comment by sevaTechoPark** [comment]
I thing it not releted to docker.
but I have no choice.
https://github.com/graphite-project/docker-graphite-statsd/issues/99
