### ISSUE TITLE
Send Queue is full, carbon not picking up carbon.conf change

### ISSUE THREAD

**Issue by caldavid** [graphite-project/carbon#851]
Hi~

I've been experiencing queuing issue quite frequently with following error, "CarbonClientFactory, send queue is full (10000 datapoints)"

I initially enlarged the "MAX_QUEUE_SIZE = 10000" for relay, but doesn't seems changing the queue size.

Wondering if there is something else i should configure in order to populate the config change? Or if that's the root cause at all?

Thanks!
David

**Comment by deniszh** [comment]
@caldavid : 
Did you restart relay afer changing value?
You put more then 10000 datapoint there, right?

**Comment by caldavid** [comment]
Yes, i restarted the relay after the change, and my new MAX_QUEUE_SIZE = 100000

**Comment by caldavid** [comment]
problem solved. Thanks
