### ISSUE TITLE
Graphite + Tags - stored values not shown

### ISSUE THREAD

**Issue by chuenniger** [graphite-project/carbon#852]
Hi

I use the laste docker image for testing: https://graphite.readthedocs.io/en/latest/install.html

I put some data with tags in the database:

```shell
➜  sl-dashboard git:(master) ✗ python3 create_data_test.py
b'testhuenni.testtags;tagp2=value63 12 1557742824\n'
b'testhuenni.testtags;tagp2=value99 72 1557742826\n'
b'testhuenni.testtags;tagp2=value26 62 1557742828\n'
b'testhuenni.testtags;tagp2=value79 52 1557742830\n'
b'testhuenni.testtags;tagp2=value86 72 1557742832\n'
b'testhuenni.testtags;tagp2=value45 23 1557742834\n'
b'testhuenni.testtags;tagp2=value94 99 1557742836\n'
b'testhuenni.testtags;tagp2=value49 40 1557742838\n'
b'testhuenni.testtags;tagp2=value5 62 1557742840\n'
b'testhuenni.testtags;tagp2=value28 86 1557742842\n'
b'testhuenni.testtags;tagp2=value25 39 1557742844\n'
b'testhuenni.testtags;tagp2=value95 96 1557742846\n'
b'testhuenni.testtags;tagp2=value62 65 1557742848\n'
b'testhuenni.testtags;tagp2=value34 68 1557742850\n'
```

Python3-Script
```python
import graphyte
import time
from random import randint

timeout = 2  # seconds
graphyte.init('localhost', prefix='testhuenni')


def main():
    while True:
        metric = "testtags"  # + str(randint(0, 99))
        value = randint(10, 99)
        tags = {'tagp2': 'value' + str(randint(0, 99))}
        graphyte.send(metric, value, tags=tags)

        time.sleep(timeout)


if __name__ == '__main__':
    main()
```

The result ( http://localhost/render?target=seriesByTag(%27tagp2=~value*%27)&format=json ):

```json

  {
    "target": "testhuenni.testtags;tagp2=value2",
    "tags": {
      "tagp2": "value2",
      "name": "testhuenni.testtags"
    },
    "datapoints": []
  },
  {
    "target": "testhuenni.testtags;tagp2=value21",
    "tags": {
      "tagp2": "value21",
      "name": "testhuenni.testtags"
    },
    "datapoints": []
  },
  {
    "target": "testhuenni.testtags;tagp2=value25",
    "tags": {
      "tagp2": "value25",
      "name": "testhuenni.testtags"
    },
    "datapoints": []
  },
  {
    "target": "testhuenni.testtags;tagp2=value26",
    "tags": {
      "tagp2": "value26",
      "name": "testhuenni.testtags"
    },
    "datapoints": []
  },
  {
    "target": "testhuenni.testtags;tagp2=value28",
    "tags": {
      "tagp2": "value28",
      "name": "testhuenni.testtags"
    },
    "datapoints": [
      [
        null,
        1557656520
      ],
      [
        null,
        1557656580
      ],
      [
        null,
        1557656640
      ]
    ]
  }
]
``` 

as image: 
![Screenshot 2019-05-13 at 12 25 13](https://user-images.githubusercontent.com/188438/57614848-889d9780-757a-11e9-9e79-5fa57d4b14d2.png)

Now you can see my setup. My question: where I can find the stored values (12,72,62,52,72,...)? All datapoints have a `null` value.

**Comment by piotr1212** [comment]
Your storage-schema does not match the interval you send your metrics in. See https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example and https://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf

**Comment by chuenniger** [comment]
Hi @piotr1212 

THNQ for your reply. 

I´ve set the timeout to 12 seconds but nothing changes.

Here ist the configuration from the docker image (set to 10 seconds) - https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-schemas.conf

**Comment by deniszh** [comment]
@chuenniger : timeout doesn't matter. 
Graphite handling every unique combination of tags as a unique metric, so, if you generate them randomly – you will get a unique metric every time. Then, you insert data, it will be written to 1st archive in whisper file, hence 10s:6h. Then, if you asking data more than 6 hours later it will be effectively gone, because there was only 1 point of data, which never was propagated to 2nd archive. because of default xFilesFactor = 0.3 (from https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-aggregation.conf)

**Comment by chuenniger** [comment]
Hi

THNQ for your replies. My goal is to store some metrics for the [Grafana Worlmap Plugin](https://grafana.com/plugins/grafana-worldmap-panel/).

Do you have an example for this?

**Comment by deniszh** [comment]
Hello @chuenniger ,
Which example do you mean?

**Comment by chuenniger** [comment]
> Hello @chuenniger ,
> Which example do you mean?

To store the required data for the Worldmap plugin to graphite. With alle required parameters.

**Comment by deniszh** [comment]
Hello @chuenniger ,
Which data do you need to store? Which parameters do you need, for carbon? Then we need to know which data do you need to store, with which precision and retention.
Sorry, but your question is too generic, you probably need to elaborate it a bit.

**Comment by chuenniger** [comment]
Okay no problem.

I want to use the Worldmap Plugin from Grafana: https://grafana.com/plugins/grafana-worldmap-panel

At the point `Time Series Data as the Data Source` is Graphite in the supported database list.

I want to store required data in `Table format`

```json
"series": [
  {
    "name": "logins.count",
    "tags": {
      "geohash": "9wvfgzurfzb"
    },
    "columns": [
      "time",
      "metric"
    ],
    "values": [
      [
        1529762933815,
        75.654324173059
      ]
    ]
  }
]
``` 
Is that enough information for you?


Regards,
Hu3nn1
