### ISSUE TITLE
Graphite-Carbon processes going down Abruptly with no error

### ISSUE THREAD

**Issue by kondalarao15** [graphite-project/carbon#854]
I've recently installed graphite and grafana on same instance and for some reason carbon processes going down with no error. I'm installed python 2.7.5 and graphite 1.1.5 versions.

I'm using the following carbon.conf file.
[carbon.txt](https://github.com/graphite-project/carbon/files/3182867/carbon.txt)

Current carbon process is up and running

![image](https://user-images.githubusercontent.com/13871668/57782063-0f748080-76f1-11e9-98f8-1daf51e883e4.png)

But intermittently few of the carbon processes are going down and we're missing the metrics.

**Comment by piotr1212** [comment]
There must be something in your carbon log or system logs or coredump, etc.

**Comment by kondalarao15** [comment]
Under carbon-cache-b/query.log 
![image](https://user-images.githubusercontent.com/13871668/57785210-e525c180-76f6-11e9-9664-6621dd8c42eb.png). During that time carbin-cache-b process went down and I didn't see any exceptions in creates.log

**Comment by piotr1212** [comment]
Nothing in your system logs, no core dumps? Only time I've seen carbon go down with nothing in it's log was due to the Linux OOM killer.

**Comment by kondalarao15** [comment]
I don’t have any other system logs, if you see in the first image for carbon process(it’s showing a to h) process but abruptly few of the carbon processes are going down. Can we have a quick meeting regarding this issue.

**Comment by piotr1212** [comment]
> I don’t have any other system logs

What do you mean?

**Comment by kondalarao15** [comment]
I've checked the system logs. These are the logs that are created on 05/12/2019 under /var/log folder. 
![image](https://user-images.githubusercontent.com/13871668/57805733-23d17100-7723-11e9-9b99-c4ac101fd811.png)

Under messages I've seen one error 
![image](https://user-images.githubusercontent.com/13871668/57805927-a65a3080-7723-11e9-9031-914ad273683a.png)
 And  
![image](https://user-images.githubusercontent.com/13871668/57806053-f1744380-7723-11e9-9eb8-32a827d3fcb7.png)

**Comment by piotr1212** [comment]
yup, oom-killer as expected. You are running out of memory, then Linux decides to kill a process.

**Comment by DanCech** [comment]
That will do it, you're trying to run 8 caches and 2 relays so you probably don't have enough memory for all that on your host.

**Comment by kondalarao15** [comment]
Currently I’m using 8 core machine with 16gb ram. Could you please suggest
me what’s  the ideal cpu and RAM requirement for running 8carbon cache and
2 relays.

Or else with current 8core machine with 16gb RAM, how many carbon caches I
can run to avoid carbon downtime.

Thanks

Kondala Rao
8127748943

**Comment by kondalarao15** [comment]
Thanks piotr and DenCech. Currently I've carbon-cache-a to carbon-cache-h and two relays. Now I've commented carbon-cache-c to carbon-cache-h and restarted the graphite carbon. For some reason it's showing three carbon-cache-processes. 
![image](https://user-images.githubusercontent.com/13871668/57867154-3486f300-77c6-11e9-870d-799598da5641.png)

Please see the following file for carbon.conf configuration file
[carbon.txt](https://github.com/graphite-project/carbon/files/3187853/carbon.txt)

**Comment by piotr1212** [comment]
> Could you please suggest me what’s the ideal cpu and RAM requirement for running 8carbon cache and 2 relays.

There are just too many variables to give an simple answer. Disk performance, number of metrics, metric interval, storage schema's, etc.
