### ISSUE TITLE
carbon install via pip doesn't show up in "pip freeze" Edit

### ISSUE THREAD

**Issue by mleinart** [graphite-project/carbon#86]
#### Imported from https://bugs.launchpad.net/bugs/1022576
|||
|----|----|
|Reported by|[jlintz](https://launchpad.net/~jlintz)|
|Date Created|Jul 09, 2012|
|Tags|[u'carbon', u'install', u'pip', u'setup']|When installing carbon via "pip install carbon", the package doesn't properly register within pip and does not showup doing a "pip freeze"

**Comment by obfuscurity** [comment]
We need to fix this for `0.9.13`. After further consideration I just don't think it's reasonable to ask users to set PYTHONPATH like this to fix problems in both Carbon and Graphite-Web.

**Comment by obfuscurity** [comment]
Sorry for the milestone tom-foolery, this is indeed `1.0.0` material due to the prefix changes required.

**Comment by obfuscurity** [comment]
The installation docs now formally instruct the user to set `PYTHONPATH` before installing via pip. Fixed in https://github.com/graphite-project/graphite-web/commit/1904348a6adbdf3eecb0c31442285fe759061f13.
