### ISSUE TITLE
Getting CarbonClientFactory related issue

### ISSUE THREAD

**Issue by caldavid** [graphite-project/carbon#861]
Hi,

I've been experiencing the data delay, and found committed-points has been always below Metrics-received, then found below error in the client.log:

> Destination is up: my_IP:2014:None
> CarbonClientProtocol(my_IP:2014:None)::connectionLost Connection to the other side was lost in a non-clean fashion.
> CarbonClientFactory(1my_IP:2014:None)::clientConnectionLost (my_IP:2014) Connection to the other side was lost in a non-clean fashion.
> Destination is down: my_IP:2014:None (1/5)
> CarbonClientFactory(my_IP:2014:None)::startedConnecting (my_IP:2014)
> CarbonClientProtocol(my_IP:2014:None)::connectionMade
> CarbonClientFactory(my_IP:2014:None)::connectionMade (CarbonClientProtocol(my_IP:2014:None))
> 

wondering what went wrong?

Thanks,
David

**Comment by caldavid** [comment]
![Screen Shot 2019-07-29 at 12 03 31 PM](https://user-images.githubusercontent.com/27234781/62075119-1fcccf80-b1f9-11e9-9792-30a936110a54.png)
here is what the trend looks like

**Comment by caldavid** [comment]
some more log from console.log:

Stopping factory CarbonClientFactory(my_IP:2014:None)
Starting factory CarbonClientFactory(my_IP:2014:None)
<twisted.internet.tcp.Connector instance at 0x7f41e6fea2d8> will retry in 2 seconds

**Comment by piotr1212** [comment]
overloaded caches? This is your relay log right?

**Comment by caldavid** [comment]
Thanks for looking into the issue!

This is from both **graphite/storage/log/carbon/console.log,** and **graphite/storage/log/carbon/client.log**

Does graphite support multiple carbon-cache instances running in parallel on the same box?
