### ISSUE TITLE
Large droppedCreates carbon agents

### ISSUE THREAD

**Issue by alexmaccabi** [graphite-project/carbon#862]
Hello,
I`m having an issue with carbon whisper based files storage.

- 10 relay nodes

- 3 data nodes 

- whisper and carbon version: 1.1.5  

Sending about 100K per minute.
We have found an issue of large droppedCreates metrics.

![droppedcreates](https://user-images.githubusercontent.com/3840250/62080524-8386e500-b259-11e9-8bb2-6b49910164cd.JPG)

Checking number of creates, and found out that it won't go past 50.
event trough: MAX_UPDATES_PER_SECOND and MAX_CREATES_PER_MINUTE set to inf

![creates](https://user-images.githubusercontent.com/3840250/62080572-9c8f9600-b259-11e9-9875-63c706088267.JPG)

**Comment by deniszh** [comment]
I’m not sure that Inf is valid value there. Did you try some sane values
for max creates, e.g. 1000 ?

**Comment by alexmaccabi** [comment]
Hello, it was a mistake by my part.
graphite is running on k8s, there was a config map for carbon.conf that was overwriting the docker config.
I tested it with inf and I don't see the droppedCreates.
cheers
