### ISSUE TITLE
[Q]Carbon-cache consuming 100% of CPU; metrics are fed with gaps as depicted on webapp; I added an extra core of CPU, but of no luck; can somebody assist, please.

### ISSUE THREAD

**Issue by AgastyaTanuj** [graphite-project/carbon#896]

**Comment by deniszh** [comment]
@AgastyaTanuj : carbon is not scaling automatically, you need to add more carbon caches. What's your installation type - docker, packages, or sources?

**Comment by AgastyaTanuj** [comment]
Thanks for response. It is installed from EPEL repo; running on version 0.9.15. 45k metrics are accumulated onto this graphite VM.
