### ISSUE TITLE
[Q] Regarding Graphite cluster data retention

### ISSUE THREAD

**Issue by AshishVerma7690** [graphite-project/carbon#898]
I am running graphite on 3 node, suddenly 2 of the nodes goes down and data coming on both  nodes ( 2, 3 ) stopped. 
I have restarted the node, but the data is lost ( for the time it is down).

Is there any way that I can get the data back?

**Comment by Jason-TJW** [comment]
You can use carbon-sync command to sync up data from node 1.
For more details please refer to https://github.com/graphite-project/carbonate
