### ISSUE TITLE
Handling SSL authentication with the basic protocol

### ISSUE THREAD

**Issue by athoune** [graphite-project/carbon#91]
I'm working for Bearstech, a web hosting company. Using a mutualized carbon server can be messy with lots of users. For now, I add a stunnerl proxy for using authentication with a lightly patched statsd python clone. AMQP is too heavy, I wont to use simple client, post mortem log reader or statsd like tools.

This blog presents my hack :
http://blog.bearstech.com/2013/03/authenticate-everything-with-ssl.html

Is it possible to let carbon handling such security and authentication?
I would like to publish a pull request, but I had some troubles with Twisted voodoo.

**Comment by ewollesen** [comment]
:+1:  Would love to see this as well. Using stunnel in the meantime.
