### ISSUE TITLE
[Q] carbon-cache or carbon-relay log file contains binary data

### ISSUE THREAD

**Issue by Jason-TJW** [graphite-project/carbon#912]
I use graphite 1.1.2 and the log file contains binary data which fills up the disk. I am not sure why it contains the binary data, please help. Thanks.

[root@pl-2 carbon-cache-a]# file /var/log/graphite/carbon-cache-a/*
**/var/log/graphite/carbon-cache-a/console.log:                        data**
/var/log/graphite/carbon-cache-a/listener.log:                       ASCII text
/var/log/graphite/carbon-cache-a/query.log:                          ASCII text
/var/log/graphite/carbon-cache-a/tagdb.log:                          ASCII text, with very long lines

Use vi command to check the file, I can see many special character **^@** in it.

**Comment by deniszh** [comment]
Hi @Jason-TJW ,

Sorry, I have no idea why could that happen. Looks like nobody else too....
