### ISSUE TITLE
[Q] New whisper file creation is not being logged

### ISSUE THREAD

**Issue by justinclloyd** [graphite-project/carbon#913]
I've recently replaced an old AWS Graphite server with a new one running Ubuntu 20.04 with carbon, whisper, and graphite-web versions 1.2.0 installed via pip from their GitHub repos (via SaltStack git.installed states). I noticed during troubleshooting that whisper file creation is not being logged in creates.log files under the carbon-cache processes' log directories (/var/log/carbon/carbon-cache-{instance}). Is this possibly a bug in carbon? The previous server (running a very old version on Ubuntu 16.04) was writing these files just fine.

**Comment by deniszh** [comment]
Maybe defaults are changed? You need to have `LOG_CREATES = True` in `carbon.conf` because default value is False.

**Comment by justinclloyd** [comment]
Ah, that seems to be it. I don't see that same parameter in the old carbon.conf so it must've been added since then. Thanks!
