### ISSUE TITLE
[Q]Handling of duplicate values

### ISSUE THREAD

**Issue by Lokanath-Cell** [graphite-project/carbon#916]
Hi,

Can you guys let me know how duplicate values with same namespace , Value and Time are handled by Carbon, Will they be written in to Whisper DB or rejected?
We have some cases where duplicate values are expected and want to know if there is build in redundancy mechanism? 

Thank you
Best Regards

**Comment by deniszh** [comment]
Hi @Lokanath-Cell ,

Data in whisper storage is bound to slots. So, if you have 2 measurements which come to same slot only last one will be saved. E.g. if your resolution is 1 minute all measurements  for specific metric for that particular minute will collapsed into single value - last one.
