### ISSUE TITLE
Migrating to travis-ci.com?

### ISSUE THREAD

**Issue by V-mourya** [graphite-project/carbon#920]
The travis-ci.org site will not run any new builds after June 15th, 2021.
Do we have any plans to migrate the repository to travis-ci.com? This is important for architectures like s390x which have CI support through Travis only.

**Comment by deniszh** [comment]
I had plans to migrate to GHA completely, but unfortunately that's not am option for s390 and ppc64le
Thanks for reminder, will try to do migration.

**Comment by V-mourya** [comment]
@deniszh Any update on this?

**Comment by deniszh** [comment]
Sorry, I'm offline currently, will check on the weekend

**Comment by deniszh** [comment]
I'm still not sure what to do here TBH. Travis behaviour as a company not becoming better, and I would prefer not to use it. But I do not see alternatives for it. :(
If someone knows - please let me know.

**Comment by V-mourya** [comment]
> I'm still not sure what to do here TBH. Travis behaviour as a company not becoming better, and I would prefer not to use it. But I do not see alternatives for it. :(
> If someone knows - please let me know.

Can you please elaborate more about the Travis behaviour so that we can get issue points and check with Travis to get them resolved.

**Comment by deniszh** [comment]
@V-mourya 

I'm doubt that this can be solved. Just google "travis security breach", it's all over the news. E.g. https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/
