### ISSUE TITLE
[Q] Is it possible to add tags to existing time series

### ISSUE THREAD

**Issue by rgoadvice** [graphite-project/carbon#924]
Dear Graphite-Team,

is it possible to add tags to existing time series (meaning: without losing its history)?

Thanks!
Ralf

**Comment by deniszh** [comment]
Hi @rgoadvice 

No, unfortunately not - metric with tags and metric without tags are two different metrics.

**Comment by rgoadvice** [comment]
Thanks for the quick response and clarification!
