### ISSUE TITLE
[BUG] carbon-cache.py differs between source and pip

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [graphite-project/carbon#942]
**Please report bug only for carbon component here, if you want to to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
the version of carbon-cache.py that is installed by the 1.1.10 source and the version installed by pip3 are subtly different.

**To Reproduce**
install carbon from source using the 1.1.10 tag
```
cd /opt/; git clone https://github.com/graphite-project/carbon.git; git --git-dir=/opt/carbon/.git --work-tree=/opt/carbon checkout 1.1.10;
```
install carbon from pip3
```
python3 -m pip install carbon==1.1.10
```
diff the two scripts
```
diff /opt/carbon/bin/carbon-cache.py /usr/local/bin/carbon-cache.py
```
note they have a difference in the header
```
1c1
< #!/usr/bin/env python
---
> #!/usr/bin/python3
```

**Expected behavior**
the code from source and from the pip3 package should be identical if version is the same

**Environment (please complete the following information):**
 - OS flavor: Ubuntu 20.04
 - Graphite version 1.1.10
 - Setup type: pip and source
 - Python version 3.8

**Additional context**
Trying to setup a working environment, bouncing between pip installed, and source installed. noticed that the pip3 installed can by invoked directly but the source installed doesnt use python3.

**Comment by deniszh** [comment]
Hi @jgrammen-agilitypr 

> the code from source and from the pip3 package should be identical if version is the same

Could you please elaborate why do you think it should be the same?

**Comment by jgrammen-agilitypr** [comment]
1.1.10 should be the same no matter how you install it, should it not? As a user I would expect a package to be identical regardless of what method is chosen to install the package.
I would not expect the pip3 version to have a python3 compatible shebang but the source version to have only a python2 compatible shebang

**Comment by deniszh** [comment]
I understand your concern, but I'm not aware  that pip3 or any python packaging tool giving you such promise.
You're use python3 during installation and git python3 in shebang. Still not sure that's an issue, for me it looks like work as intended

**Comment by jgrammen-agilitypr** [comment]
I guess then my question is why is the source version not using the python3 shebang?
and 
as a clarification are you telling me that pip3 is modifying the /usr/local/bin/carbon-cache.py during installation?

**Comment by deniszh** [comment]
> why is the source version not using the python3 shebang?

Because we didn't officially dropped python2 support, it's still there for 1.1.x branch. I have plans to drop it in 1.2.x only

> are you telling me that pip3 is modifying the /usr/local/bin/carbon-cache.py during installation?

Pip is compex tool, I would not be surprised if it did

**Comment by jgrammen-agilitypr** [comment]
ok thank you for clarifying what is happening. closing.
