### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by damaestro** [graphite-project/carbon#946]
Please add Python 3.12 support.

https://github.com/graphite-project/carbon/pull/945

**Comment by damaestro** [comment]
We should still merge Python 3.12 support.

I've already applied this patch [downstream](https://src.fedoraproject.org/rpms/python-carbon/c/4d8f7c621b261b29649bfd4a198326eda6fa1be5) in the Fedora Project.

**Comment by deniszh** [comment]
FYI here - currently Graphite have issues with python 3.11 and newer, because new pip breaks install layout and old pip stopped working with 3.11

**Comment by deniszh** [comment]
@damaestro : agreed, but for some reason your PR is not triggering tests, even after rebase.

**Comment by damaestro** [comment]
Resolved in https://github.com/graphite-project/carbon/pull/951
