### ISSUE TITLE
Delay in metrics being available

### ISSUE THREAD

**Issue by ziegeer** [graphite-project/carbon#95]
I'm seeing it take anywhere from a few minutes to more commonly ~30 minutes for incoming metrics to become visible in the Graphite gui or via the url api.  My cache is large, but shouldn't it be querying the cache and seeing the metric in it and acting as if it were on disk?  FWIW, I have four servers running carbon and graphite-web and they all receive metrics from a single relay node.  Though in my testing of this I usually just send straight to a carbon node to cut out the relay as a source of problems.  Anyone have any troubleshooting ideas?

**Comment by zakjan** [comment]
Is it posible to flush the cache manually somehow? It is really uncomfortable when testing a new metric.

**Comment by deniszh** [comment]
Hi @zakjan,

For 0.9.x you can try to apply patches from https://github.com/graphite-project/carbon/pull/419 for carbon and https://github.com/graphite-project/graphite-web/pull/1277 for graphite-web.
Then you can flush metrics by API call like ```curl "http://localhost/metrics/flush-cache?metric=^metricname" -X POST```

There's a plans to add it to  master to sometimes.
